### ISSUE TITLE
Delete unused images

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#10]
I'm unfamiliar with Capacitor Lab Basics and know it is under development, but the "unused image" reporter is indicating several images that are unused:
https://github.com/phetsims/chipper/issues/189

If they *will eventually* be used, you can ignore this warning and close this issue.  If they won't be used, please remove them and their associated entries in license.json:

closeButton.png
probe_3D_black_large.png
probe_3D_black_large_cutout.png
probe_3D_field.png
probe_3D_field_cutout.png
probe_3D_field_large.png
probe_3D_red_large.png
probe_3D_red_large_cutout.png
probe_3D_red_large_outline.png
sliderKnob.png
sliderKnobHighlight.png
voltmeter.png

**Comment by jessegreenberg** [comment]
Thanks @samreid, I removed images that I do not expect will be in the final version of capcator-lab-basics.  The remaining two images will be added shortly.  Closing.
