### ISSUE TITLE
Add stroke to voltmeter probes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#100]
There isn't much contrast between the tip of the voltmeter probe and the capacitors, which makes them a bit hard to see. During today's design meeting we decide to add a 0.25 pt stroke to the probe. I've emailed the updated assets to @andrewadare for implementation.

**Comment by andrewadare** [comment]
I forgot to reference this issue in the commit, but cd7eb4a50f092efbe2a5f3efb6aec00c527c09b5 has the new images from @arouinfar .

**Comment by andrewadare** [comment]
If this looks good now, feel free to close.

**Comment by arouinfar** [comment]
Looked at the latest in master, and the new assets look good. Thanks @andrewadare!
