### ISSUE TITLE
Make battery slider more attractive

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#102]
During interviews, students took awhile to discover the battery slider (one took 20s, and the other 90s). We want students to interact with the battery early on in their exploration, so we've decided to make a few changes to the slider thumb. Namely, adding a thicker gray stroke around the edge and making the thumb a bright color -- yellow, most likely.

![image](https://cloud.githubusercontent.com/assets/8419308/15412579/e29e4378-1de5-11e6-99a5-de74375db91c.png)

Self-assigning to find a suitable shade of yellow.

**Comment by arouinfar** [comment]
This color combination seems to work nicely, even in colorblind preview modes
![image](https://cloud.githubusercontent.com/assets/8419308/15478543/34f643e2-20d8-11e6-8eba-3278c503a4a3.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/15478550/3ef49f42-20d8-11e6-81c9-a55825f70d31.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/15478560/4b403e82-20d8-11e6-919f-b42f0cd49f7f.png)

Thumb: RGB (255, 237, 53)
Stroke (2pt): RGB (191, 191, 191)

**Comment by arouinfar** [comment]
Brighter yellows have somewhat poorer contrast with the top of the battery in colorblind preview.

**Comment by arouinfar** [comment]
@andrewadare here are the RGB values for the for the slider:

> Thumb: RGB (255, 237, 53)
Stroke (2pt): RGB (191, 191, 191)

**Comment by andrewadare** [comment]
Sorry for the confusion, looks like you did have the final color choice written down. I read through the issue too quickly. Battery looks like this now:
![image](https://cloud.githubusercontent.com/assets/154163/15584287/291e1656-2337-11e6-8c0f-015a502689c8.png)

**Comment by arouinfar** [comment]
Looks good @andrewadare. Can the gray stroke be made 1 pt/px heavier?
