### ISSUE TITLE
[PhET-iO] Reconsider slider value ranges

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#104]
@samreid @andrewadare the slider ranges in the instance proxies wrapper need to be reconsidered. All ranges are at a default [0,1]. This doesn't work with most (if any) sliders in the wrapper. Some examples:

`model.circuit.battery.voltageProperty` and `model.circuit.switchedCapacitor.platesVoltageProperty` should have a range set to something more like [-1.5,1.5]. Currently a user is unable to flip the battery nor reach its maximum voltage.

**`model.circuit.disconnectedPlateChargeProperty` completely kills the browser when being used!!! The range in the sim is incredibly small with a max number of maybe 1.06248e-12. Trying to slide this value between 0 and 1 is more than likely overloading the sim. Note: only happens when the plate is actually disconnected from anything.**

`model.circuit.switchedCapacitor.plateSeparationProperty` errors when equal to 0 (breaking the sim), and the plates go wildly off screen when slid to a value >0.07.

`model.circuit.currentAmplitudeProperty` is constrained to the positive, so arrows can only point one way. This slider is also wildly difficult to use, maybe filter it out?

`model.voltmeter.valueProperty` certainly needs attention. Hopefully it's obvious.

Does `model.circuit.switchedCapacitor.dielectricOffsetProperty` even do anything?? Or is this vestigial code?

I might be missing some examples, but please consider setting these ranges more consciously. For phetsims/phet-io/issues/440

**Comment by samreid** [comment]
Some ideas about how to proceed with this:

In the sim code, when constructing a Property, provide the metadata there such as:

```js
new Property(0,{min:0,max:123,units'meters'});
```
Then the Property could do error checking in the sim code.  The min/max/units could be retrieved over the PhET-iO API.  On the other hand, it may be useful to have it statically in the API, but this seems like a way to provide the data to both the sim and the API without duplicating it.

**Comment by samreid** [comment]
@andrewadare and I are moving the number metadata to TNumber.

**Comment by samreid** [comment]
This work will hinge on getting the API exported from the sim.

**Comment by samreid** [comment]
We've got this primarily working, but still need to update simulations with the correct ranges.  We can do that on a sim-by-sim basis, as part of new separate issues.  We will discover these problems in review or testing with instance-proxies.
