### ISSUE TITLE
[PhET-iO] Missing home screen instrumentation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#105]
@samreid @andrewadare In CLB instance proxy wrapper, I'm not able to make anything on the home screen interactable after launch. So if the sim is launched from this state, the sim is unusable.

It looks like the sim is missing some crucial intrumentation, notably the below list, that are all set to false and not under my control (they aren't in the list of proxies). If I remember correctly, the below are customizable in other instrumented sims:
![morefalsestuff](https://cloud.githubusercontent.com/assets/5863899/15441056/fd8344ee-1e95-11e6-834b-2f589ea3902e.PNG)
![falsestuff](https://cloud.githubusercontent.com/assets/5863899/15441065/0563ca08-1e96-11e6-81f3-e6bd37e81689.PNG)

Side note, ignore the showHomeScreen in the above list being false, that part of the screenshot was taken from a different state.

Seen this on Win 10 Chrome & FF, OSX 10.11.5. No errors in the console or anything either. For phetsims/phet-io/issues/440.

**Comment by samreid** [comment]
Sounds like the `pickable` buttons aren't being properly initialized.

**Comment by phet-steele** [comment]
@samreid, BLL is also missing home screen instrumentation.

**Comment by samreid** [comment]
Fixed above, closing.
