### ISSUE TITLE
Can we use null instead of NaN for voltages?

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#111]
The simulation uses NaN for when a probe is not touching a component with a voltage.  NaN doesn't play nice with Property.js since NaN!==NaN.  Can the NaNs here be converted to null instead?  This would also address #87

**Comment by andrewadare** [comment]
I'll take a look today.

**Comment by jessegreenberg** [comment]
Thanks @andrewadare!  I think use of ```Number.NaN``` is just an artifact from the port since ```Double.NaN``` was used in the Java.  I can't think of a reason why using ```null``` should be an issue.
