### ISSUE TITLE
Refactor ConnectionAreaNode and ConnectionPointNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#115]
While cleaning up #29 I noticed that ConnectionAreaNode and ConnectionPointNode are redundant.  These two objects can probably be collapsed into a single file.  This would probably improve the maintainability of the input listeners.

**Comment by andrewadare** [comment]
@jessegreenberg This change never made it into the code, and we're heading into RC testing and code review. Given that the existing code has been heavily tested, I'm inclined to skip this refactor and mark it as a deferred task. If you have any objections to that, please let me know.

**Comment by jessegreenberg** [comment]
@andrewadare I would probably fix this issue as part of the code review, it will probably come up then anyway.  "collapsing into a single file" is likely not appropriate, but maybe inheritance would be help reduce  the duplicate code.  I was thinking that things like the constants, ```resetPinColors``` and the input listeners might be moved to a supertype.  tandem might make it harder to generalize the listeners now.

**Comment by andrewadare** [comment]
@jessegreenberg I took another look at these two files, and I put the three common constants into CLBConstants.

After that, there's very little duplicated code:
![image](https://cloud.githubusercontent.com/assets/154163/20156421/77d46532-a68d-11e6-833f-5d9d7d491c09.png)

These types have different constructor signatures, different parents, and different listener implementations. Changing the inheritance structure and introducing a new supertype would allow us to factor out the two-line resetPinColors function, and that's about it. So my vote is to leave them they are, but if I'm missing something about the design, please let me know.

**Comment by jessegreenberg** [comment]
@andrewadare thanks for looking into this!  I hadn't really thought through this fully, only noticed some common patterns that might be factored out.  The comparison you showed aboved proves that creating a common type doesn't make sense here.  I agree that https://github.com/phetsims/capacitor-lab-basics/commit/ec05f9e3eb05c607f0c4c361e22e9ade9ca50e0e is the most maintanable option at this point.  Closing.
