### ISSUE TITLE
Code Review 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/capacitor-lab-basics#117]
*NOTE! Prior to doing a code review, copy this checklist to a GitHub issue for the repository being reviewed.*

PhET code-review checklist
=============

**Build and Run Checks**

- [x] Does the sim build without warnings or errors?
- [x] Does the sim start up? (requirejs and built versions)
- [x] Does the sim experience any assertion failures? (run with query parameter 'ea')
- [x] Does the sim pass a scenery fuzzer test? (run with query parameter 'fuzzMouse&ea')

**Internationalization**
- [x] Are there any strings that are not being internationalized? (run with query parameter 'stringTest=x', you should see nothing but 'x' strings)
- [x] Does the sim layout gracefully handle internationalized strings that are twice as long as the English strings? (run with query parameter 'stringTest=double')
- [x] Does the sim layout gracefully handle internationalized strings that are exceptionally long? (run with query parameter 'stringTest=long')
- [x] Does the sim layout gracefully handle internationalized strings that are shorter than the English strings? (run with query parameter 'stringTest=X')
- [x] Does the sim stay on the sim page (doesn't redirect to an external page) when running with the query parameter 'stringTest=xss' (test passes if sim does not redirect, OK if sim crashes or fails to fully start). Only test on one desktop platform.
- [x] Make sure the string keys are all perfect, they are difficult to change after 1.0.0 is published.  Strings keys should
generally match the values, such as `{binaryProbability: "Binary Probability"}`. Screen names should use `screen.screenName` instead of
camelcase.  Message patterns and long paragraphs will also use a different pattern.

**Repository structure**

- [x] Are all required files and directories present?

      For a sim repository named “my-repo”, the general structure should look like this (where assets/, audio/ or images/ may be omitted if the sim doesn’t have those types of assets).

```js
   my-repo/
      assets/
      audio/
         license.json
      doc/
         model.md
         implementation-notes.md
      images/
         license.json
      js/
         (see section below)
      .gitignore
      my-repo_en.html
      my-repo-strings_en.json
      Gruntfile.js
      LICENSE
      package.json
      README.md
```

   For a common-code repository, the structure is similar, but some of the files and directories may not be present if the repo doesn’t have audio, images, strings, or a demo application.

- [x] Is the js/ directory properly structured?

      All JavaScript source should be in the js/ directory. There should be a subdirectory for each screen (this also applies for single-screen sims, where the subdirectory matches the repo name).  For a multi-screen sim, code shared by 2 or more screens should be in a js/common/ subdirectory. Model and view code should be in model/ and view/ subdirectories for each screen and common/.  For example, for a sim with screens “Introduction” and “Lab”, the general directory structure should look like this:

```js
   my-repo/
      js/
         common/
            model/
            view/
         introduction/
            model/
            view/
         lab/
            model/
            view/
         my-repo-config.js
         my-repo-main.js
         myRepo.js
 ```

- [x] Is there a file in assets/ for every resource file in audio/ and images/? Note that there is *not necessarily* a
1:1 correspondence between asset and resource files; for example, several images may be in the same .ai file.
- [x] Was the README.md generated by `grunt published-README` or `grunt unpublished-README`?
- [x] Does package.json refer to any dependencies that are not used by the sim?
- [x] Does sim-config.js refer to any dependencies that are not used by the sim?
- [x] Is the LICENSE file correct? (GPL v3 for sims, MIT for common code)
- [x] Does .gitignore match the one in simula-rasa?
- [x] Are the credits in sim-main.js correct?
- [x] Are there git repository branches that are no longer used and should be pruned?

**Coding conventions**

- [x] Does the code meet PhET's code-style guidelines, as described in the [“Coding Style Guidelines” section of "PhET Development Overview"](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w)?
- [x] Is the code formatted according to PhET conventions? See [phet-idea-code-style.xml](https://github.com/phetsims/joist/blob/master/util/phet-idea-codestyle.xml) for IntelliJ IDEA code style.

**Documentation**

- [x] Are documentation conventions followed, as described in the [“Coding Style Guidelines” section of the PhET Development Overview](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#heading=h.1oxr3ptyo50w)?
- [x] Does model.md adequately describe the model, in terms appropriate for teachers?
- [x] Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers?
- [x] Are sim-specific query parameters (if any) identified and documented in one .js file in js/common/ or js/ (if there is no common/)? The .js file should be named `{{REPO}}QueryParameters`, for example ArithmeticQueryParameters for the aritmetic repository.

**Math Libraries**

- [x] Check that `dot.Util.roundSymmetric` is used instead of `Math.round`. `Math.round` does not treat positive and negative numbers symmetrically, see https://github.com/phetsims/dot/issues/35#issuecomment-113587879.
- [x] `dot.Util.toFixed` or `dot.Util.toFixedNumber` should be used instead of `toFixed`. JavaScript's `toFixed` is notoriously buggy. Behavior differs depending on browser, because the spec doesn't specify whether to round or floor.
- [x] Check that random numbers are generated using `phet.joist.random`, and are doing so after modules are declared (non-statically).  For instance, the following methods (and perhaps others) should not be used:
* `Math.random`
* `_.shuffle`
* `_.sample`
* `_.random`
* `new Random()`

**Organization, Readability, Maintainability**

- [x] Does the organization and structure of the code make sense? Do the model and view contain types that you would expect (or guess!) by looking at the sim? Do the names of things correspond to the names that you see in the user interface?
- [x] Are appropriate design patterns used?
- [x] Is inheritance used where appropriate? Does the type hierarchy make sense?
- [x] Is there any unnecessary coupling? (e.g., by passing large objects to constructors, or exposing unnecessary properties/functions)
- [x] Is there too much unnecessary decoupling? (e.g. by passing all of the properties of an object independently instead of passing the object itself)?
- [x] Are the source files reasonable in size? Scrutinize large files with too many responsibilities - can responsibilities be broken into smaller delegates?
- [x] Are any significant chunks of code duplicated? This will be checked manually as well as with https://github.com/danielstjules/jsinspect
- [x] Is there anything that should be generalized and migrated to common code?
- [x] Are there any TODO or FIXME comments in the code?  They should be addressed or promoted to GitHub issues.
- [x] Does the implementation rely on any specific constant values that are likely to change in the future? Identify constants that might be changed in the future. (Use your judgement about which constants are likely candidates.)
Does changing the values of these constants break the sim? For example, see https://github.com/phetsims/plinko-probability/issues/84.
- [x] The simulation should use Property instead of PropertySet
- [x] Are all dependent properties modeled as DerivedProperty instead of Property?

**Performance, Usability**

- [x] Does the sim perform as desired across the range of supported platforms? (eg, not too slow on slow platforms, not too fast on fast platforms)
- [x] If the sim uses WebGL, does it have a fallback? Does the fallback perform reasonably well? (run with query parameter 'webgl=false')
- [x] Are UI components sufficiently responsive? (especially continuous UI components, such as sliders)
- [x] Are pointer areas optimized, especially for touch? (run with query parameter 'showPointerAreas')
- [x] Do pointer areas overlap? (run with query parameter 'showPointerAreas')
- [x] Is the timestep `dt` capped appropriately?  Try switching applications or browser tabs, then switch back.  Did the model take one big/long/awkward step forward?  If so, `dt` may need to be capped.  Example from `faradays-law.FaradaysLawModel`:

```js
// Cap large dt values, which can occur when the tab containing
// the sim had been hidden and then re-shown
dt = Math.min( 0.1, dt );
```

**Memory Leaks**

- [x] Does a heap comparison using Chrome Developer Tools indicate a memory leak? (Describing this process is beyond the scope of this document.)
- [x] For each common-code component (sun, scenery-phet, vegas, …) that opaquely registers observers or listeners, is there a call to that component’s dispose function, or documentation about why dispose is unnecessary?
- [x] Are there leaks due to registering observers or listeners? These guidelines should be followed, or documentation added about why following them is not necessary:
	- [x] AXON: `Property.link` is accompanied by `Property.unlink`.
	- [x] AXON: `PropertySet.link` is accompanied by `PropertySet.unlink`.
	- [x] AXON: Creation of `DerivedProperty` is accompanied by `dispose`.
	- [x] AXON: Creation of `Multilink` is accompanied by `dispose`.
	- [x] AXON: `Events.on` is accompanied by `Events.off`.
	- [x] AXON: `Emitter.addListener` is accompanied by `Emitter.removeListener`.
	- [x] SCENERY: `Node.on` is accompanied by `Node.off`
	- [x] TANDEM: `tandem.addInstance` is accompanied by `tandem.removeInstance`.
- [x] Do all types that require a `dispose` function have one? This should expose a public `dispose` function that calls
`this.disposeMyType()`, where `disposeMyType` is a private function declared in the constructor.  `MyType` should exactly
match the filename.

**PhET-iO**

- [x] If the simulation is supposed to be instrumented for PhET-iO, please see [How to Instrument a PhET Simulation for PhET-iO]
(https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md)
for the PhET-iO development process.

**Comment by jessegreenberg** [comment]
Discussed 6/30/16, @jbphet will likely do the review (Thanks!) but will be done in a few weeks.

**Comment by andrewadare** [comment]
@ariel-phet speaking optimistically, if https://github.com/phetsims/tasks/issues/706 goes well, then it's not too early to begin arranging the code review for CL:B as we head towards the RC phase.

**Comment by ariel-phet** [comment]
@andrewadare sounds good. Will probably discuss at dev meeting unless it needs to be started beforehand.

**Comment by ariel-phet** [comment]
@jonathanolson will tackle the review when @andrewadare feels it is ready (approx 8 hour for review)

**Comment by ariel-phet** [comment]
@andrewadare just double checking, this is not quite ready for review, correct? I assume you want to address the dev testing issues first? If otherwise feel free to assign to @jonathanolson when ready.

**Comment by andrewadare** [comment]
@ariel-phet I think that's right. I not only want to address the dev test issues, but also apply the PropertySet updates discussed yesterday. I'll let @jonathanolson know when this is good to start reviewing.

**Comment by ariel-phet** [comment]
Sounds good

**Comment by andrewadare** [comment]
CL:B is getting very close to the RC stage. The only known outstanding bug, #148, just evaporated. After all the work done for #151, #152, #153, #154, and #155, one more dev round would be prudent. 

Once I finish #149, and probably https://github.com/phetsims/phet-io/issues/748, the sim will be ready to turn over to @jonathanolson for code review (just a heads up).

**Comment by jonathanolson** [comment]
Heard it is ready for a code review. Added checklist, assigning.

**Comment by jonathanolson** [comment]
I've done an initial pass for the model. There are enough recommended changes that it would probably be best for me to wait to do more in-depth model review until most of the mentioned review items have been handled.

I'll plan to continue with the view review for now.

**Comment by andrewadare** [comment]
@ariel-phet I've been going through the REVIEW comments generated from @jonathanolson so far. There are over 600 remaining. He is a good man, and thorough.

This is just a heads up that although many of them will be quick to address (e.g. visibility documentation), several involve more significant code design changes, so your comment in today's meeting that these are addressable in a day or so may be optimistic.

**Comment by jonathanolson** [comment]
Also, most of my notes are just recommendations; if you disagree one is beneficial, it would be great to discuss.

**Comment by andrewadare** [comment]
@jonathanolson so far all recommendations have been very valuable and worth implementing.

**Comment by ariel-phet** [comment]
@andrewadare no problem, there is no official "deadline" associated with CL:B and @jonathanolson's review comments are partially meant as teachable moments to improve your coding chops.

(and yes I caught the Big Lebowski reference, but I did not have a clever retort....)

**Comment by ariel-phet** [comment]
@andrewadare I would also say if it looks like it will be a longer haul, just split your time between CL:B and EFAC if possible just keep forward momentum on both with a bit of a skew toward CL:B

**Comment by andrewadare** [comment]
GH auto-closed this due to the "fixes" keyword. Don't love that feature.

updatePlateVoltages in ParallelCircuit has this review comment:
```
//REVIEW: First two logic cases are shared with CapacitanceCircuit. Can we factor this out?
```
The two functions don't quite share identical conditional statements, and the repeated code is only a few simple lines, so this is one of the *very* few instances where I'd prefer to keep the code as-is.

**Comment by jonathanolson** [comment]
> GH auto-closed this due to the "fixes" keyword. Don't love that feature.

I'll typically exclusively put "see ISSUE" or "fixes ISSUE" when referencing issues in commit messages. The "see" part keeps it from closing, even if you included "fixes" earlier in the message.

> The two functions don't quite share identical conditional statements, and the repeated code is only a few simple lines, so this is one of the very few instances where I'd prefer to keep the code as-is.

Sure, sorry!

**Comment by andrewadare** [comment]
The getMaxEffectiveEField functions in CapacitanceModel and CLBLightBulbModel have long been a problem. 

* They have a very awkward implementation: they construct temporary circuit model elements, configured for maximum E-field.
* The temporary components are awkward for PhET-iO. We don't want them instrumented, because they're just an implementation detail. This originally led to passing null Tandem instances which caused annoyances for months. @samreid and I later contrived a workaround for the tandem issue (the `enabled: false` approach), but it required tedious explanation in the comments.
* The two model subtypes duplicate a bunch of logic.
* The temporary components require disposal after use, which was missing, and is another annoyance.

Why can't we just compute the max E-Field in the supertype (since the capacitor is the same in both screens) like this?
![img_0732](https://cloud.githubusercontent.com/assets/154163/20981917/a2cf85e0-bc73-11e6-8803-86aae5dde510.JPG)

It gives the same answer, algebraically, using only values from CLBConstants.

**Comment by andrewadare** [comment]
I was able to make a similar simplification for getMaxPlateCharge in CLBModel, which has a side benefit of paving the way for consolidating the Capacitor and SwitchedCapacitor (another review item).

**Comment by jonathanolson** [comment]
> Why can't we just compute the max E-Field in the supertype (since the capacitor is the same in both screens) like this?

Sounds excellent to have this factored out to a simple formula.

**Comment by andrewadare** [comment]
Regression!
![image](https://cloud.githubusercontent.com/assets/154163/21055895/8c5ab946-bdf0-11e6-8707-299613cce64e.png)
Bisected to 746186a015f9e0e92bd82581a9f5b9c8bad8b3de. If I do 
```
git diff 7be531545314e302bab34cb489d7dc4b95ce0dff 746186a015f9e0e92bd82581a9f5b9c8bad8b3de
```
it looks like these two changes are the culprits,
```diff
     /**
@@ -128,8 +133,7 @@ define( function( require ) {
      * @returns {Vector2}
      */
     modelToViewDeltaXYZ: function( xDelta, yDelta, zDelta ) {
-      //REVIEW (performance): If it's a bottleneck, use a scratch Vector3 here.
-      return this.modelToViewDelta( new Vector3( xDelta, yDelta, zDelta ) );
+      return this.modelToViewDelta( scratchVector3.setXYZ( xDelta, yDelta, zDelta ) );
     },

...

     viewToModelDeltaXY: function( xDelta, yDelta ) {
-      //REVIEW (performance): If it's a bottleneck, use a scratch Vector2 here.
-      return this.viewToModelDelta( new Vector2( xDelta, yDelta ) );
+      return this.viewToModelDelta( scratchVector2.setXY( xDelta, yDelta ) );
     },
```
because reverting them seems to fix the regression.

**Comment by jonathanolson** [comment]
> it looks like these two changes are the culprits,

Weird, feel free to leave it, and I can investigate later after checking whether performance is a bottleneck.

**Comment by jonathanolson** [comment]
I checked over the view code (in its current status), and I'm really not seeing any systematic problems or large issues. There may be some performance optimizations, but I'd probably take care of those myself after testing with devices and profiling.

@ariel-phet, I'd recommend that @andrewadare applies to the view the same style of REVIEW comment recommentations to the model (visibility and general documentation, and any similar types of cleanup), and adds additional top-level documentation (model.md and implementation.md). Any further code improvements beyond that would probably be faster for me to apply myself.

**Comment by andrewadare** [comment]
IGridSizeStrategy.js contains this header message:
```
/**
 * Interface for all strategies used to determine the size of the grid used to cover a 2D surface with objects.
 *
 * REVIEW: Can we summarize what was tried and why it didn't work?
 * Only one of these strategies is used. The others are kept for historical purposes, so that we know what we tried,
 * why it didn't work, and how we arrived at the final solution.
 *
 * Note: I am not porting any of the other solutions for now.  They are still here in original Java for documentation
 * and we can port them later if desired.
 *
 * @author Chris Malley (cmalley@pixelzoom.com)
 * @author Jesse Greenberg
 * @author Sam Reid
 */
```
The REVIEW recommendation pertains to comments that I removed in 6499a80. I should have also removed this summary. I'm aware of no issues from any of the testing rounds over the arraying of charge symbols using this algorithm.

I'm going to remove this message, but @jonathanolson please let me know if you'd prefer it (and the commented Java code) to be restored back to the file.

**Comment by jonathanolson** [comment]
> I'm going to remove this message

Sounds good.

**Comment by andrewadare** [comment]
> I'd recommend that @andrewadare applies to the view the same style of REVIEW comment recommentations to the model (visibility and general documentation, and any similar types 

I revisited every single view-related file and committed some minor cleanups and visibility doc updates. These files required far less revision than the model.

**Comment by pixelzoom** [comment]
Evaluating status of this as part of #187.  It looks like @andrewadare was the primary developer, and @jonathanolson was part-way through the code review.  And then things stalled out around Dec 2016.  

@jonathanolson Do I have that right? Should I continue with this review? Start a new review issues?...

**Comment by pixelzoom** [comment]
I made a quick pass through the code, added some `REVIEW` tags, and added some missing annotations (mostly `@override`).

**Comment by jonathanolson** [comment]
> It looks like @andrewadare was the primary developer, and @jonathanolson was part-way through the code review. And then things stalled out around Dec 2016.

I had done some review, and @andrewadare handled what was possible before he left. It's potentially on my plate after Proportion Playground.

**Comment by jonathanolson** [comment]
Review complete, only remaining issue is performance (handling in https://github.com/phetsims/capacitor-lab-basics/issues/192).
