### ISSUE TITLE
Voltmeter doesn't update when dragging a switch

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#119]
@jessegreenberg Should be self explanatory:

![clb01](https://cloud.githubusercontent.com/assets/5863899/16052288/c7088412-3220-11e6-93d2-c2551e71cc37.gif)

For phetsims/tasks/issues/615.
Troubleshooting information:
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.22/capacitor-lab-basics_en.html
Version: 1.0.0-dev.22 2016-06-13 17:02:58 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Language: en-US
Window: 1920x1002
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"728956f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"capacitor-lab-basics":{"sha":"bb58674c","branch":"master"},"chipper":{"sha":"1586048b","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"joist":{"sha":"83de2b95","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"00bd89f4","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by jessegreenberg** [comment]
I assumed that the circuit was not connected to a new component until the switch 'pin' was released into a connection spot, so voltage should be undefined until the user releases the mouse from dragging.  Commits above ensure that voltage is undefined as long as the user is dragging.  @arouinfar what do you think? Is this an issue that needs to be addressed?

If the circuit needs to be connected as soon as the pin is over the connection point circle, we could modify the drag handler somehow.

**Comment by arouinfar** [comment]
> I assumed that the circuit was not connected to a new component until the switch 'pin' was released into a connection spot, so voltage should be undefined until the user releases the mouse from dragging. 

@jessegreenberg this seems reasonable to me! I took a look at master, and it looks good.

**Comment by jessegreenberg** [comment]
Great, thanks @arouinfar!  Commits above fix this, closing.
