### ISSUE TITLE
Pointer areas occassionally unresponsive for separation and plate area arrows

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/capacitor-lab-basics#120]
For phetsims/tasks/issues/615

On the iPad 2, for CLB, the arrows for the separation and plate areas are occasionally unresponsive. The arrows are difficult to move using the touchscreen. Also, the separation arrow can be dragged without the arrow turning yellow.

**Comment by andrewadare** [comment]
Would it help for this one to just make the arrows a little larger?

**Comment by jessegreenberg** [comment]
@phet-steele I recall you observing this elsewhere in another sim.  Was this similar to another issue you found in function builder or something?

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/capacitor-lab-basics/issues/120#issuecomment-226025917, yes, that should work.  We can make the touch areas larger too and see if that helps.

**Comment by jessegreenberg** [comment]
Commit above should make the arrows more responsive to touch dragging.

**Comment by arouinfar** [comment]
@jessegreenberg @andrewadare while reviewing #122, I tested the plate arrows out on the iPad 2. The arrows themselves feel great, but I think it would be nice to include the text as an additional drag handle. It seems like Separation text is part of the touch area, but not the Plate Area text.

**Comment by jessegreenberg** [comment]
Thanks for testing @arouinfar.  We can include the text in the pointer areas, similar to your mock up in #122.

**Comment by BryceAG** [comment]
I tested some more on the iPad 2. The arrows are responsive and move both when the arrows are selected and when the text is selected. Although when the text is selected the arrows don't turn yellow, and if you have one arrow selected but drag your finger over the other arrow, the other arrow turns yellow.

**Comment by phet-steele** [comment]
> if you have one arrow selected but drag your finger over the other arrow, the other arrow turns yellow.

This interaction + behaviour is common to all sims, and not an issue. Thank you for noticing @BryceAG. 

> when the text is selected the arrows don't turn yellow

@andrewadare, myself and @arouinfar would welcome this enhancement. Would you be so kind as to make the arrows simultaneously turn yellow when dragging a label?

**Comment by andrewadare** [comment]
@phet-steele @arouinfar Now the plate drag arrows are highlighted whenever the pointer is over the text labels, just as for the arrows themselves.

**Comment by phet-steele** [comment]
Thanks @andrewadare! Looks great.
