### ISSUE TITLE
Voltmeter probe contact locations

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/capacitor-lab-basics#121]
For phetsims/tasks#615
Test device: Bates

Operating System: Windows 7

Browser: Chrome

Problem description: There are certain spots on the lightbulb, where the voltmeter gives a different value from what you would expect.

Screenshots:
Here the red probe is clearly touching the insulating layer between the two conductive portions of the lightbulb, and you would expect ?V,  but the voltmeter treats that location as part of the bottom wire. (it will still read 0V if the capacitor is discharging through the bulb.)
![clb1](https://cloud.githubusercontent.com/assets/11947677/16207643/74322fb6-36eb-11e6-99bc-23679a0f0d78.JPG)
And here, there is a considerable portion toward the bottom of the part that connects to the top wire, where the voltmeter does not recognize a connection and reads ?V instead of 0V.
![clb2](https://cloud.githubusercontent.com/assets/11947677/16207760/26699836-36ec-11e6-9097-e0b46cba5b72.JPG)

Troubleshooting information (do not edit):
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.23/capacitor-lab-basics_en.html
Version: 1.0.0-dev.23 2016-06-13 23:06:49 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"728956f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"capacitor-lab-basics":{"sha":"c25f232c","branch":"master"},"chipper":{"sha":"1586048b","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"joist":{"sha":"83de2b95","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"00bd89f4","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by jessegreenberg** [comment]
Good poinits @brroberts1231.  @arouinfar how smart to the probes need to be with respect to the light bulb base?  Should the black part act like an insulator and the silver part act like a conductor?  Or would you rather the behavior be that anywhere on the bulb base is considered connected to the circuit?

The bulb base will need to be modeled with shapes.  @andrewadare and I will work on this next week.  To generalize the bulb, we can investigate drawing the bulb base with scenery.

**Comment by arouinfar** [comment]
> Or would you rather the behavior be that anywhere on the bulb base is considered connected to the circuit?

Let's go with this option @jessegreenberg @andrewadare.

**Comment by jessegreenberg** [comment]
Sounds good, thanks @arouinfar!

**Comment by andrewadare** [comment]
The following patch fixes the problem:
```
[model]$ git diff wire/LightBulbToSwitchWire.js
diff --git a/js/common/model/wire/LightBulbToSwitchWire.js b/js/common/model/wire/LightBulbToSwitchWire.js
index 2a93cd8..863cd8d 100644
--- a/js/common/model/wire/LightBulbToSwitchWire.js
+++ b/js/common/model/wire/LightBulbToSwitchWire.js
@@ -18,6 +18,9 @@ define( function( require ) {
```
```js
   var CLBConstants = require( 'CAPACITOR_LAB_BASICS/common/CLBConstants' );
   var capacitorLabBasics = require( 'CAPACITOR_LAB_BASICS/capacitorLabBasics' );

+  // constants
+  var TOP_WIRE_X_OFFSET = -5e-4;
+
   /**
    * @param {string} connectionPoint one of 'TOP' or 'BOTTOM'
    * @param {CircuitConfig} config
@@ -34,14 +37,17 @@ define( function( require ) {
```
```js
     // Get x coordinate of the connection point
     var isTop = connectionPoint === CLBConstants.WIRE_CONNECTIONS.LIGHT_BULB_TOP;
-    var connectionPointX = isTop ? lightBulb.getTopConnectionPoint().x : lightBulb.getBottomConnectionPoint().x;
-
+    var connectionPointX =
+      isTop ? lightBulb.getTopConnectionPoint().x + TOP_WIRE_X_OFFSET : lightBulb.getBottomConnectionPoint().x;
     var rightCorner = new Vector2( connectionPointX, horizontalY );

     // add the vertical segment.
     var verticalSegment;
     if ( isTop ) {
-      verticalSegment = WireSegment.ComponentTopWireSegment( lightBulb, rightCorner,
+      verticalSegment = new WireSegment(
+        lightBulb.getTopConnectionPoint().toVector2().plus( new Vector2( TOP_WIRE_X_OFFSET, 0 ) ),
+        rightCorner,
+        // verticalSegment = WireSegment.ComponentTopWireSegment( lightBulb, rightCorner,
         tandem ? tandem.createTandem( 'lightBulbComponentTopWireSegment' ) : null );
     } else {
       verticalSegment = WireSegment.ComponentBottomWireSegment( lightBulb, rightCorner,
```

That's a little hard to read, but all I'm doing there is shifting the vertical wire from the lightbulb to the left slightly, which causes the probe areas on the top and bottom wires to invisibly overlap under the light bulb base.

@jessegreenberg , what do you think about this option? Acceptable, or too much of a hack?

**Comment by andrewadare** [comment]
Here's how it looks after the shift:

<img width="503" alt="clb" src="https://cloud.githubusercontent.com/assets/154163/16427800/555ff356-3d2c-11e6-8758-7f071a1bd291.png">

**Comment by jessegreenberg** [comment]
@andrewadare not too much of a hack, but I am concerned that much of the base shape is still excluded outside of the wire.

I think the most robust solution would be to add a LightBulbShapeCreator under model/shapes with a getBaseShape function, similar to BatteryShapeCreeator.  This would allow us to get the behavior in https://github.com/phetsims/capacitor-lab-basics/issues/121#issuecomment-228456376.

**Comment by jessegreenberg** [comment]
The above commit takes a stab at modeling the shape of the light bulb base.  Next we can check if the probe tip is inside of this shape to determine if it is connected to the circuit.

![outline](https://cloud.githubusercontent.com/assets/6396244/16436803/36fc871c-3d5e-11e6-991b-b4140e59ec57.PNG)

**Comment by jessegreenberg** [comment]
> the behavior be that anywhere on the bulb base is considered connected to the circuit...

Hmmm, if this is the case, is the bulb base connected to the 'top' or 'bottom' of the circuit?  Lets say top for now.

**Comment by jessegreenberg** [comment]
@arouinfar would you mind reviewing to make sure this is fixed?  The behavior is that the entire light bulb base acts as a conductor connected to the *top* wire. Here is the latest:

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.26/capacitor-lab-basics_en.html

**Comment by arouinfar** [comment]
@andrewadare @jessegreenberg something's not right here...

If the voltmeter probes sandwich the socket, there should be a non-zero voltage reading when the bulb drains the capacitor. However, I get a zero reading.
![voltmeter](https://cloud.githubusercontent.com/assets/8419308/16495799/2a8709cc-3eac-11e6-9f73-2d3bfbb2a8fe.gif)

After moving the probes a little further out, the voltmeter correctly reads while the bulb drains the capacitor. However, after moving the switch back to the battery to recharge the capacitor, the voltage reading across the bulb jumps from 0 V to 1.5 V.
![image](https://cloud.githubusercontent.com/assets/8419308/16495887/8b969124-3eac-11e6-82e4-835a31bcd1fc.png)

**Comment by jessegreenberg** [comment]
Thanks @arouinfar, sorry about that!  For the first .gif, I think we can improve the boundaries to detect where the probe tips are.  Not sure why the final image is happening, I will investigate that.

**Comment by andrewadare** [comment]
After f0b911422164dcfcafa189ba21ea0f9716be3e63 and the above commits, I am no longer seeing this problem.

**Comment by BryceAG** [comment]
The bottom third of the node connected to the upper wire still is not recognized as part of the circuit
<img width="450" alt="screen shot 2016-09-29 at 11 41 59 am" src="https://cloud.githubusercontent.com/assets/15327201/18965272/c988ca86-8639-11e6-9b07-3d89d297450c.png">

**Comment by andrewadare** [comment]
I changed the shape of the bulb base test area to just cover the rectangular shape connected to the upper wire.

![image](https://cloud.githubusercontent.com/assets/154163/19250835/b305ca34-8ef9-11e6-8208-23c86881d72d.png)


![image](https://cloud.githubusercontent.com/assets/154163/19250872/d8205b22-8ef9-11e6-98ee-6d7b49a6489d.png)

![image](https://cloud.githubusercontent.com/assets/154163/19250906/f46e6d6e-8ef9-11e6-908a-1109dc117b42.png)

**Comment by phet-steele** [comment]
👍
