### ISSUE TITLE
Increase Touch Areas on Switch End

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#122]
I interviewed this sim on an iPad this afternoon and observed some minor difficulty in moving the switch (using the ball on the end) and changing the plate separation and area.

Let's increase the touch area around the ball end of the switch to be a bit larger (though still remaining within the "click to switch" areas), and also increase the touch area around the arrows and accompanying text.  I've mocked up the new touch areas in green:
![image](https://cloud.githubusercontent.com/assets/8419308/16349776/e72d09a8-3a17-11e6-8464-60aaa615f2bb.png)

The separation arrow touch area is a bit skewed to avoid overlap with the switch touch areas.

**Comment by andrewadare** [comment]
@jessegreenberg and I actually worked on a closely related issue yesterday (see #120). We increased the touch areas for the drag arrows, but not for the ends of the switch. It seems to better, especially on a touchscreen.

We'll work on increasing the areas for the switch ends as well.

**Comment by arouinfar** [comment]
Thanks @andrewadare! Sorry for the partially duplicate issue. I'll rename this one to deal with the switch only since, you have handled the arrows elsewhere.

**Comment by andrewadare** [comment]
@arouinfar The draggable switch rectangle area is now 2.25x larger. Any bigger, and it would extend outside the enclosing triangle. Hopefully this is enough to solve drag problems on tablets.

![clb](https://cloud.githubusercontent.com/assets/154163/16384222/5aa61120-3c45-11e6-8d1e-e25aa99ac300.png)

**Comment by arouinfar** [comment]
Looks great @andrewadare! I'll give it a try on the iPad this afternoon and report back.

**Comment by andrewadare** [comment]
@arouinfar do you want me to push a dev version or are you just going to test on master?

**Comment by arouinfar** [comment]
Can you push a new dev @andrewadare? I didn't think about the fact I'd be testing it out at the booth, where phettest is inaccessible. Thanks!

**Comment by andrewadare** [comment]
@arouinfar no problem... [1.0.0-dev.25](http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.25/capacitor-lab-basics_en.html) is up on spot.

**Comment by arouinfar** [comment]
Looks great! Closing.
