### ISSUE TITLE
bad names for factory functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/capacitor-lab-basics#123]
Noticed while investigating https://github.com/phetsims/phet-core/issues/24#issuecomment-233840820....

I see factory functions that look like these in BarMeterNode:

```
   // factory functions to construct different tpes of MeterNodes
    /**
     * Factory constructor for a CapacitanceMeterNode.
     *
     * @param {CapacitanceMeter} meter
     * @constructor
     */
    CapacitanceBarMeterNode: function( meter ) {
      return new BarMeterNode( meter, CLBConstants.CAPACITANCE_COLOR, CLBConstants.CAPACITANCE_METER_VALUE_EXPONENT, unitsPicoFaradsString, capacitanceString );
    },
    /**
     * Factory constructor for a CapacitanceMeterNode.
     *
     * @param {CapacitanceMeter} meter
     * @constructor
     */
    PlateChargeBarMeterNode: function( meter ) {
      return new PlateChargeBarMeterNode( meter );
    },
    /**
     * Factory constructor for a CapacitanceMeterNode.
     *
     * @param {CapacitanceMeter} meter
     * @constructor
     */
    StoredEnergyBarMeterNode: function( meter ) {
      return new BarMeterNode( meter, CLBConstants.STORED_ENERGY_COLOR, CLBConstants.STORED_ENERGY_METER_VALUE_EXPONENT, unitsPicoJoulesString, storedEnergyString );
    }
```

These functions look like constructors because they being with an uppercase letter. And they are even described incorrectly here as "Factory constructor".   At call sites, they look like this:

```js
var capacitanceMeterNode = BarMeterNode.CapacitanceBarMeterNode( model.capacitanceMeter, '0' );
```

These function should definitely have lowercase names.  And factory functions typically have a "create" prefix.  So recommended to change the above function names to:

```js
createCapacitanceBarMeterNode
createPlateChargeBarMeterNode
createStoredEnergyBarMeterNode
```

**Comment by pixelzoom** [comment]
Also note that all 3 of the factory functions above are documented as:

```* Factory constructor for a CapacitanceMeterNode.` 

This is correct for only 1 of the functions, the other 2 are incorrect.

**Comment by pixelzoom** [comment]
Similar anti-pattern used for `DielectricMaterial.CustomDielectricMaterial`.

**Comment by andrewadare** [comment]
There is extensive use of factory methods (with a similar naming pattern) in this sim. 

Examples:

* `Top` and `Bottom` factory methods in BatteryToSwitchWire, CapacitorToSwitchWire, LightBulbToSwitchWire, and PlateNode
* Many factories in WireSegment.js

Presumably these should be renamed as well.

**Comment by pixelzoom** [comment]
> Presumably these should be renamed as well.

Yes. 
Code Style Guidelines section of [PhET Development Overview](https://docs.google.com/document/d/1odXkliRagq0zuf1_NdOtQ2BrkC9hwlISnPi2y-dKdrk/edit#) indicates that PhET uses [idomatic.js](https://github.com/rwaldron/idiomatic.js#naming), which specifies lowercase for functions, uppercase for constructors (as is typical in most naming conventions).

**Comment by andrewadare** [comment]
The remaining offender, WireSegment.js, appears to need more than renaming. It reads like spaghetti and contains several functions like this:
```js
BatteryTopWireSegment: function( battery, endPoint, tandem ) {
      return new BatteryTopWireSegment( battery, endPoint, tandem );
    },
```
I'm no expert on the factory pattern, but this seems useless to me.

**Comment by andrewadare** [comment]
I now see that these methods exist so that the various method names don't need to be exposed in the global scope.

Prepending `create` (and correcting the jsdoc) will go a long way towards clarifying all this.

**Comment by andrewadare** [comment]
VoltMeterNode and VoltMeterProbeNode should also get a facelift.

**Comment by andrewadare** [comment]
Searching for `return new` (and filtering for noise), I can't find any remaining cases of this problem.

Glad this issue was raised--the whole sim feels like it just got a shave and a shower.

**Comment by jessegreenberg** [comment]
While reviewing this issue, I found one more offending case in DielectricMaterial.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/capacitor-lab-basics/issues/123#issuecomment-235028211 fixed.  Thanks for working on this issue @andrewadare.

**Comment by andrewadare** [comment]
@jessegreenberg Looks great, thanks!
