### ISSUE TITLE
Undefined typeSet error

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#127]
When running capacitor-lab-basics, I observe an error:
>Cannot read property 'plateChargesVisible' of undefined

in PropertySet (line 94).

It looks like options.typeSet is undefined in PropertySet because TBoolean is undefined in CLBModel.  If options.typeSet is dependent on brand, should PropertySet be checking for existence of typeSet first?

**Comment by andrewadare** [comment]
@jessegreenberg apologies for that. Checking for typeSet does allow CL:B to load when the brand is not phet-io:
```
diff --git a/js/PropertySet.js b/js/PropertySet.js
index 422c61c..86ecf27 100644
--- a/js/PropertySet.js
+++ b/js/PropertySet.js
@@ -91,7 +91,7 @@ define( function( require ) {
     Object.getOwnPropertyNames( values ).forEach( function( value ) {
       propertySet.addProperty( value, values[ value ],
         options.tandemSet[ value ],
-        options.typeSet[ value ] );
+        options.typeset && options.typeSet[ value ] );
     } );
   }
```
I encountered the same problem with `options.tandemSet` (one line above) on Friday, but instead of inserting a check for truthiness, @samreid suggested putting an assertion to catch cases where the tandemSet has been passed in as a `null` (because functions like `getVoltage` create a temporary circuit that shouldn't be instrumented).

@samreid is your recommendation to push the patch above, or to handle it in some other way?

**Comment by samreid** [comment]
Can you show the place in CLB where tandemSet: null is being passed in?

**Comment by jessegreenberg** [comment]
Here https://github.com/phetsims/capacitor-lab-basics/blob/master/js/common/model/CLBModel.js#L55 since TBoolean is using ifphetio.

**Comment by andrewadare** [comment]
In this case `typeSet` is undefined, not null, since as @jessegreenberg points out, TBoolean is undefined. Perhaps this comment is redundant since the issue was renamed.

**Comment by andrewadare** [comment]
In this case the tandem is defined and non-null (with id "capacitorLabBasics.capacitanceScreen.model"), and the tandemSet is defined and populated.

**Comment by samreid** [comment]
@andrewadare can we use the pattern we used previously, factoring out the options and only creating them if they will be non-null?

```js
    var propertySetOptions = tandem && TBoolean ? {
      tandemSet: {
        plateChargesVisible: tandem.createTandem( 'plateChargesVisibleProperty' ),
        eFieldVisible: tandem.createTandem( 'eFieldVisibleProperty' ),
        capacitanceMeterVisible: tandem.createTandem( 'capacitanceMeterVisibleProperty' ),
        plateChargeMeterVisible: tandem.createTandem( 'plateChargeMeterVisibleProperty' ),
        storedEnergyMeterVisible: tandem.createTandem( 'storedEnergyMeterVisibleProperty' ),
        barGraphsVisible: tandem.createTandem( 'barGraphsVisibleProperty' ),
        voltmeterVisible: tandem.createTandem( 'voltmeterVisibleProperty' ),
        currentVisible: tandem.createTandem( 'currentVisibleProperty' )
      },
      typeSet: {
        plateChargesVisible: TBoolean,
        eFieldVisible: TBoolean,
        capacitanceMeterVisible: TBoolean,
        plateChargeMeterVisible: TBoolean,
        storedEnergyMeterVisible: TBoolean,
        barGraphsVisible: TBoolean,
        voltmeterVisible: TBoolean,
        currentVisible: TBoolean
      }
    } :{};
```

**Comment by andrewadare** [comment]
Yes, in fact that was the first thing I tried in CLBModel, except that the line with `typeSet` also included a `TBoolean` check. I didn't yet commit that to master, though.

It didn't seem to solve this problem.

**Comment by andrewadare** [comment]
@samreid I suppose you object to the `options.typeSet && options.typeSet[ value ] );` solution mentioned earlier, for the same reason as for `tandemSet` (namely because it may allow problem code through uncaught)?

**Comment by andrewadare** [comment]
This was auto-closed prematurely by including the "fixes" keyword in my commit comment.

@samreid correctly identified that both the tandem instance and the wrapper type need to be checked before passing the PropertySet options.

**Comment by andrewadare** [comment]
@samreid and I discussed that asserts or checks may still be added to the axon code in the future, but we agreed that this is the best solution for now.

**Comment by andrewadare** [comment]
This was resolved months ago--closing.
