### ISSUE TITLE
Voltage reading across bulb matches capacitor, even when disconnected

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#131]
Observed in dev.27 on latest OSX/Chrome.

The voltage reading across the light bulb always matches the voltage across the capacitor, even when the bulb is disconnected.

![vm](https://cloud.githubusercontent.com/assets/8419308/17349010/d90a59dc-58d7-11e6-82fb-7c65bf134911.gif)

**Comment by phet-steele** [comment]
I believe this to be fixed, closing.
