### ISSUE TITLE
screen icon fails validation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/capacitor-lab-basics#135]
After adding icon validation to joist.Screen (see https://github.com/phetsims/joist/issues/352), it was discovered that the home screen icon in CapacitanceScreen fails validation.  At 411.59999999999997x280 it is smaller than the minimum size of Screen.HOME_SCREEN_ICON_SIZE. 

This bit of code in CapacitanceScreen is also suspect (and responsible for the non-integer width):

```js
34    var icon = new Image( capacitorIconImage );
35    icon.scale( 1.4, 1.0 );
```

In general, it's a bad idea to scale up an image file (capacitor-icon.png).  And in this case, the image's aspect ratio is also being changed.  I was going to recommend creating a new PNG file, but I also don't see the related associated asset file in GitHub.

CLBLightBulbScreen looks OK, but you'll need to verify by running with assertions enabled. If there's a problem, you'll get an assertion failure.

**Comment by andrewadare** [comment]
I've been assigned as the maintainer for CL:B, and git is confirming that I'm responsible for the suspect code, so I'll take this one over.

**Comment by andrewadare** [comment]
@pixelzoom There's no asset file because the image is a screenshot from the sim. Is that acceptable? I recall asking someone about that and got no objection, but want to confirm that.

If a screenshot is okay (provided it's the correct size), is there somewhere it needs to be noted that there's no corresponding asset file?

And if screenshots are not okay, I guess I'll either need to create one in code or request one from a designer.

**Comment by andrewadare** [comment]
@arouinfar, is it reasonably quick for you to create a nice screen icon for the capacitance screen (to replace my screenshot hack)? If you do it, we'll have an AI file to keep in assets/.

If not, I'll look into creating one in code, possibly with @jessegreenberg (who has offered to help).

**Comment by arouinfar** [comment]
Can do @andrewadare! I'll get it to you soon.

**Comment by andrewadare** [comment]
@arouinfar Outstanding! You have probably already figured it out, but I was using [this](https://github.com/phetsims/capacitor-lab-basics/blob/eac24d870d7308a3d6f1d30fc136455d0c820ccd/images/capacitor-icon.png). Feel free to design something cooler.

**Comment by pixelzoom** [comment]
> If a screenshot is okay (provided it's the correct size), i

I would think so.

**Comment by arouinfar** [comment]
I've emailed this image and the associated .ai file to @andrewadare. 
![capacitance_screen_icon](https://cloud.githubusercontent.com/assets/8419308/18522376/082d508c-7a6d-11e6-929e-742eb1afe8e1.png)

**Comment by andrewadare** [comment]
@arouinfar looks great, thanks for the quick turnaround.

**Comment by arouinfar** [comment]
Looks good in master, thanks @andrewadare!
