### ISSUE TITLE
vestigial entries in images/license.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/capacitor-lab-basics#137]
Noted while fixing https://github.com/phetsims/capacitor-lab-basics/issues/136....

These entries are for files that don't exist:

```js
"battery_3D_down.png": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Noah Podolefsky"
  },
  "battery_3D_up.png": {
    "text": [
      "Copyright 2002-2015 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Noah Podolefsky"
  },
```

One would hope that the build process would notice this, but it apparently does not.

It would also be a good idea to keep the JSON file alphabetized, so that it's easy to compare to the directory listing in your IDE.

**Comment by pixelzoom** [comment]
JSON file alphabetized, vestigial entries deleted. @andrewadare please review.

**Comment by andrewadare** [comment]
@pixelzoom thanks, I reviewed this and it looks good.
