### ISSUE TITLE
Low precision causes plates to have voltage, but no charge or stored energy

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#138]
For capacitors of increasingly smaller capacitance, there is a larger and larger, what I would call, voltage "dead zone". This zone is where (probably due to precision) plates have voltage across them but have no charge icons or E-field line representations. This is *largely* a non-issue because of the `BATTERY_VOLTAGE_SNAP_TO_ZERO_THRESHOLD`, but could still be confusing when a student is slowly changing the voltage and not seeing any change in the capacitor.
![clb03](https://cloud.githubusercontent.com/assets/5863899/19046495/e287f628-895a-11e6-869f-dea5c8f38bb7.gif)

These numbers reported are (Capacitance/Voltage), where Voltage is the voltage the battery needs to be for the sim to start reporting any Plate Charge or Stored Energy (visible with Plate Charges and Electric Field checked). Note the slider isn't strictly continuous. I could only move it in about ~0.019 V increments.

| --- | Separation 10 mm | Separation 5 mm |
| --- | --- | --- |
| **Plate Area 100 mm<sup>2</sup>** | 0.09 pF / 0.130 V | 0.18 pF / 0.074 V |
| **Plate Area 400 mm<sup>2</sup>** | 0.35 pF / 0.037 V | 0.71 pF / 0.019 V |

@andrewadare @arouinfar if you to take anything away from this issue, have it be this following part. The "0.130 V" value for max separation/min area is particularly alarming. 0.130 V is outside of the `BATTERY_VOLTAGE_SNAP_TO_ZERO_THRESHOLD` range ( <= 0.1 |V|). This means I can create a situation where the capacitor has charge and stored energy, but the sim never shows it (like below). There are also no current arrows when charging the capacitor after a discharge. IMO, the first part of this issue is not a big deal. However this second .gif sure seems to be a problem. Maybe the way to deal with this is to increase the snapping threshold to something like 0.150 V?
![clb02](https://cloud.githubusercontent.com/assets/5863899/19046010/b5f42372-8958-11e6-8723-c1b802425aae.gif)

Seen on macOS 10.12 Safari 10. For phetsims/tasks/issues/706.
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.28/capacitor-lab-basics_en.html
Version: 1.0.0-dev.28 2016-09-26 19:35:15 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50
Language: en-us
Window: 1920x997
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 ATI-1.44.68)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"ae16d65f","branch":"master"},"babel":{"sha":"877eb7e1","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"capacitor-lab-basics":{"sha":"27bec1c3","branch":"master"},"chipper":{"sha":"589bb2f9","branch":"master"},"dot":{"sha":"879674e2","branch":"master"},"joist":{"sha":"96c109c6","branch":"master"},"kite":{"sha":"d6d95bd3","branch":"master"},"phet-core":{"sha":"ee1f025a","branch":"master"},"phetcommon":{"sha":"5a539ab9","branch":"master"},"query-string-machine":{"sha":"fe8addf3","branch":"master"},"scenery":{"sha":"ff21c549","branch":"master"},"scenery-phet":{"sha":"8c6b1787","branch":"master"},"sherpa":{"sha":"affd30ea","branch":"master"},"sun":{"sha":"49ee61f8","branch":"master"},"tandem":{"sha":"fa89ce89","branch":"master"},"twixt":{"sha":"53b54ee2","branch":"master"}}

**Comment by arouinfar** [comment]
>IMO, the first part of this issue is not a big deal. 

Agreed, since the user is actively moving the slider knob through a small range in the first .gif.

>However this second .gif sure seems to be a problem. Maybe the way to deal with this is to increase the snapping threshold to something like 0.150 V?

This seems like a reasonable solution @phet-steele. This would give the battery an active range of 0.150V-1.5V, which is a factor of 10 difference. I think a range of 10x is more than sufficient.

@andrewadare can you please change `BATTERY_VOLTAGE_SNAP_TO_ZERO_THRESHOLD` to 0.150 volts?

**Comment by phet-steele** [comment]
Easy enough! Thank you @andrewadare and @arouinfar!
