### ISSUE TITLE
Voltmeter reads zero at corner

### ISSUE THREAD

**Issue by BryceAG** [phetsims/capacitor-lab-basics#139]
Test device:
Bates

Operating System:
Win 7

Browser:
Chrome, Firefox, IE, Edge

Problem description:
The voltmeter will read "0 V" instead of "? V" when connected to the top left corner of the screen and part of the circuit connected to the light bulb. It correctly shows "? V" when connected to the battery, or just the capacitor when not hooked up to the light bulb.

Steps to reproduce:
Put one end of the voltmeter on the light bulb section of the circuit, and the other end in the top left corner

Severity:

Screenshots:
![capacitor lab- basics screenshot 1](https://cloud.githubusercontent.com/assets/15327201/19054671/a4892266-897d-11e6-8243-d2b2b6125064.png)

Troubleshooting information (do not edit):
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.28/capacitor-lab-basics_en.html
Version: 1.0.0-dev.28 2016-09-26 19:35:15 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1366x613
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"ae16d65f","branch":"master"},"babel":{"sha":"877eb7e1","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"capacitor-lab-basics":{"sha":"27bec1c3","branch":"master"},"chipper":{"sha":"589bb2f9","branch":"master"},"dot":{"sha":"879674e2","branch":"master"},"joist":{"sha":"96c109c6","branch":"master"},"kite":{"sha":"d6d95bd3","branch":"master"},"phet-core":{"sha":"ee1f025a","branch":"master"},"phetcommon":{"sha":"5a539ab9","branch":"master"},"query-string-machine":{"sha":"fe8addf3","branch":"master"},"scenery":{"sha":"ff21c549","branch":"master"},"scenery-phet":{"sha":"8c6b1787","branch":"master"},"sherpa":{"sha":"affd30ea","branch":"master"},"sun":{"sha":"49ee61f8","branch":"master"},"tandem":{"sha":"fa89ce89","branch":"master"},"twixt":{"sha":"53b54ee2","branch":"master"}}

related to phetsims/tasks#706

**Comment by phet-steele** [comment]
@andrewadare maybe something that helps, but this is very similar to phetsims/ph-scale/issues/65.

**Comment by andrewadare** [comment]
Cannot reproduce on Chrome, Firefox, or Safari on OS X. Will need to borrow a Windows computer in order to fix.

**Comment by phet-steele** [comment]
@andrewadare I can repro on macOS 10.12 Chrome.

**Comment by andrewadare** [comment]
![image](https://cloud.githubusercontent.com/assets/154163/19280354/b6b6c7a6-8fa2-11e6-94a6-34cc67ab7423.png)

**Comment by phet-steele** [comment]
I cannot repro in requirejs, @andrewadare have you tried in a built version?

**Comment by andrewadare** [comment]
@phet-steele I cannot reproduce this in requirejs or built versions.

Does your OS X test computer have a non-retina display?

**Comment by phet-steele** [comment]
@andrewadare I cannot reproduce on my computer anymore in dev.29. I went ahead and checked the original reported device & browsers and also could not reproduce. What could have possibly changed? I'm inclined to defer this now.

**Comment by andrewadare** [comment]
@phet-steele since nobody can reproduce this, let's close for now and re-open if the bug resurfaces.
