### ISSUE TITLE
Bar graph panel text alignment is off

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#142]
Both these issues required no set-up, they work from sim start:

When first selecting the checkboxes, there is no "0.00 [unit]" text:
dev.29:
<img width="785" alt="screen shot 2016-10-13 at 10 00 58 am" src="https://cloud.githubusercontent.com/assets/5863899/19356735/0c1d32b8-912c-11e6-94e8-28b3022b5163.png">

dev.28:
<img width="769" alt="screen shot 2016-10-13 at 10 01 10 am" src="https://cloud.githubusercontent.com/assets/5863899/19356743/12453faa-912c-11e6-8250-3730c3f186cc.png">

Once you start charging the capacitor, there is a loss of alignment in 1.0.0-dev.29:
<img width="776" alt="screen shot 2016-10-13 at 9 51 54 am" src="https://cloud.githubusercontent.com/assets/5863899/19356347/c36c4b22-912a-11e6-8112-ec79944b047d.png">

Seen on macOS 10.12 Chrome. For phetsims/tasks/issues/711.
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.29/capacitor-lab-basics_en.html
Version: 1.0.0-dev.29 2016-10-12 20:22:21 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"f2dce2c0","branch":"master"},"babel":{"sha":"52d56600","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"capacitor-lab-basics":{"sha":"27629d25","branch":"master"},"chipper":{"sha":"eb47dfd7","branch":"master"},"dot":{"sha":"da3b5dd4","branch":"master"},"joist":{"sha":"fec74887","branch":"master"},"kite":{"sha":"d506825f","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"68bd02ca","branch":"master"},"scenery":{"sha":"28f40b23","branch":"master"},"scenery-phet":{"sha":"d471774a","branch":"master"},"sherpa":{"sha":"cbdbe169","branch":"master"},"sun":{"sha":"315997cc","branch":"master"},"tandem":{"sha":"01cae1dc","branch":"master"},"twixt":{"sha":"53b54ee2","branch":"master"}}

**Comment by andrewadare** [comment]
`git bisect` is pointing to 755fdb7ce55143ce3e2a518277af03be003043fd as the culprit.

**Comment by brroberts1231** [comment]
Reproduced on Win 7, all browsers. 
The text also gets covered up by the bars.
![clb3](https://cloud.githubusercontent.com/assets/11947677/19359293/cefe576c-9136-11e6-987a-782a20d2f4e2.JPG)

**Comment by andrewadare** [comment]
This should be fixed now on master.

**Comment by phet-steele** [comment]
Working well, thank you @andrewadare.
