### ISSUE TITLE
Mouse area for yellow highlight hint

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#144]
It was suggested to reduce the connection points' mouse area to just be a small dilation around the dashed circles (instead of the entire touch area wedge). This would effectively prevent the yellow highlight cue from appearing until a user's mouse is much closer to a connection point. @andrewadare, the proposed mouse area from @arouinfar was a circle with a diameter equal to the length of a side of the solder ball's mouse area:
<img width="103" alt="screen shot 2016-10-17 at 1 54 09 pm" src="https://cloud.githubusercontent.com/assets/5863899/19453156/42a5ecb0-9471-11e6-9955-d8133063643a.png">

This would not change the current touch behaviour; users still have the large wedge to touch to make a connection point. This would also not change the current touch/mouse area of the switch itself. For phetsims/tasks/issues/711.

**Comment by arouinfar** [comment]
> @arouinfar was a circle with a diameter equal to the length of a side of the solder ball's mouse area

@andrewadare it could also be a square like the screenshot. Your call.

**Comment by phet-steele** [comment]
Thank you @andrewadare, this is working well.
