### ISSUE TITLE
Voltmeter reading is inconsistent when the circuit is in transit

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#146]
@andrewadare I feel there was some logic applied to the second screen, but not the first. On the second screen, the voltmeter will correctly measure the voltage across the battery when the switch is in transit:

![clb05](https://cloud.githubusercontent.com/assets/5863899/19494053/94998d50-953a-11e6-97c4-2f2520fa6588.gif)

However, the first screen will incorrectly report an unknown voltage in the same scenario. Only once a connection is made will the voltmeter report voltage:

![clb06](https://cloud.githubusercontent.com/assets/5863899/19494063/9a5db22a-953a-11e6-812a-aa8f48c844ab.gif)

@andrewadare please make the first screen behave the same as the second screen.

Seen on macOS 10.12 Chrome. For phetsims/tasks#711.
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.29/capacitor-lab-basics_en.html
Version: 1.0.0-dev.29 2016-10-12 20:22:21 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Language: en-US
Window: 1920x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"f2dce2c0","branch":"master"},"babel":{"sha":"52d56600","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"capacitor-lab-basics":{"sha":"27629d25","branch":"master"},"chipper":{"sha":"eb47dfd7","branch":"master"},"dot":{"sha":"da3b5dd4","branch":"master"},"joist":{"sha":"fec74887","branch":"master"},"kite":{"sha":"d506825f","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"68bd02ca","branch":"master"},"scenery":{"sha":"28f40b23","branch":"master"},"scenery-phet":{"sha":"d471774a","branch":"master"},"sherpa":{"sha":"cbdbe169","branch":"master"},"sun":{"sha":"315997cc","branch":"master"},"tandem":{"sha":"01cae1dc","branch":"master"},"twixt":{"sha":"53b54ee2","branch":"master"}}

**Comment by andrewadare** [comment]
@phet-steele Good catch. LightBulbCircuit.getVoltageAt() handles the voltage readout on switch drag for the second screen, but the equivalent method for the first screen (in ParallelCircuit) is missing this case.

**Comment by phet-steele** [comment]
@andrewadare The above problem is fixed, with the unintended consequence that battery voltage is shown in transit even when the probes are not over the battery circuit:

1. Place the probes over the plates and charge the plates to 1.5 V
2. Disconnect the plates
3. Change the battery voltage to something other than 1.5 V
4. Drag the switch, the voltmeter will then display the battery voltage

![clb08](https://cloud.githubusercontent.com/assets/5863899/20073879/46580d4a-a4eb-11e6-8456-2e95f2716d39.gif)

**Comment by andrewadare** [comment]
@phet-steele I fixed some missing cases in ParallelCircuit and the voltmeter readout behavior looks correct now on my end.

**Comment by phet-steele** [comment]
@andrewadare I checked master. I agree, the behaviour also looks correct.
