### ISSUE TITLE
branch: no-touchsnag

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#147]
Branch to test removing touchsnag from circuit switch drag handler.  See the following dev version:

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.1.0-dev.30/capacitor-lab-basics_en.html

**Comment by jessegreenberg** [comment]
Potentially related issue:
https://github.com/phetsims/capacitor-lab-basics/issues/130

**Comment by andrewadare** [comment]
@jessegreenberg Thanks for doing this. Since the change is now in master, feel free to close and prune at your discretion.

**Comment by jessegreenberg** [comment]
Thanks @andrewadare, branch pruned.  Closing.
