### ISSUE TITLE
Solder ball does not appear in a screenshot (from the PhET menu)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#148]
![capacitor lab- basics screenshot 2](https://cloud.githubusercontent.com/assets/5863899/19700785/e5c3cfda-9ab5-11e6-991f-c69517c25004.png)

Seen on macOS 10.12.1 Chrome. For phetsims/tasks/issues/716.

URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.32/capacitor-lab-basics_en.html?profiler
Version: 1.0.0-dev.32 2016-10-24 21:08:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Language: en-US
Window: 1526x1001
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"845be6b5","branch":"master"},"axon":{"sha":"bd3a64f4","branch":"master"},"babel":{"sha":"a106d6f8","branch":"master"},"brand":{"sha":"880a18de","branch":"master"},"capacitor-lab-basics":{"sha":"e7826d19","branch":"master"},"chipper":{"sha":"c1b633ff","branch":"master"},"dot":{"sha":"da3b5dd4","branch":"master"},"joist":{"sha":"e7361bf3","branch":"master"},"kite":{"sha":"d506825f","branch":"master"},"phet-core":{"sha":"4222a05a","branch":"master"},"phetcommon":{"sha":"8df1bf7d","branch":"master"},"query-string-machine":{"sha":"438cfac1","branch":"master"},"scenery":{"sha":"9611f89d","branch":"master"},"scenery-phet":{"sha":"7aa025e8","branch":"master"},"sherpa":{"sha":"83940ff7","branch":"master"},"sun":{"sha":"ad23b8e2","branch":"master"},"tandem":{"sha":"01cae1dc","branch":"master"},"twixt":{"sha":"53b54ee2","branch":"master"}}

**Comment by andrewadare** [comment]
@jonathanolson suggested trying the screenshot with `?rootRenderer=canvas`. With that parameter set, the problem is not observed.

He mentioned on Skype that this has appeared before when CanvasNode improperly clears content.

**Comment by andrewadare** [comment]
EFieldNode and PlateChargeNode are using CanvasNode, but ShadedSphereNode (the component of interest) is not.

**Comment by andrewadare** [comment]
@jonathanolson and I spent some time troubleshooting this. The bug is not reproducible on FF or Safari.

We were able to reproduce the bug initially, but after taking a few more screenshots, the bug mysteriously disappeared. I updated Chrome to this on my OSX laptop:

Version 54.0.2840.87 (64-bit)

@jonathanolson just tried on a separate laptop with a fresh Chrome update, and the bug didn't appear, even on the first try.

@phet-steele can you update Chrome and try again?

**Comment by phet-steele** [comment]
@andrewadare, it's working wondrously now! I even checked on dev.32 where the problem was seen originally. So, close I guess?

**Comment by andrewadare** [comment]
Indeed. Looks like this Chrome-specific problem fixed itself.

**Comment by phet-steele** [comment]
@andrewadare, this is back in 1.0.0-dev.37! I can see where maybe we thought this was resolved, but there is a chance it never was. The key is this:

Move your mouse over a solder ball to highlight it first, THEN take a screenshot.

Solder balls that have not been "highlighted" look completely normal in the screenshot. Something about the highlight, followed by the return of the solder ball when the mouse moves away, is causing this.

Info: Using Chrome 55.0.2883.95 (64-bit) on macOS Sierra 10.12.2.

**Comment by andrewadare** [comment]
@ariel-phet, I assume you'll want @jonathanolson to have a look at this one.

**Comment by jonathanolson** [comment]
Yup, able to reproduce on Firefox and IE now. Investigating.

**Comment by jonathanolson** [comment]
Looks like the fill of the dashed circle outline was being set to ```'none'``` (the string) instead of null. Scenery treats strings as being filled, so when Canvas tries to render it, it keeps the old fill.

In this case, the old fill looked like the background color of the sim, so it erased the content behind (erasing our poor properly-filled switch ball).

I'll be adding assertions to Scenery to prevent this sort of shenanigan.

**Comment by jonathanolson** [comment]
Should be fixed, @phet-steele can you verify?

Also MANY MANY thanks for noticing that the mouse-over was the trigger!

**Comment by phet-steele** [comment]
It's fixed on phettest, let's hope this doesn't come up again! And don't mention it, @jonathanolson.
