### ISSUE TITLE
Battery slider labels hidden in specular highlight

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#15]
Now that the battery highlight has been corrected and the slider has been rotated as requested in #12, the slider tick labels are hidden in the specular highlight.

![battery_highlight_issue](https://cloud.githubusercontent.com/assets/6396244/9722347/c6aba5de-5568-11e5-87c2-6e4dbe0f9e31.PNG)

@arouinfar, how would you like to handle this?

**Comment by jessegreenberg** [comment]
Even without the specular lighting, I think the white label is difficult to see on the gold section of the battery image.

**Comment by pixelzoom** [comment]
The bottom 2 ticks look OK to me. How about changing the color of the top tick (+1.5V) to black?

**Comment by pixelzoom** [comment]
Other ideas:

(1) Make the specular highlight less bright, by using lighter versions of the battery colors instead of white. 

(2) Move the slider to the left side of the battery, and move the ticks to the right side of the slider (so that they don't overlap the specular highlight).

**Comment by jessegreenberg** [comment]
I thought that it might look strange to have tick marks with different colors, but now that I see it I think it looks pretty good!
![top_mark_black](https://cloud.githubusercontent.com/assets/6396244/9739237/187e80b8-560c-11e5-94ba-c540f887ffc1.PNG)
@arouinfar, what do you think of this as a solution?

**Comment by arouinfar** [comment]
I think it looks great @jessegreenberg! Thanks for your suggestions @pixelzoom.

Let's leave the highlight alone for now, and if need be I can implement @pixelzoom's other suggestion.
> (1) Make the specular highlight less bright, by using lighter versions of the battery colors instead of white.

**Comment by jessegreenberg** [comment]
Great, done and closing.
