### ISSUE TITLE
Why can plate charge go negative?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/capacitor-lab-basics#150]
@arouinfar why is plate charge allowed to go negative? Usually when we teach this subject we talk about "Q" as the charge on one of the plates but in an absolute value sense. Was this changed at some point, I don't recall discussing allowing plate charge to go negative in the bar graph.

**Comment by andrewadare** [comment]
This is a wrinkle with plotting charge on a log scale for the lab book wrapper. The symmetry is broken in an arbitrary way, since the domain for log arguments is positive-only.

**Comment by arouinfar** [comment]
@ariel-phet the graph shows the charge on the top plate, which can be positive or negative, depending on the battery polarity.  We never had a conversation about this behavior, as it matches the Java version.  The bar graph label doesn't explicitly say "Top Plate Charge" but we've used color-coding  to tie the bar color to the charge on the top plate. I haven't observed any student difficulties with interpreting the graph, and about half of the interviewees had never seen a capacitor before.

However, from @andrewadare's comment it sounds like allowing a the plate charge to go [-Q, Q] causes a discontinuity in the plot. I see two solutions
* Continue to show the +/- values for Q in the bar graph, but plot abs(Q) in the wrapper
* Show only positive values for Q in the bar graph, and the plot in the wrapper will match

I don't have a strong preference. Perhaps @kathy-phet recalls more about the motivation to show both +/-Q.

**Comment by ariel-phet** [comment]
Well, when we teach this in intro EM and use the equation Q=CV all values are considered positive, so V is really the absolute value of the voltage difference, C is positive definite and Q is the absolute value of charged stored on one plate.

Although I agree that students would not be confused by the intent of the sim, I have seen students confused by such minus sign questions when doing calculations.

**Comment by arouinfar** [comment]
Looking at the Java version, the graph says "Plate Charge (top)" so we've dropped the "top" in the HTML5 version. I think this is an unintentional change, as I couldn't find any discussion about it in the meeting notes.

I'd be fine with showing abs(Q) in the bar graph, but I think we should still allow the battery to supply [-1.5 V, 1.5 V].

**Comment by kathy-phet** [comment]
I kind like the switch of the type of charge from positive to negative with the color coding. I think it is kind of natural for you to see the connection to the top. 

I see the issue with the absolute value being important, but I don't see that we are necessarily helping resolve this difficulty if we do the absolute value for them? It seems like this is a place where the instructional facilitation/activity needs to do the work and its is actually helpful for the sim to enable that by showing Q as negative for negative voltage.

**Comment by kathy-phet** [comment]
I also think for the level of this basics sim ... that even understanding that charge can be negative is a learning goal.

**Comment by ariel-phet** [comment]
@arouinfar agreed, we should definitely allow the battery to be flipped.

@kathy-phet my problem is that is just never how we discuss charge stored in a capacitor. Perhaps we should change the wording to "stored charge". When we say this sim is "basics" remember we envision that for college level intro physics, not for middle school I would (and have) used this sim for helping to teach physics 2020 here. 

I see this sim as most useful for understanding -
- that capacitance is related to the ability to store charge
- the factors that affect capacitance
- relating to Q=CV on a conceptual level as well as U=1/2CV^2 and such

**Comment by kathy-phet** [comment]
I am concerned "stored charge" doesn't help them realize its just the charge on one plate. 
Let's discuss Thursday at design? I don't have time to continue discussing today.

**Comment by arouinfar** [comment]
I'll tag this for design meeting @kathy-phet.

**Comment by arouinfar** [comment]
I generally agree with @ariel-phet, but I do see how "stored charge" could be problematic. We'll discuss more during design meeting.

I'd also think that the Light Bulb screen can get at qualitative learning goals related to a discharging RC-circuit.
* Relate the size of the halo to the voltage across the capacitor (or bulb)
* Relate the draining rate to the capacitance 
* Observe that the brightness of the bulb decays non-linearly

Given the appropriate wrapper, these learning goals could be more quantitative.

**Comment by ariel-phet** [comment]
@arouinfar yes, totally agreed on the light bulb scene

**Comment by arouinfar** [comment]
Discussed during the 11/3/16 design meeting.

* In general, most of the team likes the connection between the the charges on the top plate and the color of the bar graph.
* Using "stored charge" terminology may unintentionally cue students to think that the plate charge is a sum of the charges on both plates.
* In Java, the plate charge bar graph shows a red/blue bar, but the value beneath it is always positive. @oliver-phet confirmed that he has not received any emails from concerned teachers.

We've decided to make the behavior match the Java version, and I will make a note in the Teacher Tips.

@andrewadare please display abs(Q) next to the Plate Charge bar graph.

**Comment by ariel-phet** [comment]
Plate charge now now longer goes negative in the readout. This can be closed.
