### ISSUE TITLE
Should current arrows reflect magnitude?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#152]
Engin commented that
> The arrows representing current disappear once there is no current anymore, but they do not change size. However, in the case of discharging (light bulb), the charge distribution is changing. 

The current arrows were only meant show the direction of the current in the original Java sim, and we ported them as-is. However, we explicitly show a draining RC-circuit in the Basics version. When draining the capacitor, the magnitude of the current exponentially decays. Should we model this in the simulation? We could scale the current arrow with the voltage as the capacitor drains.

@ariel-phet do you think it's worth pursuing this (or at least discussing further) or do you think it's sufficient to leave it as a note in the Teacher Tips?

**Comment by ariel-phet** [comment]
Lets discuss with @andrewadare at design meeting, it is possible it is a fairly straightforward tweak since that information for the current is in a sense I believe already in the model. It might be a helpful further cue to make sense of what is going on.

**Comment by arouinfar** [comment]
Discussed in 11/3/16 design meeting. 

* Because the current decays exponentially, the arrow would be pretty tiny (or have a very low opacity) for most of the time.
* The exponential decay of the current is a more advanced topic and could be addressed in the full version of Capacitor Lab, which could include the current meter.
* Change current checkbox to "Current Direction" to make things clearer.


@andrewadare please change the current checkbox to read "Current Direction".
