### ISSUE TITLE
Dev version with changes from 11/3 design meeting

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#155]
@arouinfar @ariel-phet @kathy-phet 

I believe I've addressed the items in #150, #151, #152, and #153. I put up 1.0.0-dev.35 for your perusal:

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.35/capacitor-lab-basics_en.html

Please let me know if any of these changes are misaligned with what you were envisioning, or if you find any problems.

**Comment by kathy-phet** [comment]
Looks great to me!

**Comment by ariel-phet** [comment]
I think everything is looking good @andrewadare 

My only tweak is I think we need to go with "Plate Charge (top)" like in the Java full version or else I think it is a little odd. That approach seems to have worked well in the past and shouldn't cause too much of an i18n issue.

What do you think @arouinfar?

What do you

**Comment by arouinfar** [comment]
Looks great @andrewadare! 

Now that we've removed the +/- on the plate charge, I agree with @ariel-phet that we should change the label to "Plate Charge (top)".

However, we'll need to shift some things around in the panel to accommodate the longer string. I like the symmetry of having the panel sized to the top wire, so I don't want to make the panel any larger. Instead, I think we should reduce the size of the bars a little bit to maintain the padding between the labels and the values.

The base of the bars should be shifted to the right a bit, probably near the thick black line I've added. @andrewadare I don't want to specify a specific pixel amount. Please do what you think looks good.
![image](https://cloud.githubusercontent.com/assets/8419308/20068120/d7dea33a-a4d4-11e6-80b8-46a3a094993d.png)

**Comment by ariel-phet** [comment]
@arouinfar I also thing "(top)" could potentially be in a smaller font than "Plate Charge" 

As long as that does not look odd, it would save a bit of space, and I feel like it should be de-emphasized a bit. Might be worth trying.

**Comment by arouinfar** [comment]
@ariel-phet we could try that, but I still think we'll need to shorten the bars regardless.

**Comment by ariel-phet** [comment]
@arouinfar agreed, but might help feel more balanced.

I keep trying to think if there is a shorter way to say Plate Charge (top) but have yet to have any better idea.

**Comment by arouinfar** [comment]
@ariel-phet The only thing I can think of would be "Plate Q (top)" but that's far more problematic, so it's probably best to stick with "Plate Charge (top)".

@andrewadare try adding "(top)" in a smaller font. The bars will likely still need be be shortened a bit, but not as much as in my previous screenshot. To be clear, the max bar size would still correspond to 2.7E-12 [units], but the max bar length would be a bit shorter.

**Comment by andrewadare** [comment]
This was annoyingly tricky to get right, considering the stringTest=double test, the off-range behavior for the max bar values, the font sizing, and the spacing between the title and value strings for each bar. There is no perfect solution that covers all the cases, but I tried to strike a decent balance.

![image](https://cloud.githubusercontent.com/assets/154163/20080910/8f867d08-a509-11e6-9612-ea56491889d9.png)

![image](https://cloud.githubusercontent.com/assets/154163/20080865/58eb741a-a509-11e6-97fd-bae1b4d3d3b6.png)

**Comment by andrewadare** [comment]
After a bit more obsessing, I added more breathing room, so the title string font is a bit smaller.

![image](https://cloud.githubusercontent.com/assets/154163/20081035/43eaf030-a50a-11e6-90ea-24c06055aae5.png)

**Comment by kathy-phet** [comment]
How important is it to keep the right alignment?

**Comment by andrewadare** [comment]
If you mean the off-limit arrows, they now stay in-bounds for the worst-case scenario with the double-string test:

![image](https://cloud.githubusercontent.com/assets/154163/20081098/9f039350-a50a-11e6-8cbc-7a44a3664c10.png)

**Comment by andrewadare** [comment]
Oh, @kathy-phet did you mean matching the right side of the panel to the vertical wire on the right?

We could try extending it, but there are potential consequences with internationalization like this:

![image](https://cloud.githubusercontent.com/assets/154163/20081210/485e9a1c-a50b-11e6-9066-5154dfcc40af.png)

**Comment by andrewadare** [comment]
I'm pretty happy with the latest solution. I think all the important constraints have been satisfied.

**Comment by arouinfar** [comment]
@andrewadare there seems to be quite a lot of negative space to the right of the bar graphs  https://github.com/phetsims/capacitor-lab-basics/issues/155#issuecomment-259001638 I think it would be better to shift the bar graphs + values further to the right like so:
<img width="810" alt="screen shot 2016-11-07 at 4 49 04 pm" src="https://cloud.githubusercontent.com/assets/8419308/20081017/2b0c0f2c-a50a-11e6-8736-c5e0479f353b.png">

As far as i18n goes, the bar graphs panel can expand a bit before strings are scaled down. It doesn't need to stay the same width as the top segment of the circuit. The design is optimized so that this is feasible for en, but it's not necessary that the panel maintain that alignment for other locales.

**Comment by andrewadare** [comment]
@arouinfar If the panel is allowed to expand, that makes things easier. I made some changes in 		3814a3b that allow this. I restored the bars to their original length (255px). Since built versions don't support query parameters like `stringTest=double` or `stringTest=long`, is it possible for you to have a look at the current layout on master?

**Comment by andrewadare** [comment]
After discussion with @ariel-phet, we tried out simply moving the whole panel to the left and extending its width, as well as changing from "Plate Charge (top)" to "Top Plate Charge".

**Comment by arouinfar** [comment]
@andrewadare have you pushed these changes to master?Things look a bit off when I pull master. The string still reads "Plate Charge (top)" and the panel resizes itself for no explicable reason. 

<img width="594" alt="screen shot 2016-11-08 at 11 31 03 am" src="https://cloud.githubusercontent.com/assets/8419308/20111801/de80c4d4-a5a6-11e6-8332-d252551d1d02.png">

**Comment by andrewadare** [comment]
@arouinfar not yet, there were a few more layout changes requested that I'm still working on.

**Comment by arouinfar** [comment]
Got it @andrewadare. Please let me know when it's ready for me to review on master.

I think "Top Plate Charge" is a good idea.

Also, I don't think we should dynamically resize the bar graph panel. That is, the width of the panel should be a constant for a given locale. For the en locale, restrict the panel width to match the top wire, as there seems to be plenty of room for the strings if the bars are slightly shortened. For i18n, allow the panel to expand to accommodate large strings. The max bar length would be unchanged. The panel expansion is purely to accommodate longer strings.

**Comment by andrewadare** [comment]
@arouinfar - since @ariel-phet suggested to make the panel wider, the dynamic resizing no longer seems necessary at all, and it was causing me more layout troubles than it's worth. Can you have a look at master now and see if it's acceptable? I'll be AFK for a bit to go vote.

**Comment by arouinfar** [comment]
In general, I like the changes @andrewadare. Centering the expanded panel over the top wire is a good compromise. However, I'm not quite sure why there is so much negative space to the right of the bars. I think it looks a bit odd to go off-scale with so much room left.

<img width="651" alt="screen shot 2016-11-08 at 11 56 16 am" src="https://cloud.githubusercontent.com/assets/8419308/20112681/93b5c6ee-a5aa-11e6-897a-c4578b3f258b.png">

**Comment by andrewadare** [comment]
@ariel-phet requested that the panel not expand with stringTest=double.

**Comment by ariel-phet** [comment]
Ah - @andrewadare I think I may have miscommunicated a bit.

- Yes, the panel should not expand, it should have a fixed width as you said
- However, I think @arouinfar is correct that there should not be so much negative space on the right hand side
- So it seems the bars could be made a bit longer in the bar graph, and the maxWidth for the check box labels can be made just a bit larger than the current "Top Plate Charge" width. It is fine if with ?stringTest=double the font of the labels scales down. Our requirement for longer strings is that layout is handled "gracefully" but we are OK if some fonts shrink and others do not. It is not the most aesthetically pleasing always, but it does the job, and seems appropriate in this case.

**Comment by andrewadare** [comment]
I identified the main reason why this was so troublesome. The bar origin was positioned relative to the right side of the title text for each bar. When I made the strings longer with stringTest=double, it was pushing the bars over. I fixed that and things seem better now.

![image](https://cloud.githubusercontent.com/assets/154163/20118969/e3a64f02-a5c3-11e6-972d-39a7168d58d1.png)

![image](https://cloud.githubusercontent.com/assets/154163/20118930/c6c26a56-a5c3-11e6-9e8d-a29809d83f6e.png)

![image](https://cloud.githubusercontent.com/assets/154163/20118694/b39a5a2a-a5c2-11e6-9d9a-76094bb48414.png)
