### ISSUE TITLE
Some PhET Menu buttons aren't functioning

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#159]
Neither "Report a Problem...", "PhET Website...", nor "Screenshot" from the PhET menu are directing me anywhere. I see no errors in the console. Other sims are behaving just fine.

Seen on Win 10 Chrome, for phetsims/tasks/issues/729.

**Comment by andrewadare** [comment]
I'm not able to reproduce this on OSX 10.11 Chrome, and don't have Windows to test on. Not too much I can do for this issue at the moment.

**Comment by phet-steele** [comment]
Seems fixed in 1.0.0-dev.37. Tentatively closing. For the record, I could reproduce in dev.36 on macOS 10.12.2 Chrome.
