### ISSUE TITLE
Bar graph panel is messy if a value has 4 digits

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#160]
Adding a 4th digit to the value of Stored Energy moves the string right while causing some overlap. 
Assigning to @arouinfar for comments on what direction to take.

![clb01](https://cloud.githubusercontent.com/assets/5863899/20682067/a81283e8-b563-11e6-9df8-3863a4f7403e.gif)

Seen on Win 10 Chrome, for phetsims/tasks#729.

No troubleshooting info (see #159).

**Comment by arouinfar** [comment]
Thanks @phet-steele. The string should instead expand to the left, so that the unit label does not move.

**Comment by arouinfar** [comment]
Here's an example @andrewadare. The fourth digit would get added to the left of the number so that there's no apparent shift in the value.
![screen shot 2016-11-28 at 12 50 40 pm](https://cloud.githubusercontent.com/assets/8419308/20683462/545ad15a-b569-11e6-8283-7a689a370bf8.png)

**Comment by ariel-phet** [comment]
@arouinfar assigning to you to take a look at. 

If all looks good, feel free to close, if further work is needed, please describe and assign to JO

**Comment by arouinfar** [comment]
@ariel-phet I'm not able to pull capacitor-lab-basics from master (other repos seem fine), so I think it's temporarily broken. I'll check again later.

**Comment by arouinfar** [comment]
Left-aligning the values looks reasonable to me. Closing.
