### ISSUE TITLE
Voltmeter cursor

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#161]
The "hand" (cursor: 'pointer') doesn't seem to appear until a drag is started.

Presumably if the user hovers a mouse over the voltmeter, it should change the cursor.

**Comment by jonathanolson** [comment]
See https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by andrewadare** [comment]
Both the voltmeter and its icon in the panel now have cursor = 'pointer'.

**Comment by jonathanolson** [comment]
Looks good, thanks.
