### ISSUE TITLE
Type documentation for properties

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#165]
Properties declared on objects should have visibility modifiers, preferably with type information and sometimes with documentation.

For example, in AbstractCircuit's constructor, for currentAmplitudeProperty:
```js
// @public {Property.<Number>} - In Amperes
```
or see ```this.wires``` declaration in the same file.

For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by andrewadare** [comment]
I've done a full pass through every file (both model and view) and added the docs. @jonathanolson please close if this looks satisfactory.
