### ISSUE TITLE
model.md and implementation.md documentation

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#166]
Should exist at capacitor-lab-basics/doc/, as noted in the code review guidelines:

>       doc/
>          model.md
>          implementation-notes.md

> - Does model.md adequately describe the model, in terms appropriate for teachers?
> -  Does implementation-notes.md adequately describe the implementation, with an overview that will be useful to future maintainers?

For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by jonathanolson** [comment]
Also curious about how much of the model is in the view coordinate frame, and how the coordinate frames relate (for implementation notes).

**Comment by andrewadare** [comment]
> Also curious about how much of the model is in the view coordinate frame, and how the coordinate frames relate (for implementation notes).

@pixelzoom had a comment in the original Java implementation-notes.txt file about this:
```
 - This sim uses a pseudo-3D perspective, essentially a projection with no vanishing point.
See CLModelViewTransform3D to familiarize yourself with the orientation of the coordinate system.
Turning 3D descriptions into 2D projections is handled in BoxShapeCreator.
```
I preserved his remarks in implementation-notes.md (mentioning BoxShapeCreator instead of BoxShapeFactory).

**Comment by andrewadare** [comment]
The two files have been added, @jonathanolson they are ready for review.

**Comment by jonathanolson** [comment]
Looks good, thanks!
