### ISSUE TITLE
light-bulb-base.png

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#167]
> Is there a file in assets/ for every resource file in audio/ and images/? Note that there is not necessarily a
1:1 correspondence between asset and resource files; for example, several images may be in the same .ai file.

Since license.json notes it's from Faraday (and I see faradays-law has a light-bulb-base.png), this should be factored out to scenery-phet.

Did similar work for make-a-ten (https://github.com/phetsims/make-a-ten/issues/231), (https://github.com/phetsims/scenery-phet/commit/5ced4569a646e71adc900dcb918ca76644207a9e, https://github.com/phetsims/states-of-matter/commit/061c44f6ae740eed9013ac69e407b480a34de2a8) by moving the hand to scenery-phet, if that helps.

**Comment by jonathanolson** [comment]
For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by andrewadare** [comment]
The light-bulb-base png and license entry were moved from both CLB and Faraday's Law to scenery-phet.
