### ISSUE TITLE
Extra branches

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#169]
From the checklist:

> Are there git repository branches that are no longer used and should be pruned?

I see:

- ama/wireseg-factories-out (can be removed, since it was merged in)
- ama/property (has a commit on it not in master)
- wip (can be removed, since it was merged in)
- accessible-instance (pinged for update in relevant issue)

**Comment by jonathanolson** [comment]
For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by andrewadare** [comment]
These three branches are now gone:
* ama/wireseg-factories-out (can be removed, since it was merged in)
* ama/property (has a commit on it not in master)
* wip (can be removed, since it was merged in)

**Comment by jessegreenberg** [comment]
> accessible-instance (pinged for update in relevant issue)

I commented in the issue (#23) - I would like keep the branch around for reference when we continue work on this sim for accessibility.  Since the other branches were removed, closing.
