### ISSUE TITLE
Math.round usage

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#170]
From the checklist:

> Check that dot.Util.roundSymmetric is used instead of Math.round. Math.round does not treat positive and negative numbers symmetrically, see phetsims/dot#35 (comment).

I see multiple usages in IGridSizeStrategy.

For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by andrewadare** [comment]
Math.round has been replaced.
