### ISSUE TITLE
Consider 'zone' model concept

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#174]
ParallelCircuit is full of functions that are similar, except they are for:

- lightBulbTop
- lightBulbBottom
- capacitorTop
- capacitorBottom
- batteryTop
- batteryBottom
- topPlate
- bottomPlate

that are repeated elsewhere, such as Voltmeter.

Consider an enumeration of zones, so that instead of:
```js
connectedToDisconnectedLightBulbTop: function( shape ),
connectedToDisconnectedLightBulbBottom: function( shape ),
connectedToDisconnectedCapacitorTop: function( shape ),
connectedToDisconnectedCapacitorBottom: function( shape ),
//...
```
with functions that are extremely similar (duplicated code), you have one function:
```js
connectedToDisconnected: function( shape, zone )
```
and each component knows its zone.

**Comment by jonathanolson** [comment]
For code review: #117

**Comment by andrewadare** [comment]
I gave this some thought today and as a first attempt, I wrote this function (which is untested):

```js
    /**
     * Determines whether a voltmeter probe (shape) is in electrical contact
     * with a component location in this circuit. The componentInCircuit
     * parameter specifies whether to check for contact with a component that
     * is connected (true) or isolated (false) from the rest of the circuit.
     *
     * @param {Shape} shape - voltmeter probe shape
     * @param {CircuitLocation} location - specifies a portion of some circuit component
     * @param {boolean} componentInCircuit - true if the component location is connected to the rest of the circuit
     *
     * @return {Boolean}
     */
    contactBetween: function( shape, location, componentInCircuit ) {

      var switchState = this.circuitConnectionProperty.value;

      // disconnected capacitor - top half
      if ( !componentInCircuit && this.isOpen() &&
        location === CircuitLocation.CAPACITOR_TOP && (
          this.shapeTouchesWireGroup( shape, this.topCapacitorWires ) ||
          this.capacitor.intersectsTopPlate( shape ) ) ) {
        return true;
      }

      // disconnected capacitor - bottom half
      if ( !componentInCircuit && this.isOpen() &&
        location === CircuitLocation.CAPACITOR_BOTTOM && (
          this.shapeTouchesWireGroup( shape, this.bottomCapacitorWires ) ||
          this.capacitor.intersectsBottomPlate( shape ) ) ) {
        return true;
      }

      // disconnected battery - top terminal
      if ( !componentInCircuit && switchState !== CircuitState.BATTERY_CONNECTED &&
        location === CircuitLocation.BATTERY_TOP && (
          this.battery.intersectsTopTerminal( shape ) ||
          this.shapeTouchesWireGroup( shape, this.topBatteryWires ) ) ) {
        return true;
      }

      // disconnected battery - bottom terminal
      if ( !componentInCircuit && switchState !== CircuitState.BATTERY_CONNECTED &&
        location === CircuitLocation.BATTERY_BOTTOM && (
          this.battery.intersectsBottomTerminal( shape ) ||
          this.shapeTouchesWireGroup( shape, this.bottomBatteryWires ) ) ) {
        return true;
      }

      // battery - top terminal
      if ( location === CircuitLocation.BATTERY_TOP ) {
        if ( this.shapeTouchesWireGroup( shape, this.topBatteryWires ) ||
          this.battery.intersectsTopTerminal( shape ) ) {
          return true;
        }

        // connected
        if ( componentInCircuit && switchState === CircuitState.BATTERY_CONNECTED && (
            this.capacitor.intersectsTopPlate( shape ) ||
            this.shapeTouchesWireGroup( shape, this.topCapacitorWires ) ) ) {
          return true;
        }
      }

      // battery - bottom terminal
      if ( location === CircuitLocation.BATTERY_BOTTOM ) {
        if ( this.shapeTouchesWireGroup( shape, this.bottomBatteryWires ) ||
          this.battery.intersectsBottomTerminal( shape ) ) {
          return true;
        }

        // connected
        if ( componentInCircuit && switchState === CircuitState.BATTERY_CONNECTED && (
            this.capacitor.intersectsBottomPlate( shape ) ||
            this.shapeTouchesWireGroup( shape, this.bottomCapacitorWires ) ) ) {
          return true;
        }
      }

      return false;
    },
```
I did not even commit this...by the time I finished writing it, I realized it's no better than the set of `connectedTo` functions it is intended to replace.

As a second attempt, I am working on replacing the set of Wire arrays like `ParallelCircuit.topBatteryWires` and `ParallelCircuit.topCapacitorWires` with a single hash map, using keys from the `CircuitLocation` "enum". Then lookup can be done in O(1) time, the specially-named arrays can be removed, and the check for connections can be done with a much simpler interface.

**Comment by andrewadare** [comment]
The next step is to replace all the specially-named functions like `Capacitor.intersectsTopPlate(shape)` and `Battery.intersectsTopTerminal(shape)` with more general functions like `Capacitor.contactBetween(shape, CircuitLocation.CAPACITOR_TOP)`. This should be done for the Battery, Capacitor, and LightBulb.

Once that is done, the `connectedTo` functions can be condensed.

**Comment by andrewadare** [comment]
Also, there is no Shape instance doing any contacting other than the voltmeter probes. So it would improve readability to replace the `shape` parameter with `probe` (the type info will still be clear from the function docs).

**Comment by andrewadare** [comment]
I have condensed the logic of all the duplicated functions into a single function called ParallelCircuit.probeContactsComponent. It covers 12 cases (6 locations x (isolated/connected)).

The code is shorter overall, but despite all the work, it's not very a very satisfying refactor. The core problem is that the logic is still boolean, so functions like getVoltageAt are still playing 20 questions. 

If there were a performant way for the voltmeter probes to just report what they are contacting (if anything), instead of polling for every possible case, that would improve things.

**Comment by andrewadare** [comment]
@jonathanolson it would be worth some brief discussion on this to decide how to proceed. Perhaps we can find a few minutes after today's meeting.

**Comment by jonathanolson** [comment]
With CircuitLocation and the current logic, this looks quite good actually.
