### ISSUE TITLE
[kite] Add Shape-Shape intersection

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#175]
Voltmeter.probesAreTouching needs it, I'll take care of it.

For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by pixelzoom** [comment]
Reviewing status of this issue as part of #187.

@jonathanolson status of this issue?  You said "I'll take care of it", but then labeled it as deferred.

**Comment by jonathanolson** [comment]
Un-deferring, shouldn't be too hard to add.
