### ISSUE TITLE
Future porting plans

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#177]
Just saw a note:
```js
console.error( 'Dielectrics have not been ported yet, this function should not be in use.' );
```

Are things going to get fleshed out into a full Capacitor Lab sim where currently unused code should be left in place?

My recommendations for the sim will definitely change if I'm not aware of future implementation during code review.

For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by ariel-phet** [comment]
@jonathanolson there will eventually be a port of the java version of Capacitor Lab, but the current plan is to do a port of that sim using its model. The model for Capacitor Lab: Basics is I believe more or less written from scratch to deal with the situations only in the sim (full Capacitor lab has series and parallel capacitors and dielectrics and such)

**Comment by jonathanolson** [comment]
> The model for Capacitor Lab: Basics is I believe more or less written from scratch to deal with the situations only in the sim (full Capacitor lab has series and parallel capacitors and dielectrics and such)

It looks like a port, and has unused code related to dielectrics (and the base parts of the model seem to support more general things), which is why I was wondering what to do.

**Comment by ariel-phet** [comment]
@jonathanolson Oh...that was probably brought in to support the electric field line view.

I still get the feeling these will be two separate sims, and probably just makes sense in this particular case to copy over the useful parts of the model to the full port, and remove the unused portions from this sim. I do not expect them to share a relationship like Molecule Shapes and its Basics version, they will be a fair bit more decoupled than that.

**Comment by jonathanolson** [comment]
Understood, will make recommendations based on that. Thanks!
