### ISSUE TITLE
Air vs. Vacuum

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#178]
Since we have no need to handle dielectrics (re https://github.com/phetsims/capacitor-lab-basics/issues/177), and I was confused that dielectrics were added on top of air's contribution (which is the same as the vacuum).

Seems best to just handle things as a vacuum (and rename as such).

Tagging @pixelzoom to make sure this sounds good (due to AP's comments on the basics sim), and because:
```js
    /*
     * The dielectric constant of air is actually 1.0005896. The model for this sim specified that
     * the circuit was in air.  But we discovered late in the development of this sim that we should
     * have modeled the circuit in a vacuum, because we want the E-Field component due to the
     * environment to be zero.  With air, we have a small Dielectric vector of up to 4 V/m shown
     * on the E-Field Detector when the Plate Charge control is set to its maximum.
     *
     * Rather than change "air" to "vacuum" in numerous places throughout the code and design doc,
     * it was suggested that we simply set the dielectric constant of air to 1.0.  I was hesitant to
     * do this, since I think it's going to cause future problems.  But Kathy P. bet me a 6-pack of
     * beer that it will never be a problem.  Any developer who needs to change this in the future
     * is hereby bound by the Developer Code of Ethics to inform me, so that I can collect on
     * this wager.
     */
```

For code review: #117

**Comment by pixelzoom** [comment]
> Seems best to just handle things as a vacuum (and rename as such).

Yes, agreed.

 > But Kathy P. bet me a 6-pack of
     * beer that it will never be a problem.  Any developer who needs to change this in the future
     * is hereby bound by the Developer Code of Ethics to inform me, so that I can collect on
     * this wager.

@kathy-phet @ariel-phet Stout or IPA will be fine :)

**Comment by andrewadare** [comment]
All use of non-vacuum dielectric quantities has now been removed from the sim. Apart from the six-pack arrangement, this issue is complete. A surprisingly large amount of cruft was removed in the process. There were many unused functions caught by @jonathanolson that are now gone.
