### ISSUE TITLE
Moving mouse focus causes weird visual stacking

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#180]
Mousing around the switch's end point and back to the switch causes weird toggling/flickering between the end point being on top or the switch wire being on top:

![clb-stack-1](https://cloud.githubusercontent.com/assets/480878/20772923/c1f70324-b70c-11e6-9c28-c265cbbc3284.PNG)
![clb-stack-2](https://cloud.githubusercontent.com/assets/480878/20772927/c5652018-b70c-11e6-8f20-b9a85177f99e.PNG)

For code review: #117

**Comment by andrewadare** [comment]
There were some design revisions a few months ago related to the switch appearance, as discussed in #140. #145 may also pertain. For those issues, I introduced a tipCircle node in SwitchNode.js, but it looks like there was an ordering problem. The commits above add a listener that keeps the visual effect consistent between the center switch position and the others.

**Comment by jonathanolson** [comment]
I'm a bit unclear on when the connection point is supposed to be yellow (where is the mouse / what state is the mouse button/touch in, what is the state of the switch, etc.), and where the connection point highlight is supposed to be (yellow, but there is one on top of the wire end and one below the wire end).

@arouinfar, can you advise?

**Comment by arouinfar** [comment]
@jonathanolson the connection point should be yellow when the mouse hovers over the click area for the switch position. In the screenshot below, my mouse was in the right-most triangle.
<img width="271" alt="screen shot 2017-01-19 at 1 59 14 pm" src="https://cloud.githubusercontent.com/assets/8419308/22125074/87128c0a-de4f-11e6-873f-bce099839ef0.png">

I have not been able to observe the layering issue in the original comment, but the yellow circle should always be layered above the wire.

**Comment by jonathanolson** [comment]
Does "hovers over" imply that there should be no highlight when the switch is being dragged or when the mouse is pressed down on it?

**Comment by pixelzoom** [comment]
I'm reviewing this issues as part of #187. This issue is labeled "ready-for-review". It looks like @jonathanolson was in the process of reviewing, but had some questions and is eating for a reply from @arouinfar.   @arouinfar @jonathanolson?

**Comment by jonathanolson** [comment]
Still uncertain about desired behavior, https://github.com/phetsims/capacitor-lab-basics/issues/180#issuecomment-273908638 mentions my remaining question.

**Comment by jonathanolson** [comment]
>> Does "hovers over" imply that there should be no highlight when the switch is being dragged or when the mouse is pressed down on it?
>
> Good question. I don't think the highlight needs to be present when dragged or clicked -- just on hover. The behavior in dev.37 looks good to me.

It's getting really onerous to maintain the exact behavior of dev.37 (but without the overlap bug) while moving away from 4 independently draggable things with 5 different input listeners. It's also extra tricky because the empty "connection points" are circles that are slightly smaller than the actual filled "connection point".

I'd like to clarify with essentially one of these options:

1. Exact behavior of dev.37 (without the overlap bug) desired. Includes the yellow-flicker when pressing the mouse down on the switch and then moving mouse between these areas:
![capacitor-area](https://user-images.githubusercontent.com/480878/29342720-8dfa6392-81e9-11e7-89b4-898925cad170.PNG)
(yellow when below switch itself, blue background when over the switch or in its range) and all other similar behavior.
2. Exact description of how it should work, with behavior for hovering, when it should have the yellow highlight, etc.
3. Let me do what I think is best (correct me if something is undesirable), potentially with guidelines. For instance, are these two dashed circle sizes different for a reason: (first one is mouse "up", second is mouse "down):
![capacitor-1](https://user-images.githubusercontent.com/480878/29342829-656e07ca-81ea-11e7-820d-76d1d119bd83.PNG)
![capacitor-2](https://user-images.githubusercontent.com/480878/29342831-6a55b102-81ea-11e7-8a14-d6fecb08a8ca.PNG)

**Comment by jonathanolson** [comment]
For reference: dev.37: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.37/capacitor-lab-basics_en.html

Also:
(1) is probably more expensive by about half a day's work, so I'd rather not do that unless it is the exact behavior desired.

**Comment by arouinfar** [comment]
@jonathanolson didn't realize there was maintainability issues with the behavior in dev.37. Please go with option (3) and do what you think is best. Those two dashed circles are not meant to be different, aside from their stroke and fill colors. Please let me know if you have any questions!

**Comment by jonathanolson** [comment]
I've brought the behavior up closer to what I think it should be, let me know how it behaves.

For now, pressing down on a switch area that isn't selected just sets the switch to that, but doesn't start a drag. If drags should be started from those unselected areas, let me know (it's an easy change).

**Comment by arouinfar** [comment]
Behavior looks nice on Mac and iPad. Closing.
