### ISSUE TITLE
Circuit model refactoring

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#181]
This is an attempt to unify several issues and REVIEW comments from #117 related to the circuit model. The following four components are related as follows:
```
             AbstractCircuit
                    |
             ParallelCircuit
               /         \
CapacitanceCircuit    LightBulbCircuit
```
We have the following issues:
 - Given its name and position in the graph, AbstractCircuit should behave more like an abstract class. There is too much implementation there right now. Some of this has already been handled by yesterday's commits (against #117).
 - There is unnecessary generality in the graph, as if there was an intention for AbstractCircuit to have more than one child (perhaps a SeriesCircuit was in the back of someone's mind). It was decided in #177 that we should not be leaving "hooks" for a more general model in CL:B, but instead we should commit to working with the current model only.
 - AbstractCircuit takes two callbacks that create the circuit, `createCircuitComponents` and `createWires`. It was noted by @jonathanolson that this is not an ideal design, and that preferably, the components should just be created in the concrete subtypes.
 - There are are many getter methods in AbstractCircuit like `getTopWires` that do unnecessary work at runtime, since they use iteration to filter a subset of wires or components that only needs to be generated once at circuit construction time. They should instead be "memoized" in public vars like `CapacitanceCircuit.topWires`. It is doubtful that these vars even need to exist in AbstractCircuit.
 - Another sign of excessive generality is the existence of single-element arrays like this code from LightBulbCircuit:
```js
   //REVIEW: Probably move this up to the common circuit, since every circuit has exactly one.
    this.capacitor = this.capacitors[ 0 ];
    //REVIEW: Probably can remove code that handles multiple light-bulbs?
    this.lightBulb = this.lightBulbs[ 0 ];
```
All of these considerations raise the question of why we even need (or want) AbstractCircuit at all.

I believe the best thing would be to remove AbstractCircuit completely, and shift all its logic to the other three components.

@jonathanolson before I embark on this, can you provide your appraisal of this idea?

**Comment by jonathanolson** [comment]
Sounds great!

> AbstractCircuit should behave more like an abstract class. There is too much implementation there right now.

In general, I'm not concerned with having lots of implementation in abstract types (usually the concrete functions operate on what the abstract ones would do). Many notes refer to moving behavior shared between CapacitanceCircuit/LightBulbCircuit into the shared supertype.

**Comment by andrewadare** [comment]
AbstractCircuit has been removed from the model, and its functionality has been moved elsewhere. ParallelCircuit is now a bit distended, but this is a temporary condition. Closing since there is ample coverage for remaining work in other issues and the review comments.
