### ISSUE TITLE
Mousing over drag arrows makes + and - appear

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#184]
On initial load, the charge symbols appear on the plates if the mouse pointer crosses a drag arrow.

Dies ist ein Heisenbug. I have not gotten a screenshot yet. When it happens, the reset button doesn't always clear the symbols, and they don't redistribute with plate resizing.

**Comment by andrewadare** [comment]
![image](https://cloud.githubusercontent.com/assets/154163/21117309/4701845a-c076-11e6-9fa1-520dc5c830c0.png)

**Comment by jonathanolson** [comment]
Haven't been able to reproduce, but will review the code to find out how it happens.

**Comment by jonathanolson** [comment]
Can't reproduce. If it happens again, I'll fix then (might fix during code review).
