### ISSUE TITLE
Capacitor Plate contact area not updating

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/capacitor-lab-basics#185]
It seems like the voltage probe's contact area for the capacitor plates isn't updating at all when the size or separation is updated. 
![image](https://cloud.githubusercontent.com/assets/22551096/21332721/a760ee30-c607-11e6-825d-940466d162c1.png)
The probe is at the plate's original position and size, and is registering voltage.
![image](https://cloud.githubusercontent.com/assets/22551096/21332740/c71d6532-c607-11e6-8a1c-9c0c60367db0.png)
Conversely, where the probe should be registering voltage it is not.
![image](https://cloud.githubusercontent.com/assets/22551096/21332752/e5cf8b36-c607-11e6-8e81-accd0bd344e4.png)
It should also be registering a voltage here, when the plates were expanded from their original position.

Seen on: Chrome, Firefox, Edge

Related to https://github.com/phetsims/tasks/issues/754

Debug Info;
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.37/capacitor-lab-basics_en.html
Version: 1.0.0-dev.37 2016-12-15 21:18:43 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Language: en-US
Window: 1680x930
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"1ea1df65","branch":"master"},"axon":{"sha":"5ead575b","branch":"master"},"babel":{"sha":"893c10ee","branch":"master"},"brand":{"sha":"7fd57704","branch":"master"},"capacitor-lab-basics":{"sha":"120bb48c","branch":"master"},"chipper":{"sha":"47f0abee","branch":"master"},"dot":{"sha":"cbaaa816","branch":"master"},"joist":{"sha":"329a8fde","branch":"master"},"kite":{"sha":"c1ca4885","branch":"master"},"phet-core":{"sha":"aa50d401","branch":"master"},"phetcommon":{"sha":"4692cb97","branch":"master"},"query-string-machine":{"sha":"b38c3c25","branch":"master"},"scenery":{"sha":"c3bdae4a","branch":"master"},"scenery-phet":{"sha":"5df82fe5","branch":"master"},"sherpa":{"sha":"8ad125cb","branch":"master"},"sun":{"sha":"fd47792d","branch":"master"},"tandem":{"sha":"8d1d042a","branch":"master"},"twixt":{"sha":"ad0d17b7","branch":"master"}}

**Comment by andrewadare** [comment]
@EthanWJohnson great catch. The problem might have been introduced in 1261e84.

**Comment by andrewadare** [comment]
This should be fixed now on master (it is behaving correctly in my local tests.)

**Comment by jonathanolson** [comment]
Confirmed fixed.
