### ISSUE TITLE
Update credits

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#189]
QA or anything else

**Comment by arouinfar** [comment]
Took a look at the credits in the latest dev, and they're pretty out of date. I recommended in https://github.com/phetsims/capacitor-lab-basics/issues/168#issuecomment-267638496 to 
1. Remove Graphic Arts section (usually reserved for non-team members who create artwork, which is irrelevant here)
2. Add Emily Moore to the Team
3. Add Emily Randall as either a team member or developer.

@ariel-phet can you recommend how to credit Emily Randall? I believe she was involved in porting some of the Java model, and you can see her commit history [here](https://github.com/phetsims/capacitor-lab-basics/commits?author=EmilyRandall).

**Comment by ariel-phet** [comment]
Emily Randall can certainly be credited in the developer section.

@phet-steele will be able to give proper QA credits when this goes to RC

**Comment by arouinfar** [comment]
Looks like credits in [capacitor-lab-basics-main.js](https://github.com/phetsims/capacitor-lab-basics/blob/master/js/capacitor-lab-basics-main.js) are already up to date, so all that's left is the remaining QA credits.

**Comment by phet-steele** [comment]
QA credits are up to date as of 11/2/2017.

**Comment by phet-steele** [comment]
Up to date as of 11/8/2017
