### ISSUE TITLE
Cueing arrows should reappear on reset all

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#190]
When playing with dev.37, I noticed that the cueing arrows on the switch do not reappear on reset all. Since dev.37 is pretty stale, I took a look at master, and the behavior is present there too.

1. On startup, move switch. Cueing arrow disappears (as it should).
2. Click reset all.
3. Switch returns to default position, but cueing arrow does not reappear (but it should).
4. Click reset all again, and the cueing arrow will reappear.

Step 4 only works so long as the switch isn't moved again.

**Comment by jonathanolson** [comment]
Should be fixed, can you verify?

**Comment by arouinfar** [comment]
Looks great! Thanks @jonathanolson.
