### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#191]
For a more unified look-and-feel, there have been some recent efforts to reduce the number of variations of blue backgrounds used in sims. For example, see  https://github.com/phetsims/balloons-and-static-electricity/issues/310.

@jonathanolson please update these colors to the following:
DISCONNECTED_POINT_COLOR: 'rgb( 200, 230, 255 )'
SCREEN_VIEW_BACKGROUND_COLOR: 'rgb( 151, 208, 255 )'

The cueing arrow should match `DISCONNECTED_POINT_COLOR`, but that appears to be artwork, so I'll update the assets and send to @jonathanolson.

**Comment by jonathanolson** [comment]
Should be complete.
