### ISSUE TITLE
Cueing arrow should stay until switch has landed in a new postion

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#194]
@jonathanolson, the cueing arrow should stay visible until it is released (or jumped by clicking) in a new position it didn't originate in. Currently, it simply disappears upon the first interaction of the switch, regardless of if the switch actually changes its final position.

@arouinfar has confirmed this suggestion has been the desired behaviour.

For phetsims/QA/issues/56.

**Comment by jonathanolson** [comment]
Implemented.

Also I'd like to note that the "cue" presence is shared across both screens (there's documentation that seems to indicate that is desired). That is looking good also?

**Comment by phet-steele** [comment]
Beautiful.

> Also I'd like to note that the "cue" presence is shared across both screens (there's documentation that seems to indicate that is desired). That is looking good also?

Looking great, thanks @jonathanolson.

**Comment by phet-steele** [comment]
Hooray, this was my 1000th closed issue!
