### ISSUE TITLE
Voltmeter readout and label too far up

### ISSUE THREAD

**Issue by CWilson4960** [phetsims/capacitor-lab-basics#196]
Test device: Macbook Pro

Operating System: MacOS Sierra 10.12.6

Browser: Chrome

Problem description: Voltmeter readout and label need to be moved down to match Circuit Construction Kit: DC
The voltmeters aren't exactly the same so this might be difficult to do.
Assigning Amy @arouinfar to help with this

Screenshots:
RIght one:
![correctvoltmeter](https://user-images.githubusercontent.com/31217926/32016991-9b39b60e-b982-11e7-9ba1-24d1ade0d16d.jpeg)
One in capacitor lab basics:
![voltmetercapacitorlab](https://user-images.githubusercontent.com/31217926/32016998-9e243b0a-b982-11e7-9758-81003edba6ac.jpeg)

related to phetsims/QA/issues/56

URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.1/capacitor-lab-basics_en.html
Version: 1.5.0-dev.1 2017-10-18 16:42:15 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1243x625
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"8a8ff7d2","branch":"master"},"babel":{"sha":"0b5a4452","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"capacitor-lab-basics":{"sha":"5fdf1748","branch":"master"},"chipper":{"sha":"b8a3c09a","branch":"master"},"dot":{"sha":"84bc5146","branch":"master"},"joist":{"sha":"e5c2e673","branch":"master"},"kite":{"sha":"067109a8","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"b13138d2","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"c9c3052a","branch":"master"},"scenery-phet":{"sha":"124c1c25","branch":"master"},"sherpa":{"sha":"0d590744","branch":"master"},"sun":{"sha":"082fee37","branch":"master"},"tandem":{"sha":"98e9917c","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by ariel-phet** [comment]
This voltmeter should likely be a common code component right?

**Comment by phet-steele** [comment]
> This voltmeter should likely be a common code component right?

@ariel-phet It should be, but it isn't!

**Comment by arouinfar** [comment]
I prefer the CCK-style layout for the title/readout.

**Comment by jonathanolson** [comment]
Changed the layout to match.

@samreid, were the images copied for CCK's voltmeter node?

**Comment by samreid** [comment]
@arouinfar delivered CCK voltmeter artwork on 10/25/15, but I can see that @jessegreenberg committed capacitor-lab-basics/assets/voltmeter_body.ai two months earlier.

**Comment by samreid** [comment]
@arouinfar are you recommending we commonize the CCK artwork and reuse it in Capacitor Lab Basics?  Do we have other simulations with a voltmeter?

**Comment by samreid** [comment]
To answer my own question, Faraday's law has a voltmeter, but it is a different kind.

**Comment by phet-steele** [comment]
@jonathanolson the readout looks closer to the left than the right (so not centered). Looks like this was the case before your change, too.

<img width="225" alt="screen shot 2017-10-27 at 10 45 02 am" src="https://user-images.githubusercontent.com/5863899/32115429-0b269162-bb04-11e7-9470-71634f1ff554.png">

**Comment by jonathanolson** [comment]
> @jonathanolson the readout looks closer to the left than the right (so not centered). Looks like this was the case before your change, too.

Looks like there is an extra ~9 pixels on the left of the source image for the voltmeter background. I'll cut this off and rework things to align properly.

**Comment by jonathanolson** [comment]
@phet-steele and @arouinfar, is the layout acceptable now?

**Comment by jonathanolson** [comment]
Forgot to reference issue, commit is e2e485042b9bf20620413e37eeff036e3d86c170

**Comment by phet-steele** [comment]
@arouinfar does the readout box seem slightly too tall to you? It gets pretty close to the descender on the "g" as well.

**Comment by arouinfar** [comment]
It's looking a lot better @jonathanolson, but as @phet-steele pointed out, the readout box does look a bit too tall, which doesn't leave enough negative space between "Voltage" and the readout.

**Comment by jonathanolson** [comment]
Adjusted height and stroke (since the stroke was a lot thicker than CCK).

How does it look now?

**Comment by arouinfar** [comment]
Looks great @jonathanolson! Thanks.
