### ISSUE TITLE
Battery & wire not aligned

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#198]
@jonathanolson @arouinfar the battery does not look centered on the wires. This is easiest to see at the upper connection:

<img width="201" alt="screen shot 2017-10-27 at 10 47 38 am" src="https://user-images.githubusercontent.com/5863899/32115691-093b62c8-bb05-11e7-8f2d-8964fc68e28a.png">
<img width="215" alt="screen shot 2017-10-27 at 10 47 49 am" src="https://user-images.githubusercontent.com/5863899/32115692-095133b4-bb05-11e7-90cb-282f8df16e50.png">

I don't know if it's because:

(1) The battery artwork isn't symmetrical?
(2) The battery is positioned too for right?
(3) The wire is positioned too far left?

Whichever of those three it is, the wire and battery should probably be better aligned.

For phetsims/QA/issues/56.

**Comment by arouinfar** [comment]
@phet-steele @jonathanolson I checked the .ai assets for the battery, and the terminals are centered, so (1) is not the culprit here.

**Comment by arouinfar** [comment]
@jonathanolson can you investigate (2) and (3)?

**Comment by jonathanolson** [comment]
Some of the effect may be coming from the terminals on the battery images not being quite in the center, e.g.:

![battery-center](https://user-images.githubusercontent.com/480878/32117487-c558ff82-bb0b-11e7-96c5-e06eebe45a97.PNG)

I'll try adjusting the empty space on the images to see if it fully resolves the issue.

**Comment by arouinfar** [comment]
@jonathanolson it's possible that the ovals themselves are goofy. When I try to re-center the terminal over the battery, the terminal doesn't move at all.

**Comment by jonathanolson** [comment]
The batteries look like they could be drawn fairly easily in code (based on measurements from the original images).

Should I go that route?

Otherwise, maybe try re-exporting the images (particularly so they are the same size), since they are different sizes, and I can look at determining if an offset in code is needed.

**Comment by arouinfar** [comment]
@jonathanolson I'd prefer that the artwork be drawn in code, if you're up to it. :)

>  maybe try re-exporting the images (particularly so they are the same size)

Yikes, sorry about that. I'd like to think that I handle assets a bit better these days...

**Comment by jonathanolson** [comment]
Current battery-in-code progress:
![clb-battery-code](https://user-images.githubusercontent.com/480878/32198477-dbfdee4e-bd8d-11e7-8a2c-5adc5283f3f9.PNG)

Compared to reference images:
![battery](https://user-images.githubusercontent.com/480878/32198487-e7c8a66a-bd8d-11e7-89a2-9532f0dbe279.png)
![battery_upside-down](https://user-images.githubusercontent.com/480878/32198488-e7db6aa2-bd8d-11e7-9595-4d87e21a8108.png)

**Comment by arouinfar** [comment]
Looks really nice @jonathanolson!!

**Comment by jonathanolson** [comment]
Thanks!

One note: on the positive terminal of the original image, the terminal appears to be somewhat closer to the camera than the actual center of the battery:
![clb-battery-top](https://user-images.githubusercontent.com/480878/32198593-52e17d14-bd8e-11e7-8d62-91b45dc36898.PNG)

You would expect the outer ellipse of the battery's top to have the same center as the bottom of the terminal, but the terminal ellipse is slightly lower.

Should I consider moving this up?

**Comment by jonathanolson** [comment]
> Should I consider moving this up?

Just moving the terminal up:
![clb-battery-raised-1](https://user-images.githubusercontent.com/480878/32198699-c5298d62-bd8e-11e7-9430-dcc9c4b050be.PNG)

or the (preferred) making the terminal slightly shorter:
![clb-battery-raised-2](https://user-images.githubusercontent.com/480878/32198705-cf564258-bd8e-11e7-9e33-ac239172d919.PNG)

**Comment by arouinfar** [comment]
@jonathanolson I like the 2nd screenshot in https://github.com/phetsims/capacitor-lab-basics/issues/198#issuecomment-340603183, so let's go with that.

**Comment by jonathanolson** [comment]
Fully moved the battery over to the code-drawn version (with the desired terminal above). Adjusted wire start/end position very slightly (sim was accounting for the padding in the original images).

@arouinfar, can you check to see if this looks acceptable?

**Comment by arouinfar** [comment]
Looks beautiful @jonathanolson!
