### ISSUE TITLE
Screenshot for 1.0

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#199]

**Comment by arouinfar** [comment]
![image](https://user-images.githubusercontent.com/8419308/32301664-7db6827c-bf24-11e7-9382-9413876324e2.png)

**Comment by arouinfar** [comment]
Alternate screenshots:
![screen shot 2017-11-01 at 4 53 47 pm 2](https://user-images.githubusercontent.com/8419308/32301857-4ecad4c6-bf25-11e7-809d-60c80b08bf9e.png)
![screen shot 2017-11-01 at 4 54 35 pm](https://user-images.githubusercontent.com/8419308/32301867-5e8a332a-bf25-11e7-9659-6967a7df6084.png)

**Comment by phet-steele** [comment]
Will do after #201.

**Comment by phet-steele** [comment]
Done.
