### ISSUE TITLE
Improve probe bounds along the left of the screen

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#202]
The probes can be easily lost on the left side of the screen with respect to ?dev bounds, like the black probe below.

<img width="1039" alt="screen shot 2017-11-02 at 1 14 03 pm" src="https://user-images.githubusercontent.com/5863899/32345543-1e15710a-bfd0-11e7-942f-8ef25935cb75.png">

Maybe bound the probes by their center (about where I have the red probe). @arouinfar thinks this distance is fine.

If possible, leave the bounds on all other sides of the screen unchanged. For phetsims/QA/issues/56.

**Comment by jonathanolson** [comment]
Implemented, @phet-steele can you verify?

**Comment by phet-steele** [comment]
Great, thanks @jonathanolson.
