### ISSUE TITLE
Inconsistent highlighting of moving components

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/capacitor-lab-basics#205]
**Test device:**

MacBook Air (13-inch, Early 2015)

**Operating System:**

macOS Sierra Version 10.12.6 (16G29)

**Browser:**

Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Problem description:**

This is for phetsims/QA/issues/63.

## 1) Arrows can be green (unhighlighted) when being moved
As you increase or decrease plate area or separation, the arrow can become green, i.e. unhighlighted. This seems inconsistent because all other moving components stay highlighted, i.e. yellow, as they are moved with the exception of the battery slider, which turns blue when moved.

## 2) Moving parts can become highlighted as you are moving a part
I've also noticed that if you are moving a component (doesn't matter which one) you can scroll over other moving components and they will still become highlighted. I don't think this makes sense because the highlighting feature is presumably intended to
* A) show that a component can be moved
and
* B) show which component is being moved.

If this is the case, then having other components become highlighted as you are moving a component could be confusing because it sort of contradicts B.

## 3) Inconsistency in highlighting colors
@arouinfar, I noticed that you changed the color to yellow in #102 because students were having trouble realizing that you can move the battery slider, but do you think it would be a good idea to change the stationary color of the battery slider to something other than yellow so that it could be "highlighted" (yellow) like the rest of the moving parts when it is moved?

**Steps to reproduce:**

## 1) Arrows can be green (unhighlighted) when being moved
1. Start moving one of the arrows.
2. Move your cursor around sort of erratically and the arrow should unhighlight.

## 2) Moving parts can become highlighted as you are moving a part
1. Click on a moving component other than the plate arrows.
2. Move your cursor over some other moving component.

## 3) Inconsistency in highlighting colors
N/A

**Screenshots:**

## 1) Arrows can be green (unhighlighted) when being moved
![nov-06-2017 11-20-48](https://user-images.githubusercontent.com/31285590/32456969-a0379d9a-c2e4-11e7-9008-e8392deeb148.gif)

## 2) Moving parts can become highlighted as you are moving a part
![nov-06-2017 11-30-58](https://user-images.githubusercontent.com/31285590/32457359-17647338-c2e6-11e7-8e29-7333488d00f6.gif)

![nov-06-2017 11-22-13](https://user-images.githubusercontent.com/31285590/32457015-c78178d0-c2e4-11e7-9e3e-56284a7c53e6.gif)

## 3) Inconsistency in highlighting colors
![nov-06-2017 11-24-55](https://user-images.githubusercontent.com/31285590/32457135-31c36c12-c2e5-11e7-8231-cd8c77ed9420.gif)

**Troubleshooting information (do not edit):**

Name: ‪Capacitor Lab: Basics‬
URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.2/capacitor-lab-basics_en.html
Version: 1.5.0-dev.2 2017-11-03 18:31:03 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
Language: en-US
Window: 1438x659
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"92357e1d","branch":"master"},"babel":{"sha":"b250509d","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"capacitor-lab-basics":{"sha":"9d38e701","branch":"master"},"chipper":{"sha":"5241d57d","branch":"master"},"dot":{"sha":"ae6ad936","branch":"master"},"joist":{"sha":"d294c2ac","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"phet-core":{"sha":"3a8ff8b6","branch":"master"},"phetcommon":{"sha":"ef03b2b8","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"5294ce72","branch":"master"},"scenery-phet":{"sha":"1ad80ecb","branch":"master"},"sherpa":{"sha":"c2cc5408","branch":"master"},"sun":{"sha":"92e4cb0b","branch":"master"},"tandem":{"sha":"dd2b1031","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by arouinfar** [comment]
Great observations @lmulhall-phet! I think the primary purpose of highlighting on hover is to indicate that an element is interactive, not necessarily that the element is being interacted with. I don't think issues (1) and (2) are necessarily problematic, though they can appear a bit odd at times (as your screencaptures demonstrate).

> 1. Arrows can be green (unhighlighted) when being moved

@jonathanolson is it possible/feasible to always keep the arrows yellow once they grabbed or dragged?

> 2. Moving parts can become highlighted as you are moving a part

While a bit strange, there might not be a way to block hover behaviors when some other sim element is grabbed. I'm not inclined to address this.

> 3. Inconsistency in highlighting colors

We had considered a few other options (such as green or magenta) but the team settled on yellow, since it was both eye catching and aesthetically pleasing. The changes made in #102 worked nicely to address a flow issue in interviews, so I would not be in favor of changing the thumb color (which would require further interviews).  I think it's important that hover behaviors are distinct enough to catch a user's attention, and the battery thumb already fits this requirement.

**Comment by jonathanolson** [comment]
I assumed previously (1) and (2) were sim-specific desired behaviors, as it is definitely not the typical way of doing things. If not desired, I'd definitely prefer to fix it up.

**Comment by arouinfar** [comment]
Sounds good @jonathanolson! There weren't any design discussions regarding (1) and (2), so an earlier dev may have made that call on their own. 

Great catch @lmulhall-phet!

**Comment by jonathanolson** [comment]
I believe I handled (1) and most of (2).

The slider on the battery will still improperly highlight when a press was started on the switch and/or plate arrows. Fixing this may be outside the scope of this issue (notice that it happens for most sliders in sims, and with most things, e.g. the reset all button).

Can you please check everything (except the battery highlight) and let me know how it looks?

Please let me know if the slider thing should be solved and I'll move forward with that (it will affect all sims with sliders).

**Comment by phet-steele** [comment]
@jonathanolson looks like you will need to put a tandem in for this, or do something else?

```
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/assert/js/assert.js:22:13)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/tandem/js/Tandem.js?bust=1510072084239:91:21)
    at new PressListener (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/scenery/js/listeners/PressListener.js?bust=1510072084239:260:31)
    at new ConnectionNode (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/capacitor-lab-basics/js/common/view/ConnectionNode.js?bust=1510072084239:79:25)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/capacitor-lab-basics/js/common/view/SwitchNode.js?bust=1510072084239:103:33
    at Array.forEach (<anonymous>)
    at new SwitchNode (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/capacitor-lab-basics/js/common/view/SwitchNode.js?bust=1510072084239:99:31)
    at CapacitanceCircuitNode.CLBCircuitNode [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/capacitor-lab-basics/js/common/view/CLBCircuitNode.js?bust=1510072084239:72:35)
    at new CapacitanceCircuitNode (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/capacitor-lab-basics/js/capacitance/view/CapacitanceCircuitNode.js?bust=1510072084239:26:20)
    at new CapacitanceScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1510064865662/capacitor-lab-basics/js/capacitance/view/CapacitanceScreenView.js?bust=1510072084239:42:34)
```

**Comment by jonathanolson** [comment]
Sorry, should be fixed! Should I be running instance proxies to catch things like that?

**Comment by phet-steele** [comment]
> Should I be running instance proxies to catch things like that?

You could, but Bayes caught this running the phet-io-fuzz test. It's not being reported anymore, so fixed.
