### ISSUE TITLE
Wires are measurable behind the connection nodes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#206]
@jonathanolson that little nub of wire where my red probe is touching is potentially problematic. There is no visible metallic component that probe is touching when I have debug areas off.

<img width="404" alt="screen shot 2017-11-06 at 12 23 35 pm" src="https://user-images.githubusercontent.com/5863899/32459650-965951a2-c2ed-11e7-87bd-5f6c84a9c1e6.png">

Without debug areas it looks like this:
<img width="310" alt="screen shot 2017-11-06 at 12 32 06 pm" src="https://user-images.githubusercontent.com/5863899/32459998-8e179a20-c2ee-11e7-819c-e36290eca13c.png">

Which is inconsistent with this:
<img width="316" alt="screen shot 2017-11-06 at 12 32 18 pm" src="https://user-images.githubusercontent.com/5863899/32459999-8e2b863e-c2ee-11e7-8aba-f6c5d34c6532.png">

@arouinfar and I are thinking maybe do two things:

1. Layer the wire on top so the metallic part is visual.
2. Then shorten the wire so that it looks centered within its circle.

@arouinfar Maybe like this? Ignore that my red dashed circles are under the wire, they should be over the wire like the middle connection.
<img width="256" alt="screen shot 2017-11-06 at 1 03 40 pm" src="https://user-images.githubusercontent.com/5863899/32461460-1b4e615e-c2f3-11e7-87fd-96445e05d614.png">

Or like this where the length is more similar to that of the middle connection?
<img width="196" alt="screen shot 2017-11-06 at 12 52 39 pm" src="https://user-images.githubusercontent.com/5863899/32461461-1b643ae2-c2f3-11e7-9c07-86e7160f9a09.png">

@jonathanolson what do you think?
For phetsims/QA/issues/63

**Comment by jonathanolson** [comment]
Right now, that color is fully opaque. What if it was made transparent (so that it looks like the same color in front of the blue), but shows a bit of the wire through? (I'll see if I can make a quick example)

**Comment by jonathanolson** [comment]
> What if it was made transparent

Tried it, didn't look good, would not recommend.

No strong preference on appearance, prefer the "looks like the middle connection" slightly.

Will wait for @arouinfar's opinion.

**Comment by arouinfar** [comment]
Thanks for the mockups @phet-steele!

> ![image](https://user-images.githubusercontent.com/8419308/32463486-39fe8104-c2fa-11e7-9089-87f186947981.png)

@jonathanolson thanks for testing out the opacity. Since that doesn't work out, let's go with this option (with the red circle layered on top) as it most closely matches the look of the switch arm.

**Comment by jonathanolson** [comment]
Implemented, @arouinfar can you see if that looks good?

**Comment by jonathanolson** [comment]
(in call, discussed having the red dashed border behind with the light-blue circle, let me know if I should change it to in front).

**Comment by arouinfar** [comment]
@jonathanolson looks pretty good. I think there was a slight miscommunication, though. I'd like for the red dashed line to be on top of the wire, like the black dashed line is on top of the switch arm.
![screen shot 2017-11-07 at 4 45 48 pm 2](https://user-images.githubusercontent.com/8419308/32524036-26db534a-c3db-11e7-8f1e-e1ed25e7aacf.png)

**Comment by jonathanolson** [comment]
Fixed, let me know if it needs anything else.

**Comment by arouinfar** [comment]
Looks great, thanks!
