### ISSUE TITLE
Voltmeter can become stuck to cursor

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/capacitor-lab-basics#207]
**Test device:**

1. MacBook Air (13-inch, Early 2015)
2. ASUS Laptop

**Operating System:**

1. macOS Sierra Version 10.12.6 (16G29)
2. Windows 10

**Browser:**

* Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
* Edge 40.15063.0.0
* Safari Version 11.0.1 (12604.3.5.1.1)
* Firefox 56.0.2 (64-bit)

**Problem description:**

The voltmeter can become stuck to the cursor. This is for phetsims/QA#63. 

Bug exists in:
* Chrome
* Edge
* Safari

**Steps to reproduce:**

macOS, Chrome, Safari:
1. Right click voltmeter.
2. Left click anywhere else. The voltmeter should be stuck to the cursor.

Windows, Chrome, Edge:
1. Right click voltmeter, and then left click immediately (almost simultaneously).
2. Left click anywhere else. The voltmeter should be stuck to the cursor.

**Screenshots:**

![nov-06-2017 15-34-05](https://user-images.githubusercontent.com/31285590/32467487-fbb168a4-c307-11e7-8147-8a464fde702e.gif)

**Troubleshooting information (do not edit):**

Name: ‪Capacitor Lab: Basics‬
URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.2/capacitor-lab-basics_en.html
Version: 1.5.0-dev.2 2017-11-03 18:31:03 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
Language: en-US
Window: 1438x659
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"92357e1d","branch":"master"},"babel":{"sha":"b250509d","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"capacitor-lab-basics":{"sha":"9d38e701","branch":"master"},"chipper":{"sha":"5241d57d","branch":"master"},"dot":{"sha":"ae6ad936","branch":"master"},"joist":{"sha":"d294c2ac","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"phet-core":{"sha":"3a8ff8b6","branch":"master"},"phetcommon":{"sha":"ef03b2b8","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"5294ce72","branch":"master"},"scenery-phet":{"sha":"1ad80ecb","branch":"master"},"sherpa":{"sha":"c2cc5408","branch":"master"},"sun":{"sha":"92e4cb0b","branch":"master"},"tandem":{"sha":"dd2b1031","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by EthanWJohnson** [comment]
I'll note that if you right click once its stuck on Windows 10 Edge or Chrome, it will become unstuck and can be manipulated normally. It can't be unstuck without reloading the sim or some complicated process on Mac.

**Comment by jonathanolson** [comment]
This should be fixed in the latest master, can you verify?

**Comment by phet-steele** [comment]
Works well in 1.5.0-rc.1.
