### ISSUE TITLE
Battery off center from wire in StringTest=double 

### ISSUE THREAD

**Issue by CWilson4960** [phetsims/capacitor-lab-basics#208]
Test device: Macbook Pro 2012

Operating System: OS Sierra 10.12.6

Browser: Chrome Version 62.0.3202.89 (64-bit)

Problem description: The battery is not aligned along the wire when in stringTest=double. It is pushed slightly to the left in comparison to the sim with no query parameters. This also occurs in rtl

Steps to reproduce:
Go to this link: 
https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en.html?stringTest=double
phetsims/QA/issues/64
Screenshots:
With stringTest:
![batterystringtest double](https://user-images.githubusercontent.com/31217926/32564809-8deddb42-c472-11e7-94f8-a51e10b1c015.jpeg)
![screenshotdoubleflipped](https://user-images.githubusercontent.com/31217926/32565174-87df5fa4-c473-11e7-8c3f-31575f074d0a.jpeg)

Without:
![battery-noquery](https://user-images.githubusercontent.com/31217926/32564822-943e66e2-c472-11e7-84fd-12feb281d682.jpeg)

URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en.html
Version: 1.5.0-rc.1 2017-11-08 00:09:49 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1272x631
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"63a66772","branch":"HEAD"},"babel":{"sha":"483be533","branch":"master"},"brand":{"sha":"53cf227b","branch":"HEAD"},"capacitor-lab-basics":{"sha":"fc8bbb18","branch":"HEAD"},"chipper":{"sha":"05dcc77d","branch":"HEAD"},"dot":{"sha":"4a1ddd12","branch":"HEAD"},"joist":{"sha":"58528a77","branch":"HEAD"},"kite":{"sha":"e4c0b773","branch":"HEAD"},"phet-core":{"sha":"ad21faf3","branch":"HEAD"},"phetcommon":{"sha":"d957aefc","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"e4328b73","branch":"HEAD"},"scenery-phet":{"sha":"70e077d6","branch":"HEAD"},"sherpa":{"sha":"5079b265","branch":"HEAD"},"sun":{"sha":"432da6da","branch":"HEAD"},"tandem":{"sha":"e53e93b6","branch":"HEAD"},"twixt":{"sha":"13905577","branch":"HEAD"}}

**Comment by jonathanolson** [comment]
Should be fixed in master, can you verify?

**Comment by CWilson4960** [comment]
Fixed. Thank you!
