### ISSUE TITLE
showDebugAreas parameter broken

### ISSUE THREAD

**Issue by CWilson4960** [phetsims/capacitor-lab-basics#209]
Test device: Macbook Pro 2012

Operating System: OS Sierra 10.12.6

Browser: Chrome Version 62.0.3202.89 (64-bit)

Problem description: The query parameter ?showDebugAreas is not working. When the page is loading, the status bar will fill to a point and then stop.
Steps to reproduce: 
Go to this link:
https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en.html?showDebugAreas
phetsims/QA#64
Screenshots:
![phetshowdebugbroken](https://user-images.githubusercontent.com/31217926/32568719-52039158-c47c-11e7-85c1-2776263e3d36.jpeg)

URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en.html?showDebugAreas

**Comment by jonathanolson** [comment]
Should be fixed with https://github.com/phetsims/capacitor-lab-basics/commit/1b993236627bc8461b841330bb50ac36dea2734a in master, can you verify?

**Comment by CWilson4960** [comment]
Verified. Thank you!
