### ISSUE TITLE
Strings are following bad conventions and using sloppy concatenation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#210]
- [x] screen name string keys should follow the convention of `"screen.{{screenName}}"` eg. `screen.lightBulb`. Currently they are using:
```js
"lightBulb.title": {
    "value": "Light Bulb"
  }
```
- [x] should use the new pattern format of:
```js
"valueAndUnitsPattern": { // or some other key
    "value": "{{value}} {{units}}"
  }
```
instead of
```js
"pattern.0value.1units": {
    "value": "{0} {1}"
  }
```
- [x] units.millimeters needs to not have a space in it for white space - `"value": " mm"`, ewwww!
- [x] since this is a thing...: 
```js
this.valueNode = new DragHandleValueNode( plateAreaString, millimetersSquared, unitsMillimetersString + '<sup>' + 2 + '</sup>' );
```
..it's clear that we need to have two string keys: 

```js
"units.millimeters": {
    "value": "mm" // I got rid of that ugly space!
  },
"units.millimetersSquared": {
    "value": "mm<sup>2</sup>"
  }
```
...and can do away with the concatenation of the superscript in that line of code.

- [x] eField key should be electricField
- [x] plateCharge key should be topPlateCharge
- [ ] anything else @jonathanolson finds (how many times has this sim been code reviewed? This sim would have been published like this if I didn't think to check the strings file.)

For phetsims/QA/issues/64.

**Comment by pixelzoom** [comment]
Re the item "should use the new pattern format of ..."  

`StringUtils.format` and numbered placeholders are deprecated, not to be used in new (unpublished) sims.  Use `StringUtils.fillIn` with named placeholders.

**Comment by jonathanolson** [comment]
Should be fixed on master and the release branch. @phet-steele can you confirm?

**Comment by phet-steele** [comment]
Looks nice @jonathanolson, thanks. Only thing left to recommend is to re-alphabetize the file? Up to you.

**Comment by pixelzoom** [comment]
@phet-steele said:
> Only thing left to recommend is to re-alphabetize the file? Up to you.

If you're referring to capacitor-lab-basics-strings_en.json ... PhET currently has no requirement to alphabetize the file. And (in general) the order of fields in JSON is not significant.
