### ISSUE TITLE
Voltmeter should have a reading while in the toolbox

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#211]
@arouinfar has noticed that the voltmeter has no value when in its toolbox (it's just a blank white space). For consistency with other sims, it should have the "? V" reading while in the toolbox. @jonathanolson is that easy?

This begs the question though, can the reading of "? V" be replaced with just "?" (at all times, even in the play area)? Not as important, but it would be consistent with CCK in that way.

For phetsims/QA/issues/64

**Comment by arouinfar** [comment]
I would prefer the reading to be "?" without the units, for consistency with CCK. In general, tools do not display the units without a reading. We could have a broader discussion of "-" vs. "?" but it seems like the behaviors of these tools (with the exception of Projectile Motion) were inherited from the legacy version.


<img src="https://user-images.githubusercontent.com/8419308/32623553-ca7f54f6-c543-11e7-839a-edc5c8773c6b.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/32623724-5382d4bc-c544-11e7-968e-031f86ff2a83.png" width=300>
<img src="https://user-images.githubusercontent.com/8419308/32623565-d811402a-c543-11e7-8dc5-7814b54f645b.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/32623598-f6eaf716-c543-11e7-8ac3-c1531eaf30ba.png" width=300>

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by arouinfar** [comment]
Looks great @jonathanolson!
