### ISSUE TITLE
Switch drag does not end in LoL harness

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#212]
Running a screen in the LoL harness, press "Pause in 5 seconds". Start dragging the switch and don't release until after the pause, then click resume. You are still controlling the switch. This is inconsistent with desired LoL behaviour, and is inconsistent with other drag events in this sim (ie dragging the voltmeter is correctly interrupted when paused).

Seen on macOS 10.13.1 Chrome. For phetsims/QA/issues/64.

URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en.html
Version: 1.5.0-rc.1 2017-11-08 00:09:49 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"63a66772","branch":"HEAD"},"babel":{"sha":"483be533","branch":"master"},"brand":{"sha":"53cf227b","branch":"HEAD"},"capacitor-lab-basics":{"sha":"fc8bbb18","branch":"HEAD"},"chipper":{"sha":"05dcc77d","branch":"HEAD"},"dot":{"sha":"4a1ddd12","branch":"HEAD"},"joist":{"sha":"58528a77","branch":"HEAD"},"kite":{"sha":"e4c0b773","branch":"HEAD"},"phet-core":{"sha":"ad21faf3","branch":"HEAD"},"phetcommon":{"sha":"d957aefc","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"e4328b73","branch":"HEAD"},"scenery-phet":{"sha":"70e077d6","branch":"HEAD"},"sherpa":{"sha":"5079b265","branch":"HEAD"},"sun":{"sha":"432da6da","branch":"HEAD"},"tandem":{"sha":"e53e93b6","branch":"HEAD"},"twixt":{"sha":"13905577","branch":"HEAD"}}

**Comment by jonathanolson** [comment]
@phet-steele, can you retest in master (with the Scenery/Joist changes I made above) to see if this now behaves as expected?

I'll want to include the Scenery changes in a branch if so (the Joist changes is just removing an unnecessary duplication).

Leave this issue open until branches are handled.

**Comment by phet-steele** [comment]
This looks ready for RC testing, it works much better on master now.

**Comment by phet-steele** [comment]
Working well in rc.
