### ISSUE TITLE
[iPad] Can drag two items at the same time

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/capacitor-lab-basics#214]
For phetsims/QA#64
Test device: Tycho

Operating System: iOS 9.3.5

Browser: Safari

Problem description: By dragging the switch and then moving your finger without lifting it over another draggable object like the battery slider, the voltmeter, or one of its probes, you will be controlling both at the same time. This only works when you begin by dragging the switch first, not the other way around. Also, this does not happen with the Separation or Plate Area arrows. 

Screenshots:
![clb2](https://user-images.githubusercontent.com/11947677/32674543-f3b4d29c-c610-11e7-84bb-2edeaf99729f.gif)

Troubleshooting information (do not edit):
Name: ‪Capacitor Lab: Basics‬
URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en.html
Version: 1.5.0-rc.1 2017-11-08 00:09:49 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1
Language: en-us
Window: 980x642
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"63a66772","branch":"HEAD"},"babel":{"sha":"483be533","branch":"master"},"brand":{"sha":"53cf227b","branch":"HEAD"},"capacitor-lab-basics":{"sha":"fc8bbb18","branch":"HEAD"},"chipper":{"sha":"05dcc77d","branch":"HEAD"},"dot":{"sha":"4a1ddd12","branch":"HEAD"},"joist":{"sha":"58528a77","branch":"HEAD"},"kite":{"sha":"e4c0b773","branch":"HEAD"},"phet-core":{"sha":"ad21faf3","branch":"HEAD"},"phetcommon":{"sha":"d957aefc","branch":"HEAD"},"query-string-machine":{"sha":"c74e454e","branch":"HEAD"},"scenery":{"sha":"e4328b73","branch":"HEAD"},"scenery-phet":{"sha":"70e077d6","branch":"HEAD"},"sherpa":{"sha":"5079b265","branch":"HEAD"},"sun":{"sha":"432da6da","branch":"HEAD"},"tandem":{"sha":"e53e93b6","branch":"HEAD"},"twixt":{"sha":"13905577","branch":"HEAD"}}

**Comment by jonathanolson** [comment]
Applied a fix to this, can you test?

Don't close, will plan to leave open to create the Scenery branch for this.

**Comment by brroberts1231** [comment]
Tested on iPad 2, this is fixed in master

**Comment by jonathanolson** [comment]
Thanks, will handle the branch in Scenery for this.

**Comment by jonathanolson** [comment]
Included Scenery patch in release branch. Will leave open to ensure this is fixed for next RC.

**Comment by phet-steele** [comment]
Good to go!

**Comment by phet-steele** [comment]
This is occurring again in https://bayes.colorado.edu/dev/html/capacitor-lab-basics/1.7.0-dev.4/phet/capacitor-lab-basics_en_phet.html. This version was recently built off master, so something reintroduced this.

It's somewhat different than the original steps:

- Start by dragging the thumb on the voltage slider.
- Drag your finger over to a plate separation handle and you will grab that also.

**Comment by jonathanolson** [comment]
Assigning for the dev meeting, as I've added an option to SimpleDragHandler to support handling this, but there are some considerations I'd like to discuss during the meeting.

**Comment by pixelzoom** [comment]
This option should be used with SimpleDragHandler in sims that use both SimpleDragHandler and DragListener, so that they play nice together.

**Comment by jonathanolson** [comment]
I'll need to do additional testing to figure out the most common case for this, and will hopefully figure it out while looking into DragListener improvement.

**Comment by samreid** [comment]
We decided we'll remove this from dev meeting, @jonathanolson will work on it and will raise it again if he runs into questions.

**Comment by KatieWoe** [comment]
dev.7 This can happen with the voltmeter probes and the arrows that change the capacitor size.
![stillhere](https://user-images.githubusercontent.com/41024075/55982617-86cc7580-5c56-11e9-8605-f3b6ae9ec63f.gif)

**Comment by KatieWoe** [comment]
While testing on iPad I noticed that https://github.com/phetsims/capacitor-lab-basics/issues/214#issuecomment-482246132 is much more noticeable and likely to interfere.  This is because, if you are trying to drag the probe to a wire or a capacitor, there is less room and you are very likely to move over one of those arrows.

**Comment by Denz1994** [comment]
`allowTouchSnag` has been set to `false` for both separation and area arrow handlers. @KatieWoe Could you use a touch device to test if this is fixed? Please use this [dev link](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-dev.8/phet/capacitor-lab-basics_en_phet.html).

Does this also an issue with the circuit switches?

**Comment by KatieWoe** [comment]
Looks good on Win 10 and iOS 12.  Doesn't seem to have any problems with the switches.

**Comment by Denz1994** [comment]
Good to know. Closing this issue.
