### ISSUE TITLE
Assertion failed: mismatched messageIndex, possible start/end mismatch

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#216]

**Comment by samreid** [comment]
This appears to be the only problem on bayes at the moment aside from https://github.com/phetsims/phet-io-wrappers/issues/37, so I'll take a look at it next.

**Comment by samreid** [comment]
You can reproduce this problem by launching http://localhost/capacitor-lab-basics/capacitor-lab-basics_en.html?brand=phet-io&phetioLog=lines&phetioStandalone&ea&screens=1 and clicking on the voltmeter

**Comment by samreid** [comment]
The upstream error (which is commented out) is `cannot start event while event is in progress`.  It is going through DynamicProperty.onSelfChange:

```js
    /**
     * Listener added to ourself when we are bidirectional
     * @private
     *
     * @param {*} value
     */
    onSelfChange: function( value ) {
      if ( this.valuePropertyProperty.value !== null ) {
        this.derive( this.valuePropertyProperty.value ).value = this.inverseMap( value );
      }
    },
```

I wonder if DynamicProperty requires re-entrant changes?  @jonathanolson can you help?

**Comment by samreid** [comment]
Proposed fix is above, and fuzzing and linting are working nicely.  @jonathanolson can you please review?

**Comment by jonathanolson** [comment]
Looks good to me, thanks!
