### ISSUE TITLE
When clicking on the voltmeter, there is no user message preceding the voltmeterVisible property

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#221]
See #218

**Comment by samreid** [comment]
One way to address this would be to add a tandem option to addForwardingListener, then bracket phetioEvents.start/end around the calls.

**Comment by samreid** [comment]
Here's what that part of the data stream looks like at the moment:

![image](https://user-images.githubusercontent.com/679486/34793009-2b424354-f607-11e7-96f4-88b1d578e633.png)

Would it help to have a toolbox event preceding this?  Should there be other changes to the event stream in this context?  It seems a good question for a PhET-iO design meeting.

**Comment by samreid** [comment]
@phet-steele recommended this for next dev test.

**Comment by samreid** [comment]
Fixed, at least good enough until we have our PhET-iO design.

**Comment by samreid** [comment]
Reopened for testing.

**Comment by phet-steele** [comment]
Looks okay in https://phet-io.colorado.edu/sims/capacitor-lab-basics/1.6.4/capacitor-lab-basics_all_phet-io.html?production&phetioStandalone&phetioLog=lines.



> Fixed, at least good enough until we have our PhET-iO design.

Maybe I'll keep this open until then?

**Comment by KatieWoe** [comment]
From SR on Slack:
>To me it looks like it can be closed.  If we make a new version, we will test the data stream at the time.  It seems the request was completed.

Closing
