### ISSUE TITLE
Add Top Plate Charge and Stored Energy graphs to Capacitance screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#225]
@jonathanolson can you update the Bar Graph option on Capacitance so that it is identical to the Bar Graphs option on Light Bulb? The default configuration would be the same on both screens.

![image](https://user-images.githubusercontent.com/8419308/35356483-c8a315cc-010d-11e8-93a0-39d0576f2c7b.png)

In pilot interviews Tanja observed that students find the light bulb very engaging and spend a lot of time interacting with it. This, of course, is not necessarily a bad thing, but it may distract some learners from interacting with the capacitor while it is disconnected. Learning goals related to stored energy and what happens as the capacitance is changed (while disconnected) could be better supported in an environment without the light bulb.

Originally, the motivation for leaving top plate charge and stored energy off of the Capacitance screen was so that the sim would be more accessible to younger learners. However, I do not think these graphs would do any harm to or disenfranchise younger students, particularly because they would be off by default. I also like the added flexibility that their availability would provide.

Given that Tanja is still in the pilot testing stage, it would be nice if this change could be made sooner rather than later, so I'm marking this as high priority.

**Comment by jonathanolson** [comment]
Should be implemented. Can you check master?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson! Can you push a new dev version for Tanja?

**Comment by jonathanolson** [comment]
Available here: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.7.0-dev.1/phet/capacitor-lab-basics_en_phet.html

**Comment by arouinfar** [comment]
@jonathanolson I just realized the checkbox on the Capacitance screen still reads "Bar Graph", but it should be made plural.

**Comment by samreid** [comment]
Not sure if I picked up these changes for the RC, @jonathanolson can you take a look?

https://github.com/phetsims/QA/issues/86

**Comment by kathy-phet** [comment]
@samreid - We changed our mind re which screen to use since students were getting too distracted by the lightbulb. So we will use screens=1, instead, with this addition.

**Comment by samreid** [comment]
As far as I can tell, it looks like this fix made it into 1.6.1 aside from the string pluralization.

**Comment by jonathanolson** [comment]
Just checked, this is in 1.6.1.

**Comment by jonathanolson** [comment]
> @jonathanolson I just realized the checkbox on the Capacitance screen still reads "Bar Graph", but it should be made plural. Can you fix the string and republish?

Will do, I'll need to coordinate with @samreid for publishing.

**Comment by phet-steele** [comment]
This is all working.

**Comment by arouinfar** [comment]
Reopening with `status:fixed-awaiting-deploy` for #237.

**Comment by arouinfar** [comment]
Not sure when it happened, but this behavior is present in latest. Closing.
