### ISSUE TITLE
Change battery slider to have snap-to behavior at 0.05 jumps? 

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/capacitor-lab-basics#227]
@arouinfar - Comparison of doubling/halving is challenging with the voltage slider right now because it does not "snap to" nice values. What do you think of making them 0.05 jumps reproducible? Currently jumps seem to be around 0.03, so you would have close to as much flexibility in exact numbers. 

Note that voltage readout would need to stay 3 decimal places because changing area and separation can change voltage too.

**Comment by kathy-phet** [comment]
@jonathanolson - How invasive would the proposed change be? (It would be great for the study if Amy agrees and it is small enough that it can happen today and republish).

**Comment by arouinfar** [comment]
@kathy-phet I think 0.05 V jumps would be great, but I we'll still need to keep the `BATTERY_VOLTAGE_SNAP_TO_ZERO_THRESHOLD` at 0.150 V due to the behavior at small voltages (see #138).

**Comment by kathy-phet** [comment]
OK - makes sense. I will touch base with JO.

**Comment by phet-steele** [comment]
This is working in 1.6.4 phet-io. Will keep open to spot check in phet brand

**Comment by DianaTavares** [comment]
Working well when testing with [https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.6-rc.1/phet/capacitor-lab-basics_all_phet.html], closing

**Comment by arouinfar** [comment]
Reopening with `status:fixed-awaiting-deploy` for #237.

**Comment by arouinfar** [comment]
Not sure when it happened, but this behavior is present in latest. Closing.
