### ISSUE TITLE
Current arrows showing on both sides of the circuit

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#228]
Using 1.6.2 phet-io

1. Lightbulb screen.
2. Charge the plate, then connect to the light bulb.
3. As the plate is discharging (while current arrows are visible), press Reset All.
4. Note the arrows don't disappear right away. But more importantly, charging the plate now shows current arrows on the light bulb circuit even when disconnected.

<img width="903" alt="screen shot 2018-01-29 at 11 18 29 am" src="https://user-images.githubusercontent.com/5863899/35526873-2afa0830-04e6-11e8-9950-fdad47b8556b.png">

Seen on macOS 10.13.2 Chrome. For phetsims/QA/issues/86.

**Comment by jonathanolson** [comment]
Both issues confirmed.

The arrows not disappearing right away seems on purpose (based on the code, and this code comment):

> When current stops flowing, the node fades out over a period of time.

**Comment by phet-steele** [comment]
@jonathanolson looks like this new problem from your commit is ONLY in the Lightbulb screen:

Charge the plates and BEFORE the current arrows disappear, quickly disconnect then reconnect the plates from the battery. If done correctly, the current arrows will stick around and not fade away.

**Comment by phet-steele** [comment]
Fixed.
