### ISSUE TITLE
Probe targets don't update on Reset All when invisible

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#229]
@samreid @kathy-phet I'm not sure how we want this to behave, so I'm posing this as a question.

Here is the usual scenario:

1. The user places a probe somewhere and the event stream reports a probe target.
2. The user presses Reset All. Three things happen in the event stream:
- The voltmeter is made invisible (i.e. it's "in" the toolbox).
- The probe locations update to be default.
- The probe targets update to be default ("NONE").

Here is the questionable scenario:

1. The user places a probe somewhere and the event stream reports a probe target.
2. BEFORE Reset All, the user places the voltmeter back into the toolbox.
3. The user presses Reset All. One thing happens in the event stream:
- The probe locations update to be default.

Note how the "probe targets update to default ("NONE")" is not present. This is because they are not updated when invisible, for performance. So after this step, the state data still reports that probes have a non-NONE target even though the probe are (invisibly) not over anything.

However, this is is self-correcting. Once a user takes the voltmeter back out of the toolbox, probe targets are updated to be correct. So, are we okay with this momentary out-of-sync data? You'd really only ever notice in the event stream.

For phetsims/QA/issues/86.

**Comment by kathy-phet** [comment]
What is the behavior if the user places the voltmeter into the toolbox. Do the probe targets ever update? E.g. would a researcher know that the votmeter is not actually out?

**Comment by phet-steele** [comment]
> What is the behavior if the user places the voltmeter into the toolbox. Do the probe targets ever update? E.g. would a researcher know that the votmeter is not actually out?

Yes there is a `voltmeterVisibleProperty` that changes to false when placed into the toolbox.

**Comment by samreid** [comment]
Here's the code that looks like it is updating the probe targets only when they are visible.

```js
    /**
     * Update the value of the meter. Called when many different properties change.
     */
    var updateValue = function() {
      if ( self.visibleProperty.value ) {
        var probesTouching = self.probesAreTouching();
        self.positiveProbeTargetProperty.value = probesTouching ? ProbeTarget.OTHER_PROBE : self.circuit.getProbeTarget( self.shapeCreator.getPositiveProbeTipShape() );
        self.negativeProbeTargetProperty.value = probesTouching ? ProbeTarget.OTHER_PROBE : self.circuit.getProbeTarget( self.shapeCreator.getNegativeProbeTipShape() );
        self.measuredVoltageProperty.value = self.computeValue();
      }
      else {
        self.measuredVoltageProperty.value = null;
      }
    };
    updateValue();
```

@jonathanolson can you look into this?

**Comment by samreid** [comment]
Resetting the probeTargetProperties on reset all may be the correct fix.

**Comment by jonathanolson** [comment]
Resetting on reset-all. Can you verify?

**Comment by phet-steele** [comment]
Verified in master.

**Comment by jonathanolson** [comment]
Cherry-picked to 1.6 branch.

**Comment by phet-steele** [comment]
This passed testing in https://github.com/phetsims/QA/issues/86.
