### ISSUE TITLE
branch: accessible-instance

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#23]
We are going to be working on resolving buggy behavior in this simulation and getting it to a state where it can be outfitted for PhET-iO.  Because of this, we are storing accessibility progress in the accessible-instance branch and continuing to work on code clean up in master.

**Comment by jonathanolson** [comment]
Instrumentation issue was closed. Does this code need to be moved to master, or what additional work is needed?

**Comment by jessegreenberg** [comment]
This code should not be moved to master.  The accessibility features and implementations need to be redone after what we have learned in the latest prototypes.  But I would like to keep it around for reference for when we begin working on accessibility in this sim again.

**Comment by zepumph** [comment]
@jessegreenberg can we delete this branch and close this issue?

**Comment by jessegreenberg** [comment]
Yep, branch deleted.
