### ISSUE TITLE
Performance issues with accessibility

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#24]
When accessible content is active ('?accessibility' in use), the sim performance is reduced when the capacitor is discharging.  Without the query parameter, the discharging capacitor performs just fine.

**Comment by jessegreenberg** [comment]
Removing assignment until we begin to work on this sim again for accessibility.

**Comment by zepumph** [comment]
I would say that performance of accessibility features will be handled as needed. Closing
