### ISSUE TITLE
Current state of PhET-iO in this simulation

### ISSUE THREAD

**Issue by zepumph** [phetsims/capacitor-lab-basics#241]
@Denz1994 there have been a few phet-io bugs that I've noticed while work has continued for this repo. This is totally reasonable, as there probably hasn't been an expectation for you to be working on the phet-io as you go. I'm wondering if we are keeping up on PhET-iO for this repo, or if we will catch up with it later. If it is the latter, then we may want to remove this sim from phet-io testing/building.

@ariel-phet can you specify the priority of PhET-iO in this repo. IMO it may not be too much work to maintain runnability of this sim in phet-io mode, I would rather have the upfront cost done, than to have to go back and fix potentially menial issues. I would say it is a bit of a challenge in terms of priority, because @samreid and @zepumph have limited time to support these efforts, but spending time supporting @Denz1994 now would be overall the most efficient way to go about maintaining phet-io for this sim.

Here are a few examples that I have seen recently:
* https://github.com/phetsims/capacitor-lab-basics/issues/240
* Tandem registration error because of copy paste without changing tandem names:
```

    // @public {Property.<boolean>}
    this.currentVisibleProperty = new BooleanProperty( true, {
      tandem: tandem.createTandem( 'currentVisibleProperty' )
    } );

    // @public {Property.<boolean>}
    this.currentOrientation = new NumberProperty( 0, {
      tandem: tandem.createTandem( 'currentVisibleProperty' )
    } );

    // @public {Property.<Color>}
    this.arrowColorProperty = new Property( new Color( 83, 200, 236 ), {
      tandem: tandem.createTandem( 'currentVisibleProperty' )
    } );
```
* New type `DraggableTimerNode` uses common code `TimerNode` which isn't instrumented yet.

Tagging @samreid in case he has opinions. @ariel-phet please comment on the best way to proceed.

**Comment by samreid** [comment]
Everything mentioned above sounds great!

**Comment by zepumph** [comment]
I agree with @samreid.

@Denz1994 please use the following links (but for your local server) to tests changes for phet-io:
* http://localhost/phet-io-wrappers/phet-io-wrappers-tests.html?ea&sim=capacitor-lab-basics
* http://localhost/aqua/test-server/test-sims.html?ea&audioVolume=0&testDuration=10000&testConcurrentBuilds=4&brand=phet-io&fuzzMouse&phetioStandalone&testSims=capacitor-lab-basics

and if there are any issues that come up that you want to discuss, please make an issue and potentially we can meet up about them. 

Thanks!

@Denz1994 please close if all sounds good here.

**Comment by Denz1994** [comment]
Thanks for the clarification. Closing this issue.

**Comment by samreid** [comment]
@KatieWoe pointed out that Bayes CT is still failing.  I addressed one issue today, but there are downstream issues.

**Comment by samreid** [comment]
Some CT issues have been addressed, another issue noted in https://github.com/phetsims/scenery/issues/858, we can reopen this issue or another issue if there are still problems after https://github.com/phetsims/scenery/issues/858 has been addressed.
