### ISSUE TITLE
Test TimerNode to make sure it still works properly in Capacitor Lab: Basics

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#244]
From https://github.com/phetsims/scenery-phet/issues/372#issuecomment-421099482 and also related to #234.  The TimerNode has recently been updated to support units, and will require testing to make sure it still works properly in Capacitor Lab: Basics.

Also assigning @Denz1994 since I saw he had been working in #234

**Comment by Denz1994** [comment]
After testing with DraggableTimerNode, things work well in the sim. The units option seems flexible enough to handle long strings and as noted in the documentation does change the format of the TimerReadout.

**Comment by Denz1994** [comment]
The elongated `TimerNode` is shown above only appears if there is a unique `maxValue` and `unitsNode` option passed. If only one of the options is passed at initialization, then the `TimerNode` doesn't widen.

The behavior isn't consistent and either the timer should widen or not, but currently, it does both depending on the options passed.

**Comment by samreid** [comment]
> This may be out of the scope of this issue, but it does look a bit wierd that the timerNode remains that large despite having a value with significantly less digits. 

I believe this design is so that the TimerNode can accommodate the largest string without any text scaling and without resizing the text box.

> I've noticed that the timer readout uses scientific notation once the value has 22 digits. This seems pretty high for most uses cases and it may be better to start using scientific nototation after 7 digits?

It seems unlikely that we would want to automatically transition from non-exponential notation to exponential notation in a timer.  Should we throw an exception if maxValue is greater than or equal to 1E+21 (which is the JavaScript default according to http://2ality.com/2012/03/displaying-numbers.html)?

> The elongated `TimerNode` is shown above only appears if there is a unique `maxValue` and `unitsNode` option passed. If only one of the options is passed at initialization, then the `TimerNode` doesn't widen.
> The behavior isn't consistent and either the timer should widen or not, but currently, it does both depending on the options passed.

The timer uses the maxValue and the bounds of the unitsNode to determine the size of the text container, see https://github.com/phetsims/scenery-phet/blob/5ccc58d1ed303b76f0fd557473e78300bbfd8ddb/js/TimerReadoutNode.js#L90-L91.  Perhaps I'm not understanding the inconsistency, can you please elaborate and provide an example?

**Comment by Denz1994** [comment]
If the intent of design is to avoid box resizing then, that paradigm should be followed.

> Should we throw an exception if maxValue is greater than or equal to 1E+21?
An assertion sounds like suitable addition in this case. It wasn't clear to me why at 22 digits scientific notation is used, but the link you provided explains it well ("Displaying Decimal Numbers" section).

> Perhaps I'm not understanding the inconsistency?
The documentation you pointed out is clear that the maxValue is responsible for the panel size. This is less of an inconsitency and more of an oversight in reviewing documentation on my end. Thanks for the clarification.

Re-assigning to @samreid.

**Comment by Denz1994** [comment]
Looks great. Thanks @samreid.
