### ISSUE TITLE
Inconsistent Screen Icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#246]
The screen icons now have different background colors. 
![image](https://user-images.githubusercontent.com/8419308/45774333-e9521b80-bc09-11e8-964b-72da9212035d.png)
![image](https://user-images.githubusercontent.com/8419308/45774349-efe09300-bc09-11e8-909f-2f93afab095e.png)

I think the issue is that one screen icon is code-generated (Light Bulb) and one is an image (Capacitance), which seems odd as they are similarly simple setups. Would it be possible to convert Capacitance into a code-generated icon @Denz1994? The default configuration of the capacitor would work nicely.

If that's not feasible, here are updated assets:
[capacitance_screen_icon.png](https://user-images.githubusercontent.com/8419308/45774640-b9efde80-bc0a-11e8-9d0a-3870e4c47da1.png)
<a href="https://drive.google.com/file/d/1xnp26VSnpJvnWr9DY2SF8-k-VrZhtA8H/view">capacitance_screen_icon.ai</a>

**Comment by Denz1994** [comment]
The screen icons have been updated. Please review in master @arouinfar.

**Comment by arouinfar** [comment]
Looks great! Thanks @Denz1994

**Comment by KatieWoe** [comment]
Looks good on all Win 10 platforms.  I'll continue to keep an eye out, but I think this can be considered done.  Dev.7

**Comment by Denz1994** [comment]
Good to know. Closing this one.
