### ISSUE TITLE
Update Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#247]
For #237, we will need to update the screenshots, as many visual changes have been made to the sim. Here are the current screenshots:

* <a href="https://github.com/phetsims/capacitor-lab-basics/blob/master/assets/capacitor-lab-basics-screenshot.png">capacitor-lab-basics-screenshot.png</a>
* <a href="https://github.com/phetsims/capacitor-lab-basics/blob/master/assets/capacitor-lab-basics-screenshot-alt1.png">capacitor-lab-basics-screenshot-alt1.png</a>
* <a href="https://github.com/phetsims/capacitor-lab-basics/blob/master/assets/capacitor-lab-basics-screenshot-alt2.png">capacitor-lab-basics-screenshot-alt2.png</a>

@KatieWoe when this sim goes into rc, can you retake these screenshots? For alt2, please display only the Capacitance bar graph (leave the other two unchecked). 

Marking as `on-hold` for now, but assigning @KatieWoe so she's aware. Feel free to unassign yourself until this issue becomes relevant.

**Comment by KatieWoe** [comment]
This sim is now in RC (https://github.com/phetsims/QA/issues/315), so removing on-hold status.  However, I will wait until next rc as https://github.com/phetsims/capacitor-lab-basics/issues/259 may make some of the screenshots more difficult.

**Comment by KatieWoe** [comment]
Here are the screenshots.  @arouinfar once you sign off I'll commit them to master and 1.7

**Comment by KatieWoe** [comment]
![capacitor-lab-basics-screenshot](https://user-images.githubusercontent.com/41024075/58274661-8abcde80-7d50-11e9-8a87-c43078a2ad91.png)
![capacitor-lab-basics-screenshot-alt1](https://user-images.githubusercontent.com/41024075/58274662-8abcde80-7d50-11e9-8534-b865ed737b91.png)
![capactor-lab-basics-screenshot-alt2](https://user-images.githubusercontent.com/41024075/58274663-8abcde80-7d50-11e9-93c7-d4d220d83809.png)

**Comment by arouinfar** [comment]
Looks great @KatieWoe, please go ahead and commit the screenshots.

**Comment by KatieWoe** [comment]
Should be done in above commits
