### ISSUE TITLE
Capacitor Lab Basics - PhET-iO Design and Publication

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#249]
This sim was instrumented for PhET-iO using the "instrument everything" approach.  When the time is right, we should have an intentional design and re-implementation process.

**Comment by zepumph** [comment]
A client asked for this sim to be republished off of master recently. It could be nice to do as much of this as possible (priority/time permitting) before a republication.

**Comment by zepumph** [comment]
In the above commits I made some cleanup. There is no longer an instrumented timerNode in the first screen, the wires were uninstrumented, and some tandems were rearanged to make more sense.

When further work is done on this:
- [ ] RadioButtonGroup needs to support linked element
- [ ] Do we need to instrument color Properties, like for example model.arrowColorProperty
* likely more to come!

**Comment by arouinfar** [comment]
This issue is very stale, let's close it. We can open new issues to track publication, update PhET-iO design, etc. when it becomes a priority.
