### ISSUE TITLE
Should there be a voltage reading

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#254]
For https://github.com/phetsims/QA/issues/306.  When one voltage probe is on a disconnected plate and the other is on a wire on the battery, the reading is ``` ? ``` but this seems odd to me.  Shouldn't there be a reading since there is a difference in voltage?  Or am I misunderstanding?

**Comment by KatieWoe** [comment]
![novolts](https://user-images.githubusercontent.com/41024075/55998404-4a5f4080-5c7b-11e9-8e2d-287385f0205a.png)

**Comment by phet-steele** [comment]
Voltmeters will show the potential difference in a _complete circuit_. What you are showing is not a complete circuit. A "?" is expected.
