### ISSUE TITLE
Swipe to pick up wire

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#255]
For https://github.com/phetsims/QA/issues/306.  I noted that the bit of wire you move to connect/disconnect different parts of the circuit doesn't have swipe to pick up.  But the touch areas are pretty good sized.  Since we are looking at https://github.com/phetsims/QA/issues/295, I thought it might be useful to look at.

**Comment by phet-steele** [comment]
@KatieWoe this feature (swipe to pick up) is called `touchSnag`. Please see #130 for why `touchSnag` was disabled, mostly starting at https://github.com/phetsims/capacitor-lab-basics/issues/130#issuecomment-251751139. @arouinfar be aware what you would be reintroducing if you are looking at this for https://github.com/phetsims/QA/issues/295. I don't think it's a worthwhile trade-off to revert all the time spent in #130.

**Comment by KatieWoe** [comment]
Thanks @phet-steele sorry for missing that.

**Comment by arouinfar** [comment]
Thanks for the reminder @phet-steele! Since there isn't any real usability issue on touch, I think we can continue leaving `touchSnag` disabled.
