### ISSUE TITLE
Light Bulb screen does not keep charges when plates change

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#259]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/315 May be connected to https://github.com/phetsims/capacitor-lab-basics/issues/256
Only seems to appear on the light bulb screen.  Not in published.
When the plates are charged, moving them seems to get rid of those charges
**Steps to reproduce:**
1. Go to the Light Bulb screen
2. Charge the plates.  Make sure the +/- are visible to make this easier
3. Doe not matter if plates remain connected to battery or not.  Do not set it to  discharging on bulb
4. Grab one of the green arrows and change size/distance
5. Discharging on bulb and doing this causes further problems that look like https://github.com/phetsims/capacitor-lab-basics/issues/256 (but without being paused) when capacitors are completely disconected

**Screenshots:**
![nomorecharges](https://user-images.githubusercontent.com/41024075/57333590-79ca6700-70da-11e9-8c74-69e055315dd5.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.1/phet/capacitor-lab-basics_all_phet.html
Version: 1.7.0-rc.1 2019-05-07 18:06:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
I did a bit more digging on step 5 and found that you only need to set the wires to discharge, then move them to the middle position.  Moving the capacitors after this causes the below phenomenon.
![moreandlesscharges](https://user-images.githubusercontent.com/41024075/57335518-17746500-70e0-11e9-88c6-49f82ae8f9eb.gif)

**Comment by etwa4650** [comment]
While replicating this issue on MAC OS 10.12.6 and Firefox, I noticed that when the plates are close together, the number of Charges reduces to some minimum number depending on the Plate Area, rather than disappearing entirely. In this case it reduces to 6 Charges on the top plate with a Plate Area of 210 mm^2.

The charges disappear once the plates are separated, and reappear when they are close again.

 
![Screen Shot 2019-05-08 at 10 05 17 AM](https://user-images.githubusercontent.com/26493147/57390352-5b677880-7179-11e9-9e0c-4b86b6ab02bc.png)

**Comment by Denz1994** [comment]
The discharge needs to only occur when the lightbulb is connected. This logic would work for both screens. https://github.com/phetsims/capacitor-lab-basics/commit/6e2f7d57e826bcae9b5dcbc8082e49f4303e622f should have fixed this but I'll let qa verify.

**Comment by KatieWoe** [comment]
This looks fine as of 1.7.0-rc.2
