### ISSUE TITLE
Timer is grabbed instead of voltmeter

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#260]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/315.  Timer is not in published version, so it doesn't apply.
When trying to grab the voltmeter, a fairly large chunk of the right side grabs the timer instead.
**Steps to reproduce:**
1. Go to the light bulb screen
2. Start trying to grab the voltmeter by its right most probe.
3. Put the timer back
4. Repeat attempts to remove the voltmeter while moving in very slightly each time
5. You should be able to grab the voltmeter at about the right-most point of its read out

**Screenshots:**
![whereamigrab](https://user-images.githubusercontent.com/41024075/57337673-9de07500-70e7-11e9-82c7-5b00b5337fba.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.1/phet/capacitor-lab-basics_all_phet.html
Version: 1.7.0-rc.1 2019-05-07 18:06:40 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Nice find @KatieWoe. I was able to reproduce on latest macOS/Chrome.

@Denz1994 looks like the click/touch areas may need some adjusting. I don't see anything in the toolbox when using `?showPointerAreas`, but I think something like this could work. Click areas would be limited to the physical bounds of the icons in the toolbox, but touch areas could be quite generous.
![image](https://user-images.githubusercontent.com/8419308/57403616-53b6cc80-7197-11e9-9380-a15a9e81dc20.png)

**Comment by Denz1994** [comment]
There was a large overlap of the timerNodeIcon touch/mouse areas. Touch/mouse areas for the timerNodeIcon have been adjusted. This seemed to have resolved the issue but I'll let qa verify.

**Comment by KatieWoe** [comment]
Looks much better on 1.7.-rc.2 Win 10 chrome
