### ISSUE TITLE
Timer can be lost

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#261]
Found on Win 10 firefox and edge so far.  Does not seem to happen chrome, likely due to how chrome handles iframes.  It can also happen in the normal sim by dragging to the bottom.
When dragging the timer outside the bounds of the sim, it can be lost with no way to get it back without resetting the sim.
![losttimer](https://user-images.githubusercontent.com/41024075/57393225-e77c9e80-717f-11e9-910e-656e3ffa7c99.gif)
For https://github.com/phetsims/QA/issues/315

**Comment by lmulhall-phet** [comment]
The timer can also be lost in the vanilla simulation on FF via dragging it down toward the PhET menu.

![issue](https://user-images.githubusercontent.com/31285590/57393810-22330680-7181-11e9-93c5-37a786cef2b4.gif)

**Comment by lmulhall-phet** [comment]
Timer can also be lost on iOS 9.3.5 + Safari by moving it to the right by the checkboxes.

**Comment by lmulhall-phet** [comment]
Timer can be lost in the same way as in https://github.com/phetsims/capacitor-lab-basics/issues/261#issuecomment-490569298 on Chrome OS.

**Comment by Denz1994** [comment]
`DraggableTimerNode.dragbounds` needed to be updated to respect the changing sim bounds. They update in correspondence with the layout bounds which keep the timer in the play area.

**Comment by KatieWoe** [comment]
This is looking good in 1.7.9-rc.2
