### ISSUE TITLE
Long strings overlap with green/yellow arrow

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#262]
For https://github.com/phetsims/QA/issues/315
When strings are long, the string that denotes the sizeof the plates can overlap with the tilted arrow.  This happens on published version as well.  Happens on both screens.
![bittyoverlap](https://user-images.githubusercontent.com/41024075/57396783-6970c580-7188-11e9-8bdd-79db5fb162fe.png)

**Comment by arouinfar** [comment]
@Denz1994 looks like a layout issue to me. The string should not be allowed to overlap the arrow.

**Comment by KatieWoe** [comment]
Looks good 1.7.0-rc.2
