### ISSUE TITLE
Update Credits for 1.7.0

### ISSUE THREAD

**Issue by Denz1994** [phetsims/capacitor-lab-basics#265]
@arouinfar and @KatieWoe could you please verify that the credits are correct in this [version](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.2/phet/capacitor-lab-basics_all_phet.html).

@ariel-phet I'm listed as the responsible dev for this sim, but I wasn't part of the original development team. Should I be added to the credits for 1.7.0? I'm not sure how that process works.

**Comment by ariel-phet** [comment]
@Denz1994 yes, definitely add yourself to the development credits

**Comment by arouinfar** [comment]
Design credits look good to me. @Denz1994 you should definitely add yourself to the dev credits!

**Comment by KatieWoe** [comment]
I should be added (Kathryn Woessner) and Ethan Ward should be added as well.

**Comment by Denz1994** [comment]
Credits have been updated. Thanks for the input everyone. Closing.
