### ISSUE TITLE
Short strings are centered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#266]
For https://github.com/phetsims/QA/issues/321
Found on Win 10 Firefox.  On the lighbulb screen, the checkboxes in the box above the voltmeter and timer are centered with short strings (stringTest=X).  The first screen behaves correctly, and the checkboxes do not move.
![centers](https://user-images.githubusercontent.com/41024075/58285298-b4ceca80-7d69-11e9-9bdf-5ab4b4d3f501.png)

**Comment by KatieWoe** [comment]
Edit: Wrong screenshot

**Comment by arouinfar** [comment]
This issue is reminiscent of https://github.com/phetsims/masses-and-springs-basics/issues/59.

@Denz1994, I would prefer that the checkboxes/radio buttons remain anchored on the left side of the panel, rather than shifting with varying string length.

**Comment by KatieWoe** [comment]
This is what it looks like in published: 
![pub](https://user-images.githubusercontent.com/41024075/58288926-3591c480-7d72-11e9-9aef-7c540ef08f28.png)

**Comment by lmulhall-phet** [comment]
I think the huge gap next to the capacitance bar is due to the centering, so we should check that this gets fixed as well.

**Comment by arouinfar** [comment]
Good observations @KatieWoe @lmulhall-phet. In general, the panel shouldn't ever shrink so the behavior in the published version does indeed seem strange. 

> I think the huge gap next to the capacitance bar is due to the centering, so we should check that this gets fixed as well.

It would be good to confirm that the bar graph is indeed shifting -- it definitely shouldn't be. It's a bit hard for me to tell (without overlapping screenshots) because the graph label alignment could be off too.

**Comment by Denz1994** [comment]
The panel contents with checkboxes have been left aligned. Originally, it was centered, causing the alignment issue above. I'll verify in next RC.

**Comment by phet-steele** [comment]
The panel checkboxes are aligned properly in 1.7.0-rc.5, but @arouinfar do we want these to be aligned any differently?

![image](https://user-images.githubusercontent.com/5863899/96189583-fbdcd300-0efd-11eb-887e-3b1a952df82f.png)

If not, you can close this.

**Comment by arouinfar** [comment]
@phet-steele that panel looks good to me, closing.

**Comment by KatieWoe** [comment]
This is back in https://github.com/phetsims/QA/issues/616

**Comment by jonathanolson** [comment]
Should be fied in master, @KatieWoe can you verify?

**Comment by KatieWoe** [comment]
Putting this in issues to verify on QA board

**Comment by KatieWoe** [comment]
Looks fixed on master
