### ISSUE TITLE
Pointer Area for voltmeter is smaller than actual

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#267]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/321.  Related to https://github.com/phetsims/capacitor-lab-basics/issues/263
The pointer areas for the voltmeter are a bit smaller than the grabbable area.  Minor and like shouldn't block publication per @arouinfar 
**Steps to reproduce:**
1. Use the query parameter showPointerAreas
2. Drag the voltmeter out
3. Grab just outside of the area.  Particularly to the left and right

**Screenshots:**
![bitbigger](https://user-images.githubusercontent.com/41024075/58285758-9fa66b80-7d6a-11e9-8cfd-92f360efd4ab.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.2/phet/capacitor-lab-basics_all_phet.html
Version: 1.7.0-rc.2 2019-05-23 09:21:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
@Denz1994 it looks like the boundaries shown with `?showPointerAreas` are not accurate to the true touch/click areas. Since #263 was deferred, the same can probably be done here, but I'll leave that up to you.

**Comment by Denz1994** [comment]
The mismatched touch/mouse areas are remnants of a proposed solution to #263. Because this doesn't completely solve that issue and that issue has been deferred, I'll retract the code relevant to #263.

**Comment by Denz1994** [comment]
The code that modified the touch/mouse areas has been retracted. I'll post a new rc version to confirm with @arouinfar.

**Comment by Denz1994** [comment]
It was decided that https://github.com/phetsims/capacitor-lab-basics/issues/263 is low-priority and a complete solution to this would require a custom shape to fit along the border of the voltmeterNode. I will close this issue and handle further discussion in #263.
