### ISSUE TITLE
Longer strings near capacitance, plate charge, and energy bars need more space

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/capacitor-lab-basics#268]
For https://github.com/phetsims/QA/issues/321. If you have strings that are just one character longer than the English strings next to the capacitance, top plate charge, and energy bars (not sure what else to call them?) there's no space.

Examples found by @arouinfar:

locale = uk (Ukranian)
![image](https://user-images.githubusercontent.com/31285590/58289538-f8c6cd00-7d73-11e9-8d7b-65b869f5be13.png)

locale = th (Thai)
![image (1)](https://user-images.githubusercontent.com/31285590/58289557-08deac80-7d74-11e9-801a-6ae5bff8ffe4.png)

**Comment by arouinfar** [comment]
Thanks @lmulhall-phet.

@Denz1994 a few suggestions
- [ ] Move value strings 5 px to the left (pink line in screenshot below), but leave `maxWidth` the same. This will ensure there is some padding between the the value string and the bar graph.
- [ ] Increase `maxWidth` of checkbox labels by 15 px (green line in screenshot below). This will still leave a reasonable amount of padding between the checkbox label and the value string (~20 px), but provide a bit more room for i18n.

![image](https://user-images.githubusercontent.com/8419308/58353964-39365180-7e2d-11e9-91ca-596f3d833b63.png)

**Comment by Denz1994** [comment]
Alignments and maxWidth have both been adjusted. Will release a new RC for review.

**Comment by KatieWoe** [comment]
Looks good 1.7.0-rc.3
