### ISSUE TITLE
Inconsistent tool box size when strings are long

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#269]
**Device**
Chadwick
**OS**
ChromeOS
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/321.  Quite minor
On the first screen, the tool box with the voltmeter has the same width no matter how much the box above it grows.  The corresponding toolbox on the second screen grows in width to match the box above it (the images inside do not change).  In the published version both toolboxes started smaller than the box above and did not grow.  It seems behavior would ideally be consistent between screens.
**Steps to Reproduce**
1. Open a sim with no string tests
2. Open another sim with stringTest=long
3. Compare tool box sizes on both screens on both sims

**Screenshots:**
_First Screen:_
![longcap](https://user-images.githubusercontent.com/41024075/58348707-9c6cb780-7e1e-11e9-82fd-6566d5e3c61a.png)
![regcap](https://user-images.githubusercontent.com/41024075/58348714-a1316b80-7e1e-11e9-8d9e-6b8609cba13c.png)
_Second Screen:_
![longlight](https://user-images.githubusercontent.com/41024075/58348729-aabad380-7e1e-11e9-8a68-d13f2cb11406.png)
![reglight](https://user-images.githubusercontent.com/41024075/58348733-aee6f100-7e1e-11e9-862f-f2dbddcd6a2d.png)
_Published:_
![pub](https://user-images.githubusercontent.com/41024075/58348743-b4dcd200-7e1e-11e9-9967-272df5a893ef.png)

**Comment by arouinfar** [comment]
Since the toolbox width now matches the panel above it, it seems a bit inconsistent that it only expands on Light Bulb to maintain equal widths. @Denz1994 seems like it should also expand on Capacitance.

While this is a minor issue, I think it would be nice to address since this sim will need to go through another RC cycle, regardless.

**Comment by Denz1994** [comment]
I added an alignGroup for the checkbox panel and the toolbox panel. Both should maintain the same width when adjusted by the string size.

**Comment by KatieWoe** [comment]
Looks good.
