### ISSUE TITLE
CircuitSwitch refactor

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#27]
There is a substantial amount of duplicated code, and the constructor should be rethought. It takes a lot of code to create each switch, and it is not an intuitive API.

**Comment by jessegreenberg** [comment]
Yikes, CapacitanceCircuitSwitch is a copy of CircuitSwitch with about 10 lines removed.  This can definitely be reconsidered so that CapacitanceCircuitSwitch can be deleted.

**Comment by jessegreenberg** [comment]
CapacitanceCircuitSwitch deleted, refactored CircuitSwitch so there is only one switch file.

**Comment by jessegreenberg** [comment]
I think that CircuitSwitche.js is sufficiently refactored that this issue can be closed.
