### ISSUE TITLE
Voltmeter is behind the pause/speed panel

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#270]
**Device**
Dell Laptop
**OS**
Windows 10
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/349 (revisiting)
I noticed that the voltmeter is behind the pause speed panel on the second screen, but the timer is in front of it.
![behindandabove](https://user-images.githubusercontent.com/41024075/60138690-85481f00-9768-11e9-8a4d-24de3f243c5e.png)

**Comment by arouinfar** [comment]
@Denz1994 let's layer both the voltmeter and timer on top of the panel.

**Comment by Denz1994** [comment]
Z-ordering has been changed for the sim controls. It should be checked when we revisit this sim for development.

**Comment by arouinfar** [comment]
@Denz1994 I'm not seeing any z-ordering changes in rc.4
![image](https://user-images.githubusercontent.com/8419308/96056541-15214900-0e44-11eb-808f-000db86623aa.png)

**Comment by Denz1994** [comment]
Right. This commit wasn't cherry-picked into the 1.7 branch. I made a quick commit to include this change. I'll assign this issue for verification in the next RC.

**Comment by phet-steele** [comment]
This fix is present in 1.7.0-rc.5!
