### ISSUE TITLE
Use Stopwatch and StopwatchNode

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#272]
From https://github.com/phetsims/gas-properties/issues/170, DraggableTimerNode and several model properties can be replaced by StopwatchNode and Stopwatch.  I've made these changes in my working copy, this issue is to facilitate review.  After I commit, I'll reassign to the responsible dev for review.

**Comment by samreid** [comment]
@Denz1994 can you please review at your convenience?

**Comment by Denz1994** [comment]
It looks like using `model.Stopwatch` centralized a lot of the model components previously used by draggableTimerNode (now `StopwatchNode`).  This looks a lot cleaner. Thanks for the change @samreid. Closing this one.
