### ISSUE TITLE
Small line off side of battery

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#277]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 14.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/565. This does also happen in published.
When the iPad is in portrait mode and there is no other tab, the battery on both screens has a small graphical oddity in the form of a line coming off the left side of the battery.

**Visuals**
![IMG_0012](https://user-images.githubusercontent.com/41024075/97919841-b994fd80-1d15-11eb-91b1-f2710b3608e7.PNG)

**Comment by Denz1994** [comment]
It would be helpful to know if this oddity persists if the battery is flipped so the positive side is faced downward. To test, set the battery voltage to -1.5v. This may have something to do with the `BATTERY_POSITIVE_TERMINAL_HEIGHT` for `BatterGraphicNode.POSITIVE_UP`.

Labeling this a low-priority, as this should not block a maintenance release for this sim.

**Comment by KatieWoe** [comment]
It does occur if the battery is the other way around.
![IMG_0013](https://user-images.githubusercontent.com/41024075/99573985-08889700-2994-11eb-96f2-406071efa7c0.PNG)

**Comment by arouinfar** [comment]
@Denz1994 this is not a priority for the redeploy. I am fine with deferring or closing as wontfix.

**Comment by Denz1994** [comment]
Closing as a wont-fix.
