### ISSUE TITLE
Current options should be disabled when current is not shown.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#278]
**Test device**
Pauling
**Operating System**
iPadOS 13.7
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/565. Happens on any platform. Option is not available in published.
There is a checkbox to show the current change. Bellow that are options for showing the behavior in terms of electrons or in terms of conventional current. You can switch between these two options even when the higher order checkbox to show the current is off. Other sims (CCK has almost this exact set up as an example, and Acid-Base Solutions has a similar set up with the Molecules/Solvent option) show that, when the higher level option is off the lower level options should be disabled. If this was an intentional change/deviation, feel free to close.

**Visuals**
![disablecurrentoptions](https://user-images.githubusercontent.com/41024075/98173426-57bccb00-1eb0-11eb-884f-c002bde39e1a.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.7.0-rc.5/phet/capacitor-lab-basics_all_phet.html
Version: 1.7.0-rc.5 2020-10-15 20:25:58 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Language: en-US
Window: 1306x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Denz1994** [comment]
Good catch. The radio buttons have been made to be responsive to the current direction visibility. Will post a new rc version for verification.

**Comment by DevonQui** [comment]
The radio buttons are grayed-out when the current direction visibility isn't enabled in the simulation. Closing.
<img width="223" alt="Screen Shot 2020-12-17 at 2 37 19 PM" src="https://user-images.githubusercontent.com/72042459/102546769-6385da80-4075-11eb-9e8f-ab6f75aff056.png">
