### ISSUE TITLE
CircuitConfig constructor

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#28]
- Consider a new pattern for construction and making all of those variables public.
 - Populate with defaults for the intro screen.

**Comment by andrewadare** [comment]
After discussion, we concluded that the current approach of using an options object is best. It allows us to easily create defaults have a simpler call signature.

**Comment by jessegreenberg** [comment]
Considering https://github.com/phetsims/capacitor-lab-basics/issues/28#issuecomment-206521561, I think the only remaining task is to populate with defaults.

**Comment by andrewadare** [comment]
@jessegreenberg, 0c6e2fc3cef0e2ad77d79c1c571898b30ed80294 looks okay in my tests, but let's discuss today before closing.

**Comment by andrewadare** [comment]
We had discussed updating the C.L.B.LightBulbModel ctor by taking defaults. Turns out the first parameter we looked at is the only duplicated parameter. All others have new, non-default values.

Thus, there is nothing left to do.
