### ISSUE TITLE
Plate charge display weirdness?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#282]
In master:

1. Light Bulb (2nd) screen
2. Battery to 1.5V: 
![image](https://user-images.githubusercontent.com/480878/106551408-6b3cf980-64d2-11eb-9828-83cb4dd33f3f.png)
3. Reduce Separation slightly: 
![image](https://user-images.githubusercontent.com/480878/106551429-7859e880-64d2-11eb-9b8b-b9006b46c4f4.png)

It looks like the plate charges disappear visually (and act like they disappear, since moving the switch to the light bulb doesn't discharge). Moving BACK to the battery fixes things.

So... things seem very broken in master. Am I wrong?

**Comment by jonathanolson** [comment]
I believe we were incorrectly adjusting the voltage on the light-bulb screen when it wasn't connected to the light bulb. I believe it should be fixed with the above. @arouinfar can you see how this is working on master?

**Comment by arouinfar** [comment]
@jonathanolson I can't reproduce the original issue in master, so I think this is safe to close.
