### ISSUE TITLE
Current Direction buttons still activated when Current Direction is off

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/capacitor-lab-basics#283]
This is for https://github.com/phetsims/QA/issues/616, seen on Win10.
![caplabbasics](https://user-images.githubusercontent.com/72031637/111511330-3ef0db80-8714-11eb-9043-f7296b369c3a.PNG)
When the "Current Direction" is deselected, you can still click the conventional and electrons current buttons. Should those also be disabled?

**Comment by arouinfar** [comment]
Nice find @brooklynlash!

@jonathanolson this looks like a regression, see https://github.com/phetsims/capacitor-lab-basics/issues/278.

**Comment by jonathanolson** [comment]
Cherry-picked into master, @brooklynlash can you verify this is fixed?

**Comment by brooklynlash** [comment]
Fixed in master! Closing
