### ISSUE TITLE
Snag-to-pick-up grabs multiple objects

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#286]
**Device**
iPad 6th Gen
**OS**
iPadOS 14.4.1
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/616
When using touch to drag many of the objects, passing over other objects picks them up as well. This can be particularly troublesome when you end up picking up multiple parts of the voltmeter, rather than just one.
**Steps to Reproduce**
1. Use snag-to-pick-up to pickup an object, such as a voltmeter probe
2. move finger over another object, such as main voltmeter body

**Visuals**

https://user-images.githubusercontent.com/41024075/112530519-2617a400-8d6c-11eb-890c-faa34961f4c7.MP4

https://user-images.githubusercontent.com/41024075/112530563-32036600-8d6c-11eb-99eb-09f66094385f.MP4

https://user-images.githubusercontent.com/41024075/112530605-421b4580-8d6c-11eb-8a48-46421008b2a2.MP4

**Comment by jonathanolson** [comment]
I believe this is fixed in master, can you verify?

**Comment by KatieWoe** [comment]
Adding this to issues to verify on QA board

**Comment by KatieWoe** [comment]
Looks good on master
