### ISSUE TITLE
Black lines appear while Top Plate Charge and Stored Energy bars go down

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/capacitor-lab-basics#287]
**Test device**
Win 10 Firefox 
**Operating System**
Win 10
**Browser**
Firefox 87.0 64 bit
**Problem description**
Black and grey lines appear when Top Plate Charge and Stored Energy bars are losing charge. I also tested on chrome and I could not reproduce the graphical error
**Steps to reproduce**
1. Check Top Plate Charge and Stored Energy
2. Select slow mode
3. Put battery -1.5v
4. Set separation to 2.0mm
5. Set Plate Area to 400mm
6. Turn on the light
7. While the light is going quickly set separation to 10mm
**Visuals**
![Weird Lines](https://user-images.githubusercontent.com/48224214/114938734-53e48b80-9df4-11eb-9836-fc3a3820b494.JPG)
![Yellow weird black lines](https://user-images.githubusercontent.com/48224214/114938744-5646e580-9df4-11eb-9518-14fc74349f3c.JPG)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Capacitor Lab: Basics‬
URL: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.8.0-dev.6/phet/capacitor-lab-basics_en_phet.html
Version: 1.8.0-dev.6 2021-04-12 21:29:04 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0
Language: en-US
Window: 2048x1038
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by arouinfar** [comment]
I was not able to reproduce this in Firefox/macOS 10.15.7.

**Comment by arouinfar** [comment]
Tagging https://github.com/phetsims/QA/issues/640 so it shows up in the QA issue.

**Comment by jonathanolson** [comment]
I'll look into whether I can add a hidden (invisible) element to do the trick.

**Comment by jonathanolson** [comment]
Added a potential workaround above, can you try out master to see if it's resolved?

**Comment by Matthew-Moore240** [comment]
@jonathanolson It looks good to me. I was not able to replicate it.

**Comment by jonathanolson** [comment]
Thanks!
