### ISSUE TITLE
When should current arrow disappear

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#288]
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 14.4.2
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/640
I noticed that, when you turn off current arrows and turn them back on, the behavior of the sim is a bit different depending on what state the sim is in. This is very minor and may not need to be addressed.
If arrows are already present when turned off, and would be there when turned on, they will show back up if the plates are connected to the battery. If, however, they are on the lightbulb, the arrows won't come back. This is easier to see with pausing.

**Steps to reproduce**
1. Go to the second screen
2. Pause the sim
3. Add charge to the plate and observe the arrows.
4. Turn arrows off
5. Turn arrows on and observe
6. While still paused, switch to lightbulb and observe arrows
7. Turn arrows off
8. Turn arrows on and observe

**Visuals**

https://user-images.githubusercontent.com/41024075/115122004-d85d1880-9f72-11eb-933a-fa7d37bdfd4d.MP4

**Comment by arouinfar** [comment]
Nice find @KatieWoe. 

It basically looks like the current arrows will not reappear on the light bulb side of the circuit if you turn them off and then back on while paused. The arrows will appear again when the model is stepped forward. I think this is a really minor issue so unless there is a nearly effortless solution to this, I'm fine as closing as wontfix @jonathanolson.

**Comment by jonathanolson** [comment]
Looks quite tricky! Closing as wontfix.
