### ISSUE TITLE
Lots of time may elapse when previewing the sim in Studio

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#290]
Discovered during #249 

Steps to reproduce
1. Open the sim in Studio
2. Maximize capacitance (2 mm separation, 400 mm^2 area) to maximize the decay time
3. Charge capacitor to 1.5 V
4. Move switch to the light bulb
5. When the left side of the halo reaches the center of the capacitor, click "Preview Sim". (The exact halo size doesn't seem to be important, but this is a handy visual reference point.)
    <img width="600" alt="Screen Shot 2021-04-29 at 5 11 43 PM" src="https://user-images.githubusercontent.com/8419308/116629320-2af0ea00-a90e-11eb-9dd1-9de43b02dbb0.png">
6. It takes a second or two for the previewed sim to load, but when it does, it seems like time was still elapsing in the model and the halo is now very small. (Because of https://github.com/phetsims/scenery-phet/issues/676 I can't actually confirm that time is elapsing in the sim.)
   <img width="600" alt="Screen Shot 2021-04-29 at 5 11 46 PM" src="https://user-images.githubusercontent.com/8419308/116629412-6b506800-a90e-11eb-91e1-6e98fb49d6fe.png">
7. Switch back to the Studio browser tab and notice that the halo is essentially the same size as as when pressing "Preview Sim".

**Comment by jonathanolson** [comment]
Doesn't look like elapsed time (https://github.com/phetsims/scenery-phet/issues/676 has been addressed it seems). Something else is going on

**Comment by jonathanolson** [comment]
`phet.joist.sim.screens[2].model.circuit.capacitor.plateVoltageProperty.value` is 0.768879966097508 for the in-studio sim, and 0.1281466610162513 for the previewed sim.

**Comment by jonathanolson** [comment]
I believe this should be fixed by the above commit, can you verify?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson!
