### ISSUE TITLE
User suggestion:  vary resistance

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/capacitor-lab-basics#293]
> Any chance you could allow the capacitor lab the option to vary resistance (of the bulb perhaps) and throw a stopclock into the mix in order to allow full simulation of charge/discharge curves etc.

It sounds like the timer will be added in https://github.com/phetsims/capacitor-lab-basics/issues/234.

**Comment by arouinfar** [comment]
@oliver-phet yes, we will be adding a timer in the next release. However, a variable resistance goes beyond the scope of this sim. If the user has deeper goals related to RC circuits, I would recommend that they use CCK: AC instead. There, they can change the capacitance, resistance, initial voltage, and measure the decay with the voltage chart and current chart.

**Comment by oliver-phet** [comment]
Thanks, will reply back to the user!
