### ISSUE TITLE
WireSegment.js cleanup

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#31]
Source file is currently messy.  There should be some refactoring.  We should remove the unused `cleanup()` functions, because our wires are static and do not need to be disposed.  We can probably remove some types that were experimental and are now unused.

**Comment by jessegreenberg** [comment]
```js
    update: function() {
      // TODO: Optimize: update should only be called on segments where optimze is defined
      // This is temporary, and a way to noop for segments where update is not defined
    }
```
should be handled as part of this issue.

**Comment by jessegreenberg** [comment]
I am satisfied with this file and WireSegment usage.  Also added documentation to the file in the above commits.  TODO's have been handled.  Closing.
