### ISSUE TITLE
Overhaul of Wire...To... types

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#32]
The files WireBatteryToCircuitSwitch.js, WireCapacitorToCircuitSwitch.js, and WireLightBulbToCircuitSwitch.js have several problems: 

 - [x] These each assume specific geometry information. This should be provided from a common source, or else explicitly described in each file.
 - [x] Their names are confusing/misleading. Each returns a type, and inherits from Wire. Rename to something like
```
  BatterySwitchWire
  LightBulbSwitchWire
  LightBulbCircuitWire
```
  - [x] Also rename the static constructors for each like
  WireCapacitorToCircuitSwitchBottom -> CapacitorToSwitchBottomWire.
  - [x] There is factorable code in all three types. Consider options for code reuse.
  - [x] There are unused public functions. Go through each file, check for usage, and clean up.

**Comment by andrewadare** [comment]
Now called:

BatteryToSwitchWire.js
CapacitorToSwitchWire.js
LightBulbToSwitchWire.js

**Comment by andrewadare** [comment]
> These each assume specific geometry information. This should be provided from a common source, or else explicitly described in each file.

Today's commits have largely resolved this. The positional/geometry info is now used in a very reasonable way to initialize these objects.

> There is factorable code in all three types. Consider options for code reuse.

The factorable code turned out to be unused code! This has now all been deleted. The remaining single-use public functions were removed; their logic is now implemented directly in the constructors.

**Comment by jessegreenberg** [comment]
These files are looking much cleaner, thanks @andrewadare! Closing this one.
