### ISSUE TITLE
Revisit voltmeter implementation

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#36]
Verify that VoltmeterShapeCreator still works well given that much of the voltmeter image representation has changed (mostly probes)

**Comment by andrewadare** [comment]
The source is simple and pretty clean, and the voltmeter looks okay to me on-screen. 

The only issue apparent to me is a TODO in `getProbeTipShape`. @jessegreenberg, is this one still outstanding, or are you satisfied with the appearance?

**Comment by jessegreenberg** [comment]
I think i was concerned that the shape used to determine probe intersection with the circuit components may no longer be completely correct, but perhaps there is really no issue.  I will take a look and close if there is nothing to do.

**Comment by jessegreenberg** [comment]
It looks like the model shapes for the probe tips are justified too far to the right of the tip on the image, 
![capture](https://cloud.githubusercontent.com/assets/6396244/14959807/70400a22-104e-11e6-8c5d-2d4380594e22.PNG)

**Comment by jessegreenberg** [comment]
There is this TODO in VoltmeterShapeCreator that is likely causing this:

```js
var x = origin.x + width / 2; // TODO: adding the width justifies the shape.  Probably some white space in the images.
```

Now that the assets have been updated, this is probably causing the issue.

**Comment by jessegreenberg** [comment]
Removing that adjustment fixes this:
![capture](https://cloud.githubusercontent.com/assets/6396244/14960010/c0f3118e-104f-11e6-85c4-9c98aa952729.PNG)

But there are still weird things happening with the voltmeter probes, such as the voltage being read when it shouldn't be:
![capture](https://cloud.githubusercontent.com/assets/6396244/14960092/2a966ffa-1050-11e6-9c7e-7a3f7eda08d3.PNG)

**Comment by jessegreenberg** [comment]
I think this issue can be closed, this issue cannot be reproduced with other circuit components or the wires, so I think this is an issue with the capacitor shapes.  The above image is observable on both the lft and right side of the capacitor plate. I will create a new issue to understand why the capacitor model shapes are too wide.
