### ISSUE TITLE
Remove Voltmeter.getUsefulProbeLocations

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#37]
Voltmeter.getUsefulProbeLocations is not documented and is not neatly organized. This was introduced for accessibility and will be removed.

**Comment by andrewadare** [comment]
This is an accessibility-related issue; assigning to @jessegreenberg instead after discussing.

**Comment by jessegreenberg** [comment]
Removed from master, along with some other accessibility code from master branch.  Closing.
