### ISSUE TITLE
Improve upon array indexing pattern in `createWire()`

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#38]
Change the createWire, etc functions, these rely on taking the capacitor and lightbulb from an array
which only makes sense to the developer at the time.

**Comment by jessegreenberg** [comment]
This also applies to referencing the circuit switch nodes in the CircuitNode types.

**Comment by jessegreenberg** [comment]
createWires of ParallelCircuit assumes a single light bulb and capacitor, but ParallelCircuit is intended to handle any number of circuit components.  Fixing this issue will require fully generalizing the createWires function of ParallelCircuit.

**Comment by jessegreenberg** [comment]
Things would be much more simple if capacitors had knowledge of their switches.  Perhaps a cleaner solution would be to have a new type like SwitchedCapacitor that combined a circuit switch and a capacitor.  This would also make the (rather confusing) CircuitSwitchFactory and createCircuitSwitches functions unnecessary.

**Comment by jessegreenberg** [comment]
Went through some significant changes to do this and implement https://github.com/phetsims/capacitor-lab-basics/issues/38#issuecomment-215231533.  The result is much less code and no confusing array references.  ParallelCircuit is also truly generalized now and can handle any number of capacitors.  More cleanup to be done, but the above commit closes this issue.
