### ISSUE TITLE
ConnectionAreaInputListener is poorly named

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#39]
Rename ConnectionAreaInputListener, since this is a node not a listener. Perhaps to ConnectionAreaNode.

**Comment by jessegreenberg** [comment]
Name change and references look good, but while working on #53 I noticed that the constructor and name registered to namespace were not changed.

**Comment by andrewadare** [comment]
Oh boy. I'll fix it

**Comment by jessegreenberg** [comment]
Ah, sorry I didn't see your message!  Since I was already working in there for #53 I already committed the fix.

**Comment by andrewadare** [comment]
Even better.

**Comment by jessegreenberg** [comment]
Re-closing.
