### ISSUE TITLE
Voltmeter probe locations are not quite ideal in keyboard nav

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#41]
After selecting a probe, you can use the arrow keys to move to set locations (free movement is not allowed). The locations for the top and bottom plates of the capacitors are good in most situations, but at smaller separations and smaller plate areas, the probes do not quite reach:
![probea11y](https://cloud.githubusercontent.com/assets/5863899/14330527/37041500-fbfe-11e5-8a9f-593fdcadf01d.PNG)

I've tried this in Win 10 Chrome/Edge. For phetsims/tasks/issues/566

**Comment by jessegreenberg** [comment]
Thanks @phet-steele, fixed in above commit.  Closing.
