### ISSUE TITLE
Bar Graphs selectable by keyboard nav while disabled

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#44]
@jessegreenberg this seems like buggy behaviour to me, but maybe it isn't? When the "Bar Graphs" option is unchecked, it is still possible to tab select the bar graph (on both screens).
![bara11y](https://cloud.githubusercontent.com/assets/5863899/14333254/f3ed3a82-fc0a-11e5-8071-e20fd0df5f75.PNG)

I've tried this in Win 10 Chrome/Edge. For phetsims/tasks#566

**Comment by jessegreenberg** [comment]
Yes, this is buggy behavior.  Bar graphs should not be in the navigation order when invisible.

**Comment by jessegreenberg** [comment]
Fixed in the commits above, closing.
