### ISSUE TITLE
branch: wip

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#5]
The wip branch holds a snapshot of the state of Capacitor Lab as a work in progress.  This sim state includes all work completed by @EmilyRandall as of 5/28/15.

**Comment by andrewadare** [comment]
@jessegreenberg I'm doing a bit of housekeeping here - do we still need this issue? If so, no problem, otherwise feel free to close it.

**Comment by jessegreenberg** [comment]
Thanks @andrewadare, yes I think we do.  I would like to keep this branch around for when we start to work on accessibility in this sim again, and we decided a while back to document branches with issues like this.

**Comment by pixelzoom** [comment]
@jessegreenberg I don't see this branch? Was it deleted? Can this issue be closed?

**Comment by jessegreenberg** [comment]
Hmm, that is too bad - yes, it looks like branch was deleted.  Not a huge loss, PhET accessibility has changed a lot since we were originally playing with designs in this sim. Closing.
