### ISSUE TITLE
Instrument for phet-io

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#50]
From https://github.com/phetsims/phet-io/issues/368, @andrewadare let's discuss your status for capacitor lab basics and when it would be a good time to start collaboration for phet-io instrumentation.

**Comment by andrewadare** [comment]
A lot of cleanup has taken place in the past week. Many refactoring tasks have been completed. There's one major outstanding cleanup item, which is the removal of accessibility code from master (#23, #46). @jessegreenberg is working on that this week (and may do some delegating to me).

Since we are close, it is not too early to lay out a plan. I am available to discuss this any time soon, even today.

**Comment by samreid** [comment]
Hi @andrewadare, today is a good day for me to work on phet-io.  Let me know if you have time before 3pm to start instrumentation for Capacitor Lab Basics.

**Comment by jessegreenberg** [comment]
@samreid and @andrewadare feel free to begin instrumentation, but I will also mention that Capacitor Lab: Basics is still in a heavy refactor phase, and it is also in the process of its first dev test.  I am currently working on these issues:

- https://github.com/phetsims/capacitor-lab-basics/issues/47
- https://github.com/phetsims/capacitor-lab-basics/issues/34
- https://github.com/phetsims/capacitor-lab-basics/issues/38
- https://github.com/phetsims/capacitor-lab-basics/issues/12
- https://github.com/phetsims/capacitor-lab-basics/issues/33
- https://github.com/phetsims/capacitor-lab-basics/issues/34

A few of these could change constructor signatures, and we may collide as as we make changes.

**Comment by samreid** [comment]
@jessegreenberg that's good to know.  @andrewadare and I can wait until things settle down a bit.  Can you un-"hold" this issue once things are more stable?

**Comment by jessegreenberg** [comment]
Thanks @samreid, I will un-"hold" and assign to you once these issues are wrapping up.

**Comment by andrewadare** [comment]
Instrumentation status of model component properties:
 - [x] Battery
 - [x] Capacitor
 - [x] CircuitSwitch
 - [x] CLBModel
 - [x] AbstractCircuit
 - [x] BarMeter
 - [x] Voltmeter
 - [ ] Wire
 - [x] WireSegment

Wire has a shapeProperty only, which we don't serialize out. So it looks like the model properties are done.

**Comment by andrewadare** [comment]
This sim has been instrumented and reviewed several months ago.
