### ISSUE TITLE
Voltmeter readout layout change

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#51]
I notice that the readout is a bit tight on the voltmeter when the voltage reads negative:
![capture](https://cloud.githubusercontent.com/assets/6396244/14500683/3eff33c2-0160-11e6-98a9-de440f6b30a4.PNG)

The value also jumps around in the panel when changing sign, and it is a little distracting in this case.

**Comment by jessegreenberg** [comment]
This kind of issue is of lower priority until after code is prepped for instrumentation.

**Comment by arouinfar** [comment]
@jessegreenberg I think this can be taken care of by bumping down the font size of the readout one or two points. It also looks like the readout window isn't quite centered within the body. There's also more negative space on the right side of the voltmeter body, so you can probably also expand the size of the box by a pixel or two on the right.

**Comment by jessegreenberg** [comment]
> It also looks like the readout window isn't quite centered within the body

I think this is because the image for the body itself was exported with a little bit of asymmetric space around it.  I will try to export a new image with from the asset with no space.

**Comment by arouinfar** [comment]
@jessegreenberg I trimmed the artboard and exported a new .png. Perhaps this will fix the issue.

[voltmeter_body.png](https://cloud.githubusercontent.com/assets/8419308/14849533/c3c1ccae-0c88-11e6-807f-2fb56546fc9b.png)

**Comment by phet-steele** [comment]
@jessegreenberg @arouinfar I don't think this issue exists anymore (with regards to the cramped feeling of negative numbers)?
<img width="219" alt="screen shot 2016-10-14 at 10 52 05 am" src="https://cloud.githubusercontent.com/assets/5863899/19395741/66f63fec-91fc-11e6-93c7-1d2b98063832.png">

**Comment by arouinfar** [comment]
Looks good to me @phet-steele @jessegreenberg.
