### ISSUE TITLE
Rename types prefixed with CapacitorLabBasics

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#52]
A few types in this sim have 'CapacitorLabBasics' as a prefix to the name, creating very long names, like
'CapacitorLabBasicsLightBulbScreenView'.  This sim would benefit from changing the names to have the 'CLB' acronym instead, changing the above example to CLBLightBulbScreenView.

There are also a few types with a 'CL' prefix, likely from when this sim was still 'Capacitor Lab'.  As we do this, we should rename these files to have the 'CLB' prefix for consistency.

**Comment by andrewadare** [comment]
These files will be renamed:

 - [ ] common/model/CapacitorLabBasicsModel.js
 - [ ] common/view/control/CapacitorLabBasicsViewControl.js
 - [ ] light-bulb/model/CapacitorLabBasicsLightBulbModel.js
 - [ ] light-bulb/view/CapacitorLabBasicsLightBulbScreenView.js
 - [ ] light-bulb/CapacitorLabBasicsLightBulbScreen.js

**Comment by andrewadare** [comment]
There are pretty much no files left to touch in this repo, so I better close this....
