### ISSUE TITLE
Negative charge won't dissipate

### ISSUE THREAD

**Issue by BryceAG** [phetsims/capacitor-lab-basics#54]
Test device:
Bates

Operating System:
Win 7

Browser:
Chrome

Problem description:
If the capacitor is given negative charge, then connected to the light bulb, it will keep the same charge. This happens regardless of how negative the charge is, as long as it is negative.

Steps to reproduce:
while the capacitor is hooked up to the battery, set the battery to a negative voltage. Then connect to the light bulb

Severity:

Screenshots:
![image](https://cloud.githubusercontent.com/assets/15327201/14506764/b2a7b7e2-017c-11e6-8c0e-52d323f0af16.png)

Troubleshooting information (do not edit):
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.16/capacitor-lab-basics_en.html
Version: 1.0.0-dev.16 2016-04-12 21:32:21 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36
Language: en-US
Window: 1366x667
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 10 uniform: 253
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"084c71cf","branch":"master"},"babel":{"sha":"d453849c","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"capacitor-lab-basics":{"sha":"e71a4121","branch":"master"},"chipper":{"sha":"b2e0b31e","branch":"master"},"dot":{"sha":"833eef12","branch":"master"},"joist":{"sha":"393ac1c9","branch":"master"},"kite":{"sha":"24ad131a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"d7eed2d1","branch":"master"},"scenery":{"sha":"7db0478c","branch":"master"},"scenery-phet":{"sha":"71c5dea5","branch":"master"},"sherpa":{"sha":"b74418c0","branch":"master"},"sun":{"sha":"3c696e66","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

related to phetsims/tasks#575

**Comment by BryceAG** [comment]
additionally, if you change the size of the capacitor while this is happening, the light bulb will still glow the same amount unchanging, but the current arrows will show up and the bar graphs will still change. If the charge is positive the bulb glow will still change accordingly.

**Comment by jessegreenberg** [comment]
@andrewadare would you mind looking at this?  I think this might be related to the voltage threshold change (https://github.com/phetsims/capacitor-lab-basics/issues/30)

**Comment by arouinfar** [comment]
Also observed on Mac OSX 10.11.2 and Chrome 49.

**Comment by andrewadare** [comment]
Sorry, just learned that using the word "fixes" in a commit message automatically closes the issue. @jessegreenberg, I believe this is resolved now.

**Comment by jessegreenberg** [comment]
Octocat can be silly sometimes :octocat:, I do that too often as well.  I think it automatically closes if 'fix' comes immediately before the issue number reference.  Commit looks good, and does indeed fix the issue.  Closing.
