### ISSUE TITLE
Development HTML is out-of-date

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#55]
While working on https://github.com/phetsims/tandem/issues/9 I ran 

```
for-each.sh active-runnables grunt generate-development-html
```

This indicated capacitor-lab-basics_en.html was out of date.  I'll commit shortly.

**Comment by samreid** [comment]
Fixed in the commit above, reassigning to @andrewadare or @jessegreenberg to verify.

If this change was intended to launch the simulation in "phet" brand, the recommended way to do so is with the query parameter "?brand=phet", or by launching from phetmarks which does this automatically.

**Comment by andrewadare** [comment]
I ran `grunt generate-development-html` yesterday afternoon (while working on #48), then @jessegreenberg deployed a dev version to spot shortly afterward. I am not sure how/why the HTML came to be marked as out of date.

**Comment by samreid** [comment]
@andrewadare I suspect that if you ran `grunt generate-development-html` again, it would revert to the wrong brand (would be good to verify this).

Do you have a build-local.json file in your $HOME/.phet directory?  If so, does it have this line?

```json
"brand":"phet"
```

If you have the build-local.json file and brand:phet, then run `grunt generate-development-html` it should come out properly.

**Comment by andrewadare** [comment]
I do not have ~/.phet/build-local.json. The [docs](https://github.com/phetsims/phet-info/blob/master/sim_deployment.md) say that creating it is beyond their scope. But I tried
```
grunt generate-development-html --brand=phet
```
and got this change:
```
-    var brand = brandMatch ? decodeURIComponent( brandMatch[ 1 ] ) : 'adapted-from-phet';
+    var brand = brandMatch ? decodeURIComponent( brandMatch[ 1 ] ) : 'phet';
```
> it should come out properly.

Is this the correct outcome? Am I supposed to  commit it?

**Comment by jessegreenberg** [comment]
That looks correct @andrewadare, that matches the commit from @samreid in a28a237b8c5a22309e7795870a772b7f46f229ff.  We can meet at some point to set up your build-local.json file.

**Comment by samreid** [comment]
> Am I supposed to commit it?

I think I already did so here: https://github.com/phetsims/capacitor-lab-basics/commit/a28a237b8c5a22309e7795870a772b7f46f229ff

**Comment by samreid** [comment]
You will need a correct build-local.json file, it is not clear how you got the right answer in https://github.com/phetsims/capacitor-lab-basics/issues/55#issuecomment-209627936 without the right brand in the build-local.json file.

**Comment by andrewadare** [comment]
Will set up build file with @jessegreenberg next week,  in conjunction with account setup on spot server. Since all that is unrelated to this, and this has been resolved, I will close now.
