### ISSUE TITLE
Document the minimum number of E field lines in the Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#57]
Tested on latest Mac/Chrome and Mac/Safari as part of https://github.com/phetsims/tasks/issues/575. 

When the capacitor discharges, the number of electric field lines will reduce as the plate charge dissipates. However, once the plate charge reaches ~0.12 pC the number of electric field lines stays constant until the plate charges reaches 0.0 pC. This is particularly noticeable, as it could take several seconds for the capacitor to fully discharge once reaching the 0.12 pC mark.

![clb_fieldlines](https://cloud.githubusercontent.com/assets/8419308/14551622/d053515e-0292-11e6-830a-75a6f5b2e32a.gif)

**Comment by jessegreenberg** [comment]
It looks like this behavior was also in the Java version but is particularly noticeable now that the capacitor can discharge.
![recording 9](https://cloud.githubusercontent.com/assets/6396244/14568003/204efd96-02f4-11e6-8d59-768e5fecee72.gif)

**Comment by jessegreenberg** [comment]
From the Java sim, the minimum number of electric field lines was 4 per quadrant, or 16 for the whole capacitor.  I am not sure why this limit was used.  We could easily reduce this to one field line per quadrant of the capacitor so that it looks like this as it discharges.  Would this suffice @arouinfar?
![recording 10](https://cloud.githubusercontent.com/assets/6396244/14618870/054e92e2-0572-11e6-9f0b-2d701820a101.gif)

**Comment by arouinfar** [comment]
That does indeed seem reasonable @jessegreenberg. Nice work!

I'll need to eventually document this as a model simplification in the Teacher Tips, so please reassign this issue to me once you've finished the implementation.

**Comment by jessegreenberg** [comment]
Great, thanks!  This was done in the above commit, reassigning to @arouinfar.

**Comment by jessegreenberg** [comment]
From the change in #59, the minimum number of field lines is no longer important since the density is changing directly with the strength of the electric field.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg. I'm still going to document this in the Teacher Tips, because there is still a minimum number of E-field lines, even though the density of the lines can change.
