### ISSUE TITLE
Current stops flowing too early on discharge

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#58]
When discharging the capacitor, the current indicators will disappear before the plate voltages hits zero.  They begin to fade around 0.004 Volts.

**Comment by jessegreenberg** [comment]
@andrewadare would you mind looking into this bug?

**Comment by andrewadare** [comment]
Verified that it's not due to the voltage thresholding optimization...still investigating.

**Comment by andrewadare** [comment]
When I insert this line into the LightBulbCircuit.js step() function,
```
console.log( this.bulbTopCurrentIndicator.currentAmplitudeProperty.get(), this.capacitor.platesVoltage / this.lightBulb.resistance );
```
I see that the current values are awfully small. They begin their exponential decay at values near 1e-13. This must be because in CircuitConfig.js the resistance is huge:
```
var LIGHT_BULB_RESISTANCE = 5e12; // Ohms
```
Isn't that  too large for a physical light bulb by at least 9 orders of magnitude? If there's some visual reason, it might be worth adding a comment to explain.

The observable current and the V/R value both drop below ~1e-16 in a couple seconds. It has me wondering if this is just an artifact of floating-point comparison, along the lines of this example:
```
$ node
> 1 + 1e-17 > 1
false
```

**Comment by andrewadare** [comment]
Scratch that last point about floating-point comparison. But it is the case that the currentAmplitude goes to identically zero, while the V/R value remains small (1e-15) but finite.

I just think all this would be easier to debug if the resistance were not so large.

**Comment by jessegreenberg** [comment]
> If there's some visual reason, it might be worth adding a comment to explain.

Since the voltage and capacitance values are 'realistic' for this sim, the resistance in the light bulb had to be extremely large so that the time constant is large enough to see the discharge.  There is a note about this in LightBulb.js, but I agree that a comment about this would be good in CircuitConfig since that is where the actual resistance variable is defined for this sim.

**Comment by jessegreenberg** [comment]
It looks like in ```updateCurrentAmplitude()```, ```this.getTotalCharge()``` is returning 0 because that function calls ```getAirPlateCharge()``` and ```getDielectricPlateCharge()```, both which return 0 if less then ```CLConstants.MIN_PLATE_CHARGE```.  This was probably done to make sure that the current indicators don't stay visible for too long, but maybe the correction went too far.

We could try reducing the value of ```CLConstants.MIN_PLATE_CHARGE``` to see if that helps.

**Comment by andrewadare** [comment]
That may help, but this all feels kind of messy.

AbstractCircuit.js computes currentAmplitude as dQ/dt, while  Capacitor.plateVoltage is assigned  using Q=CV in LightBulbCircuit.js. At such tiny current values, I think we're sensitive to discreteness of timesteps, numerical precision, and so forth. The model is just not self-consistent all the way down to the boundaries of floating-point precision.

**Comment by jessegreenberg** [comment]
> AbstractCircuit.js computes currentAmplitude as dQ/dt, while Capacitor.plateVoltage is assigned using Q=CV in LightBulbCircuit.js.

This is certainly an issue with the model!  Especially since dQ/dt is meaningless here, dt is  the time step from joist, a somewhat arbitrary length of time.  If we had needed the exact values of current, this would be terrible.  In this case, the current indicators only care about non zero values and direction, so magnitude of current does not matter.  This gets the job done, but is a bit crude, so I would be happy to discuss another alternative.

**Comment by jessegreenberg** [comment]
Perhaps we could use a rule like 'if capacitor plate voltage is less than precision allowed by voltmeter plate charge (and current) should be zero?  This way we aren't dealing with arbitrary value limits like ```CLConstants.MIN_PLATE_CHARGE```.

**Comment by andrewadare** [comment]
The current through the indicators is consistent with the bulb V/R by construction now. This might be fixed "too much"--the arrows hang around quite a bit longer now. I'll leave it up to somebody else to decide what's the optimal visual effect.

**Comment by andrewadare** [comment]
It's a bit messy that I've over-written the "bogus" dQ/dt value assigned to `this.currentAmplitudeProperty` in the LightBulbCircuit.js step function.

It may be best to just remove the call to updateCurrentAmplitude() in AbstractCircuit.js for clarity.

**Comment by jessegreenberg** [comment]
Changes look good @andrewadare, and thanks for enhancing the documentation.

We still need the updateCurrentAmplitude method in AbstractCircuit because this is how current is calculated when the light bulb is disconnected.  If V = I / R in step(), current will not flow via dQ/dT when the capacitor is connected to the battery and changes capacitance.

I added updateCurrentAmplitude to LightBulbCircuit, which overrides the function in AbstractCircuit and calculates current differently depending on the circuit connection.  @andrewadare would you mind reviewing this change?

**Comment by andrewadare** [comment]
This looks good, both on the light bulb side, and for the battery (I now see that ddc0351254686654aff1491e1c97a7eaf7d66c96 didn't properly handle the latter; sorry for that).

The only other visual tweak I might suggest for the discharge is to start fading out the current arrows at MIN_VOLTAGE,  rather than zero. That way, the situation where the current arrows are showing while the voltmeter reads zero is shorter-lived. But I'm not sure what people will consider to be the most correct representation.

**Comment by jessegreenberg** [comment]
Thanks for the review comments and recommendation @andrewadare.  I created a new issue to discuss some of the issues involving precision for the various values in this sim ( #60 ).  I think that this issue can now be closed.
