### ISSUE TITLE
Shift E-field lines up a little for better alignment between plates

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#59]
At times, the E-field lines align with the outside edge of the plates. I've noticed there is a gap between the lines and the top plate in the last few dev versions. 

In Java the field lines will touch the bottom edge of the top plate and the top edge of the bottom plate.
![image](https://cloud.githubusercontent.com/assets/8419308/14649570/f1b267c8-0624-11e6-9826-8da3d79f7283.png)

In HTML5 the field lines look like they've shifted down, and it doesn't look as clean as Java. There is a gap between the field lines and the top plate, and a bit too much overlap between the field lines and the bottom plate.
![image](https://cloud.githubusercontent.com/assets/8419308/14649579/fbd6c118-0624-11e6-8a73-5eb2428639b0.png)  ![image](https://cloud.githubusercontent.com/assets/8419308/14650919/e057ec40-062a-11e6-89cf-00c36309bd52.png)

**Comment by jessegreenberg** [comment]
It also looks like the arrows are slightly off center when the electric field is oriented toward the top plate.
![capture](https://cloud.githubusercontent.com/assets/6396244/14658124/ed1173d8-064e-11e6-8c52-48e7e48e7674.PNG)

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/capacitor-lab-basics/issues/59#issuecomment-212159274 is fixed.

**Comment by jessegreenberg** [comment]
@arouinfar here is a dev version with some changes to the layout of the electric field lines.  Would you mind reviewing and letting me know if any more changes need to be made?

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.18/capacitor-lab-basics_en.html

**Comment by arouinfar** [comment]
It's looking pretty good @jessegreenberg! One thing I noticed is that when the plate area is small, the electric field lines will spread out as the charge decreases, even when down to the minimum of four field lines. This is the desired behavior-- the E-field line density is decreasing with the plate charge.

<img width="174" alt="screen shot 2016-04-20 at 11 34 13 am" src="https://cloud.githubusercontent.com/assets/8419308/14684292/88580454-06ec-11e6-8741-79517c2c151f.png"> <img width="174" alt="screen shot 2016-04-20 at 11 31 23 am" src="https://cloud.githubusercontent.com/assets/8419308/14684294/88678226-06ec-11e6-8560-3d2566e2d9bc.png"> <img width="175" alt="screen shot 2016-04-20 at 11 31 48 am" src="https://cloud.githubusercontent.com/assets/8419308/14684295/8867830c-06ec-11e6-95ba-ef7e8d29c308.png">

However, if the plate area is large, the field lines seem to stay in place once it reaches four field lines. Increasing the plate area increases the capacitance, and therefore the voltage decay time, so it's pretty noticeable that the charge decreases, but the number of field lines stays the same. I realize that this is a necessary model simplification (as noted in #57), but I think it would be helpful if the E-field lines could move towards the edge of the plate, as it does when the plate area is small.
<img width="241" alt="screen shot 2016-04-20 at 11 37 58 am" src="https://cloud.githubusercontent.com/assets/8419308/14684296/88686dda-06ec-11e6-90ae-c09fe1969616.png">  <img width="242" alt="screen shot 2016-04-20 at 11 38 33 am" src="https://cloud.githubusercontent.com/assets/8419308/14684293/88653336-06ec-11e6-8766-bd1f8835ab94.png">  <img width="240" alt="screen shot 2016-04-20 at 11 36 27 am" src="https://cloud.githubusercontent.com/assets/8419308/14684298/88699ea8-06ec-11e6-8aa9-0f9b63c306c0.png"> <img width="241" alt="7jmda" src="https://cloud.githubusercontent.com/assets/8419308/14684321/ae9cf732-06ec-11e6-90b4-3de81fb9ed4c.png">

**Comment by jessegreenberg** [comment]
In the Java version, the spacing is determined by the number of field lines rather than the magnitude of the electric field directly.  I changed this a bit so that the line density is directly related to the strength of the electric field.  The result is a slightly different behavior, but a much smoother animation and the density will also change as requested in https://github.com/phetsims/capacitor-lab-basics/issues/59#issuecomment-212532921.

Here is a new dev version with this behavior, would you mind reviewing @arouinfar?
http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.19/capacitor-lab-basics_en.html

**Comment by arouinfar** [comment]
@jesseegreenberg dev.19 feels good to me. Thanks for adjsuting the model! I think that tying the line density to plate charge is a nice way to mediate the simplication relating the number of lines to the plate charge. I'm going to leave this issue self-assigned to document this behavior in the Teacher Tips.
