### ISSUE TITLE
Rename this repo to "capacitor-lab-basics"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/capacitor-lab-basics#6]
@jessegreenberg - please rename the repo as we discussed

**Comment by pixelzoom** [comment]
I took care of the rename, since @jessegreenberg doesn't have Admin permissions. I also updated chipper active-repos and active-sims.

**Comment by ariel-phet** [comment]
Thanks @pixelzoom - I decided to make @jessegreenberg a part of the "owner" team, since it seems appropriate to give him admin privileges. Thanks for taking care of the issue though!
