### ISSUE TITLE
Precision issues for current, voltage, plate charge

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#60]
Due to the precision of various values in this simulation it is possible for some values to be zero while others are still observable.  Since these values are correlated, is it possible that this will cause confusion? I have a vague memory of discussing this already, so my apologies if I am backtracking here.

For example:

- Plate charge can be zero while voltage is still observable
- Stored energy can be zero while there is still charge on the plates
- Current will continue to flow while there is no charge on the plates

Can be observed in the most recent dev version:
http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.18/capacitor-lab-basics_en.html

**Comment by arouinfar** [comment]
@jessegreenberg no matter how many decimal places we choose to display, there will be instances where some quantity will apparently be zero, but observations could be made to the contrary (such as those you listed in your comment). These kinds of observations can spark valuable discussions in the classroom around precision. For that reason, we decided to leave the number of decimal places as is, but I should document this issue in the Teacher Tips.

**Comment by jessegreenberg** [comment]
OK, sounds good @arouinfar, thanks for describing.
