### ISSUE TITLE
Strings should be rescalable

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#61]
Steele pointed out that the strings are not currently in fixed-width boxes. Creating long strings with the `stringTest=double` query parameter shows the effect.

We'll need to go through and fix all the translatable strings, and possibly rotate the sliders so that the labels are on the right hand side.

**Comment by andrewadare** [comment]
@jessegreenberg, I self-assigned this one a while back, but don't know exactly how to do it (other than self-educating from examples). Maybe it would be a fun pairing project sometime soon? You could get me started, then turn me loose to finish it off.

**Comment by jessegreenberg** [comment]
Sounds good @andrewadare!  I did a significant portion of this for dev.22 in https://github.com/phetsims/capacitor-lab-basics/commit/0411b044cc00fd919c4babd6d040424aacf4cad1 but there is still some work to do, it would be great to work on this together.

**Comment by jessegreenberg** [comment]
@andrewadare and @jessegreenberg worked together to wrap this up.  The commit above completes i18n and cleans things up so scaling is calculated by screen view layout where possible.  Closing.
