### ISSUE TITLE
Missing menu thumbnails

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/capacitor-lab-basics#63]
I would guess that this is already known, but since it doesn't appear that there is already an issue about it, I'll write one just in case. 

In the menu, there are no screenshots of the sim on the thumbnails, only a red and blue rectangle.
![screen shot 2016-04-20 at 1 18 34 pm](https://cloud.githubusercontent.com/assets/11947677/14687368/6ccd41f0-06fa-11e6-932c-c4b0e6d1887a.png)
phetsims/tasks#575

**Comment by phet-steele** [comment]
Yup @brroberts1231 they are missing. They are currently acting as placeholders. You'll see this in lots of early development sims until design of the sim is more finalized and someone takes the time to make/code them. There will eventually be icons there don't worry :smile:, thanks for your vigilance.
