### ISSUE TITLE
Voltmeter readout doesn't update accross plates if V never changes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#64]
1. Increase V of battery, set plate separation to minimum.
2. Place the voltmeter probes just above and just below the plates so the readout is "? V"
3. Increase separation so the probes are now on each plate. Readout is still "? V".

![clb01](https://cloud.githubusercontent.com/assets/5863899/14687638/dfb38caa-06fb-11e6-8d95-9a2722736b71.gif)
Changing V with the battery, or disconnecting the plates from the battery, etc... will have the readout update. Seen on Win 10 browsers. For phetsims/tasks/issues/575.

Troubleshooting information:
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.16/capacitor-lab-basics_en.html
Version: 1.0.0-dev.16 2016-04-12 21:32:21 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
Language: en-US
Window: 1600x767
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"084c71cf","branch":"master"},"babel":{"sha":"d453849c","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"capacitor-lab-basics":{"sha":"e71a4121","branch":"master"},"chipper":{"sha":"b2e0b31e","branch":"master"},"dot":{"sha":"833eef12","branch":"master"},"joist":{"sha":"393ac1c9","branch":"master"},"kite":{"sha":"24ad131a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"d7eed2d1","branch":"master"},"scenery":{"sha":"7db0478c","branch":"master"},"scenery-phet":{"sha":"71c5dea5","branch":"master"},"sherpa":{"sha":"b74418c0","branch":"master"},"sun":{"sha":"3c696e66","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by jessegreenberg** [comment]
Would you mind checking out this issue @andrewadare?  My guess is that the voltmeter readout needs to be linked to the capacitor geometry.

**Comment by andrewadare** [comment]
Hopefully this is addressed now, but I'll leave it to the experts to test more thoroughly.

**Comment by andrewadare** [comment]
This issue has been fixed for quite a while. Closing.
