### ISSUE TITLE
Positive probe wire is detached from the voltmeter

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#65]
Seems self explanatory, should be slightly moved to the right to line up with the red dot. For https://github.com/phetsims/tasks/issues/575.
![positiveprobe](https://cloud.githubusercontent.com/assets/5863899/14689903/9c11b246-0706-11e6-84f6-986a2448f167.PNG)

**Comment by jessegreenberg** [comment]
@andrewadare would you mind looking into this issue?
