### ISSUE TITLE
Resetting the "Capacitance" screen does not reset the wire connection to the battery.

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#66]
Simply disconnect the plates and press reset all; the plates will remain disconnected. The "Light Bulb" screen correctly resets the wire connection.
Seen on Win 10 browsers. For phetsims/tasks#575.

Troubleshooting information:
Name: ‪Capacitor Lab: Basics‬
URL: http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.16/capacitor-lab-basics_en.html
Version: 1.0.0-dev.16 2016-04-12 21:32:21 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
Language: en-US
Window: 1600x767
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"084c71cf","branch":"master"},"babel":{"sha":"d453849c","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"capacitor-lab-basics":{"sha":"e71a4121","branch":"master"},"chipper":{"sha":"b2e0b31e","branch":"master"},"dot":{"sha":"833eef12","branch":"master"},"joist":{"sha":"393ac1c9","branch":"master"},"kite":{"sha":"24ad131a","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"d7eed2d1","branch":"master"},"scenery":{"sha":"7db0478c","branch":"master"},"scenery-phet":{"sha":"71c5dea5","branch":"master"},"sherpa":{"sha":"b74418c0","branch":"master"},"sun":{"sha":"3c696e66","branch":"master"},"tandem":{"sha":"2441eec6","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by jessegreenberg** [comment]
Looks like the connection property is not being reset, but this should be fixed as part of #67.

**Comment by jessegreenberg** [comment]
Done in the above commit, closing.
