### ISSUE TITLE
Constructors take too many parameters

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#70]
Similar to #69, CapacitanceCircuitNode has too many parameters:

```js
  function CapacitanceCircuitNode( circuit, modelViewTransform, plateChargeVisibleProperty, eFieldVisibleProperty, currentIndicatorsVisibleProperty, maxPlateCharge, maxEffectiveEField ) {
```

There are probably others. We can look into using an ESLint rule to count parameter numbers.

**Comment by samreid** [comment]
Here's a lint rule you can temporarily add to .eslintrc to check for 4 max parameters:

```js
"max-params": [2,4],
```

**Comment by samreid** [comment]
There are 21 cases reported when I enable this rule:

/Users/samreid/github/capacitor-lab-basics/js/capacitance/view/CapacitanceCircuitNode.js
  31:3  error  This function has too many parameters (7). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/CircuitSwitch.js
  34:3  error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/SwitchedCapacitor.js
  29:3  error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/circuit/AbstractCircuit.js
  30:3  error  This function has too many parameters (6). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/circuit/ParallelCircuit.js
  300:21  error  This function has too many parameters (6). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/shapes/BoxShapeCreator.js
   48:20  error  This function has too many parameters (6). Maximum allowed is 4  max-params
   83:22  error  This function has too many parameters (6). Maximum allowed is 4  max-params
  123:26  error  This function has too many parameters (6). Maximum allowed is 4  max-params
  155:21  error  This function has too many parameters (6). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/wire/BatteryToSwitchWire.js
  29:3  error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/wire/CapacitorToSwitchWire.js
  26:3  error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/model/wire/LightBulbToSwitchWire.js
  29:3  error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/view/CLBCircuitNode.js
  38:3  error  This function has too many parameters (7). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/view/CapacitorNode.js
  31:3  error  This function has too many parameters (6). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/view/ConnectionAreaNode.js
  42:3  error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/view/PlateChargeNode.js
   76:3   error  This function has too many parameters (6). Maximum allowed is 4  max-params
  219:25  error  This function has too many parameters (5). Maximum allowed is 4  max-params
  235:3   error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/view/meters/BarMeterNode.js
  60:3  error  This function has too many parameters (5). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/common/view/meters/ProbeWireNode.js
  31:3  error  This function has too many parameters (7). Maximum allowed is 4  max-params

/Users/samreid/github/capacitor-lab-basics/js/light-bulb/view/LightBulbCircuitNode.js
  33:3  error  This function has too many parameters (7). Maximum allowed is 4  max-params

✖ 21 problems (21 errors, 0 warnings)

**Comment by andrewadare** [comment]
This issue ended up leading to a lot of work, but the refactored interfaces are simpler in many places now, and led to other improvements. All constructors take 4 or fewer parameters now, except the following, which have 5:

 - PlateAreaDragHandler
 - PlateSeparationDragHandler
 - BarMeterNode
 - VoltmeterProbeNode

Of these, only BarMeterNode doesn't yet have a tandem instance. It's not worth trying to refactor this one in my opinion. I think we should close this issue and move on.
