### ISSUE TITLE
Review phet-io instrumentation

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#79]
During #50 @andrewadare has been working to instrument the simulation for phet-io.  He said it is getting to a good point for review.

**Comment by samreid** [comment]
I committed JSDoc fixes above.

**Comment by samreid** [comment]
I searched every occurrence of `tandem` in capacitor-lab-basics and they seemed reasonable.  
I searched for `tandem.addInstance` in capacitor-lab-basics to see if they were properly paired with `tandem.removeInstance`, and there is only one and it is currently only used for air dielectric.  If we add tandems for other dielectrics (see #81) then we will likely have to implement `dispose` and `tandem.removeInstance`.

**Comment by samreid** [comment]
I used the events wrapper to look for missing messages from view and model components.

**Comment by samreid** [comment]
Things are generally looking very good, nice work @andrewadare!  I'm not aware of any other work other than what is identified in the issues linked above.  Reassigning to you to review my commits on this issue and let me know if you have any questions about the review.

**Comment by andrewadare** [comment]
Thanks for this thorough review @samreid! I will make it a priority to address the issues that came up.
