### ISSUE TITLE
Should DielectricMaterial require tandem?

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#81]
During #79 I saw that DielectricMaterial has the tandem as optional.  Should the tandem be required here?  Also, be aware that if the tandem is required, then the tandem will be required in TDielectricMaterial.fromStateObject.

**Comment by samreid** [comment]
Likewise, `CustomDielectricMaterial` is created with null tandem.  Can we investigate adding a tandem for that?  Or are many CustomDielectricMaterial instances created and thrown away?

**Comment by andrewadare** [comment]
While preparing CL:B for code review, I found a [TODO](https://github.com/phetsims/capacitor-lab-basics/blob/78860499ca433d1cdb1e339b88191add9567f1d5/js/common/model/DielectricMaterial.js#L58) in DielectricMaterial.js related to this issue.

I think we should leave the Tandem placeholder `null` there for now. As a design choice, dielectric support in this sim is somewhere between nonexistent and incomplete. I'm not sure what useful information instrumentation would provide if added.

If we agree on that, we can replace the TODO with an explanation, and possibly a reference to this issue.

And to directly address the question for this issue, I think the tandem should remain optional for this type.

@samreid do you agree?

**Comment by samreid** [comment]
Yes, that sounds like a good plan.
