### ISSUE TITLE
Should tandem be required?

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#82]
During #79 I noticed that tandem is optional in SwitchedCapacitor and other places such as:
- [x] SwitchedCapacitor
- [x] AbstractCircuit
- [x] BarMeter
- [x] CapacitanceMeter
- [x] there are probably others, search for them with `tandem ?` or the likes
  
  Should it be required here? If not, it should be documented why it is optional.

**Comment by samreid** [comment]
If it would simplify the code *a lot* by adding a tandem to the temporary "intermediate" circuit, we should do it.  It seems awkward and complicated to have so many optional tandems in sim code.

**Comment by andrewadare** [comment]
I have documented occurrences of the "optional tandem" pattern to say that `null` is allowed for components of a temporary circuit that is created only for calculating quantities like voltage or stored energy.

**Comment by andrewadare** [comment]
This issue has been superseded by https://github.com/phetsims/phet-io/issues/748
