### ISSUE TITLE
2nd screen checkboxes don't appear instrumented

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#89]
During #79 I noticed these checkboxes:
![image](https://cloud.githubusercontent.com/assets/679486/15168271/38402094-16ed-11e6-8a70-ee4dc39bae6b.png)

aren't sending user (blue) messages:
![image](https://cloud.githubusercontent.com/assets/679486/15168275/4e99f374-16ed-11e6-993d-db988481488c.png)

**Comment by andrewadare** [comment]
@samreid, can I get a little guidance on this one? My approach in these two commits came from looking at CLBViewControlPanel (which we did early in this project). I called tandem.addInstance; not sure if that is the right thing to do here.

**Comment by samreid** [comment]
Fixed in the above commit, curly braces were missing.

**Comment by samreid** [comment]
Assigned to @andrewadare to review the changes and close.

**Comment by andrewadare** [comment]
Thanks for fixing this. Works as expected; closing.
