### ISSUE TITLE
Don't give Vector3 to kite

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#91]
During #79 I noticed the state wrapper is crashing because Kite is getting a Vector3 and Vector2, and finding the distance to be (x,y,NaN).  We should only give Vector2 to Kite.  @andrewadare and I discussed this today.

**Comment by samreid** [comment]
Testing of the state wrapper is on hold until this is addressed.

**Comment by andrewadare** [comment]
After 24338e0 I am no longer seeing console errors on the PhET-iO states page.
