### ISSUE TITLE
Many nodes require phet-io instrumentation

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#92]
During #79 I used the instance proxies wrapper to make all of the instrumented nodes invisible and I still saw this:

![image](https://cloud.githubusercontent.com/assets/679486/15168899/e26bb420-16f2-11e6-92f4-876d276a86d0.png)

Most of the remaining nodes need to be instrumented for phet-io, so at least they can be hidden or disabled.  I'll do one as an example then reassign to @andrewadare for further work.

**Comment by samreid** [comment]
In the above commit, I instrumented the view control panel. Now it can be disabled or hidden like so:

![image](https://cloud.githubusercontent.com/assets/679486/15168970/b47407ec-16f3-11e6-9d8b-06a08e309486.png)

@andrewadare please review my commits and proceed with instrumenting the remainder of the nodes.

**Comment by andrewadare** [comment]
Aha. I did not understand before why these needed instrumentation, since they don't have any direct support for user interactivity. Now I see; I will do it.

**Comment by andrewadare** [comment]
Both screens can be made completely blank now (by deselecting many nodes in the instance proxies page). Apart from going deeper into the scene graph, I don't know of any remaining uninstrumented nodes.
