### ISSUE TITLE
Duplicated code in the API file

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#93]
During #79 I noticed in the API file there are parts with duplicated code, such as:

![image](https://cloud.githubusercontent.com/assets/679486/15169035/410ff292-16f4-11e6-9839-21f04789e9a0.png)

This kind of thing should be factored out as much as possible.

**Comment by samreid** [comment]
Also it looks like this diff highlights #90

**Comment by andrewadare** [comment]
![image](https://cloud.githubusercontent.com/assets/154163/15198249/82005554-1793-11e6-85a7-b982a8b58aa9.png)

After handling #89, the two screens are now more dissimilar. I tried out making a function to return a kind-of common object, then patching in the new checkbox names to the result, but it sure doesn't look very nice. I hesitate to commit it.

But if the goal is really to factor the common names as much as possible, I can do so.

**Comment by andrewadare** [comment]
This is what I tried:
```js
  function screenElements( circuitNode, screenSwitch ) {

    var elements = {
      model: modelComponents,
      view: {
        voltmeterNode: voltmeterNodes,
        resetAllButton: TResetAllButton,
        viewControlPanel: TPanel.extend( {
          verticalCheckBoxGroup: verticalCheckBoxGroup
        } )
      }
    };

    elements[ circuitNode ] = {
      topSwitchNode: screenSwitch,
      bottomSwitchNode: screenSwitch,
      batteryNode: {
        sliderNode: THSlider
      },
      plateAreaDragHandleNode: {
        inputListener: TTandemDragHandler
      },
      plateSeparationDragHandleNode: {
        inputListener: TTandemDragHandler
      }
    };

    return elements;
  }

  var lightBulbScreenElements = screenElements( 'lightBulbCircuitNode', lightBulbScreenSwitch );

  lightBulbScreenElements.view.barMeterPanel = TPanel.extend( {
    capacitanceMeterCheckBox: TCheckBox,
    plateChargeMeterCheckBox: TCheckBox,
    storedEnergyMeterCheckBox: TCheckBox
  } );

  phetio.api = PhETIOCommon.createAPI( {
    capacitorLabBasics: PhETIOCommon.createSim( {
      dielectrics: {
        air: TObject
      },
      capacitanceScreen: screenElements( 'capacitanceCircuitNode', capacitanceScreenSwitch ),
      lightBulbScreen: lightBulbScreenElements
    } )
  } );
```
There are a number of things I don't like about it. In particular, it's much more difficult to see the structure.

@samreid if you have any suggestions on how to improve this, please let me know.

**Comment by andrewadare** [comment]
Just as a warning, the code above is read-only, just for discussion about how to refactor the API.

**Comment by samreid** [comment]
In the above commits, I instrumented the other reset all button and reorganized the API file a bit to prepare for factoring out parts.

**Comment by samreid** [comment]
In the above commits, I showed another way to factor out the duplicated parts.  I created these methods:

```js
  var CircuitNode = function( SwitchType ) {
    return {
      topSwitchNode: SwitchType,
      bottomSwitchNode: SwitchType,
      batteryNode: {
        sliderNode: THSlider
      },
      plateAreaDragHandleNode: {
        inputListener: TTandemDragHandler
      },
      plateSeparationDragHandleNode: {
        inputListener: TTandemDragHandler
      }
    };
  };

  var ScreenView = {
    voltmeterNode: VoltmeterNodes,
    resetAllButton: TResetAllButton,
    viewControlPanel: TPanel.extend( {
      verticalCheckBoxGroup: VerticalCheckBoxGroup
    } )
  };
```

And now the diff looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/15220185/d7877f3a-1823-11e6-8cc0-087e8b2c1361.png)

Leaving assigned to @andrewadare to review/discuss the changes.

**Comment by andrewadare** [comment]
Unsurprisingly, I like your solution better :)

Results look good in my tests, so closing.
