### ISSUE TITLE
Add initial cueing arrow to the switch

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#94]
To make the switch a more intuitive component, we would like to add an initial cue that indicates the switch can be moved.

@ariel-phet wrote
>I would think if we did such a cue we have two choices:<br>
1. It would be like wave on a string where it appears at the beginning but once you move the switch it goes away.
2. It would be like bending light, anytime you touch or hover on the switch the arrows would appear. <br><br>I would be in favor of (1)...I don't think there is much harm since we already have some other arrow cues. My instinct says to make the arrows clear but no more attractive than the "move plate" arrows. (perhaps even slightly less)

I'm also in favor of the first option, and have mocked up a few different options for cueing arrows. 

![image](https://cloud.githubusercontent.com/assets/8419308/15335147/51b66376-1c2e-11e6-98ea-4730e3912766.png)
![image](https://cloud.githubusercontent.com/assets/8419308/15335225/a670fb6a-1c2e-11e6-94cc-14eb72a717cb.png)
![image](https://cloud.githubusercontent.com/assets/8419308/15335273/df997f52-1c2e-11e6-8e1b-9d3d32dc9b91.png)
![image](https://cloud.githubusercontent.com/assets/8419308/15335282/ec1dcd28-1c2e-11e6-9efc-a93d0640fa3c.png)

I prefer the last option because the arrows feel a bit more out of the way, while cueing that the switch slides between the positions. I think that the curved arrows cue rotation about the switch's end. 

We'll discuss these options in the next design meeting, so I'll leave this issue self-assigned for now.

**Comment by ariel-phet** [comment]
@arouinfar can you mockup the last option but with a double headed arrow that is a little longer and follows the "arc" of the path the switch end would swing through?

**Comment by arouinfar** [comment]
Love the idea @ariel-phet! I think that's what I was going for, but didn't quite get there. I'll mock it up.

**Comment by arouinfar** [comment]
@ariel-phet here are a few mockups with varying color/stroke weight.
![image](https://cloud.githubusercontent.com/assets/8419308/15337879/d65adede-1c3a-11e6-86e3-d83eef28e20c.png)
![image](https://cloud.githubusercontent.com/assets/8419308/15338664/1c77477e-1c3e-11e6-8745-3cc77efc3d44.png)

Increasing the top arrow by 15%
![image](https://cloud.githubusercontent.com/assets/8419308/15338762/90e7fd7e-1c3e-11e6-8862-b75cd189790a.png)

I'm leaning towards the smaller blue arrow with a 0.5 pt stroke (bottom arrow in screenshot above).

**Comment by ariel-phet** [comment]
Yes, I agree, I would also make that arrow a bit longer, so it will have more of the arc to it

**Comment by arouinfar** [comment]
I've made the top arrow a bit longer @ariel-phet 
![image](https://cloud.githubusercontent.com/assets/8419308/15339091/fdd125e0-1c3f-11e6-8c8a-97a54be57e74.png)

**Comment by arouinfar** [comment]
As discussed in the 5/19 design meeting, the cueing arrow will have the following properties:
* Blue, double-headed, arc-shaped arrow with 0.5 pt stroke. Asset will be emailed to @andrewadare.
* Arrow will be visible on Capacitance and Light Bulb screens until the user interacts with the switch. 
* The arrow cue will disappear from BOTH screens once the switch has been used on one of the screens. For example, if a user interacts with the switch on the Capacitance screen, the arrow cue will not be visible on the Light Bulb screen.

**Comment by andrewadare** [comment]
The third check box is harder...requires sending info between screens. I haven't come across any examples of this yet. Will ask the other devs about it.

**Comment by arouinfar** [comment]
@andrewadare the third checkbox is more of a wishlist item, and less of a necessity. It would be still be nice if you could consult with the other devs to see what it would take to implement this feature.

**Comment by andrewadare** [comment]
49671ad should wrap this one up. Works as requested; closing.

**Comment by phet-steele** [comment]
@arouinfar, quick question. Do we want to arrows to return or not after Reset All?

**Comment by arouinfar** [comment]
@phet-steele, yes the arrows should reappear after Reset All. This is consistent with other cueing arrows like those in Wave on a String and Faraday's Law.
