### ISSUE TITLE
CL:B dev version 20 is up

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#95]
http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.20/

@phet-steele it's been almost a month since we put out the last dev version, and the sim has seen heavy development: extensive refactoring, many bug fixes, and a full PhET-iO pass. Many entry points for unexpected behavior.

Obviously up to @ariel-phet to assign priority for this, just letting you know this is available when you can get to it. Note that this is not a full publication deployment (e.g. strings still need work--no need to file issues about stuff like that).

cc @samreid @jessegreenberg

**Comment by ariel-phet** [comment]
@andrewadare why don't you actually close this issue, and open a dev testing task in the tasks repo, and assign to me (that is our more traditional work flow for dev testing issues).

**Comment by andrewadare** [comment]
Oops, good to know :)
