### ISSUE TITLE
Plate Area text overlaps wire

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#98]
It looks like the horizontal wires on the light bulb side of the circuit have been shortened, and there's now overlap between the Plate Area text and the wire.

dev.20 and dev.21
![image](https://cloud.githubusercontent.com/assets/8419308/15412132/68a3a232-1de2-11e6-8bcd-87ef921ce203.png)

dev.19 (desired look)
![image](https://cloud.githubusercontent.com/assets/8419308/15412148/8f446052-1de2-11e6-9aa7-53f34bca5fa4.png)

**Comment by arouinfar** [comment]
@jessegreenberg has reported this issue in #107 so this is now a duplicate issue. Closing.

**Comment by jessegreenberg** [comment]
Oops, sorry about that!  Thanks @arouinfar.

**Comment by arouinfar** [comment]
No problem! I should have tagged you in this issue.
