### ISSUE TITLE
Voltmeter funkiness near switch

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#99]
Observed in dev.21 during today's design meeting. There appears to be an issue when reading near the switch. For example, the voltage in this situation should be undefined:
![image](https://cloud.githubusercontent.com/assets/8419308/15412234/2e0f47e2-1de3-11e6-83d6-e9ea50a96e4a.png)

**Comment by jessegreenberg** [comment]
While looking into #72 I noticed that the voltmeter reads '?' for the following configuration
![capture](https://cloud.githubusercontent.com/assets/6396244/15971170/18df8a6c-2ef5-11e6-98a3-e4dc86d02743.PNG)

**Comment by jessegreenberg** [comment]
When both probes are connected to the wires connecting the battery, voltage is read correctly.  Possibly related to the touchingFreePlate function.

**Comment by jessegreenberg** [comment]
connectedToDisconnectedCapacitorTop was return true even when the capacitor was disconnected.  Fixing the issue resolves the issue for the capacitor.  However, we still have the issue for the lightbulb as well
![capture](https://cloud.githubusercontent.com/assets/6396244/15973760/57dcfcf6-2f02-11e6-924d-3de5ef4de592.PNG)
So we will need to do something similar for the lightbulb.

**Comment by jessegreenberg** [comment]
The voltmeter readout should be correct at all probe locations, closing.
